//! `apple_pay` API object models.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(missing_docs, clippy::doc_markdown, clippy::struct_excessive_bools, clippy::wildcard_imports, rustdoc::bare_urls)]

use serde::{Deserialize, Serialize};

// Models reference each other across modules; the parent re-exports every type.
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ApplePayDomain {
    /// Time at which the object was created. Measured in seconds since the Unix epoch.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub domain_name: Option<String>,
    /// Unique identifier for the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub livemode: Option<bool>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
}
