//! `billing_portal` API object models.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(missing_docs, clippy::doc_markdown, clippy::struct_excessive_bools, clippy::wildcard_imports, rustdoc::bare_urls)]

use serde::{Deserialize, Serialize};

// Models reference each other across modules; the parent re-exports every type.
#[allow(unused_imports)]
use super::*;

/// A portal configuration describes the functionality and behavior you embed in a portal session. Related guide: \[Configure the customer portal\](/customer-management/configure-portal).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct BillingPortalConfiguration {
    /// Whether the configuration is active and can be used to create portal sessions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// ID of the Connect Application that created the configuration.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub application: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub business_profile: Option<Box<PortalBusinessProfile>>,
    /// Time at which the object was created. Measured in seconds since the Unix epoch.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created: Option<i64>,
    /// The default URL to redirect customers to when they click on the portal's link to return to your website. This can be \[overriden\](https://docs.stripe.com/api/customer_portal/sessions/create#create_portal_session-return_url) when creating…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default_return_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub features: Option<Box<PortalFeatures>>,
    /// Unique identifier for the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Whether the configuration is the default. If `true`, this configuration can be managed in the Dashboard and portal sessions will use this configuration unless it is overriden when creating the session.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_default: Option<bool>,
    /// If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub livemode: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub login_page: Option<Box<PortalLoginPage>>,
    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::BTreeMap<String, String>>,
    /// The name of the configuration.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// Time at which the object was last updated. Measured in seconds since the Unix epoch.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated: Option<i64>,
}

/// The Billing customer portal is a Stripe-hosted UI for subscription and billing management. A portal configuration describes the functionality and features that you want to provide to your customers through the portal. A portal session describes the instantiation of the customer portal for a particular customer. By visiting the session's URL, the customer can manage their subscriptions and billing…
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct BillingPortalSession {
    /// The configuration used by this session, describing the features available.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub configuration: Option<serde_json::Value>,
    /// Time at which the object was created. Measured in seconds since the Unix epoch.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created: Option<i64>,
    /// The ID of the customer for this session.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer: Option<String>,
    /// The ID of the account for this session.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_account: Option<String>,
    /// Information about a specific flow for the customer to go through. See the \[docs\](https://docs.stripe.com/customer-management/portal-deep-links) to learn more about using customer portal deep links and flows.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub flow: Option<serde_json::Value>,
    /// Unique identifier for the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub livemode: Option<bool>,
    /// The IETF language tag of the locale Customer Portal is displayed in. If blank or auto, the customer’s `preferred_locales` or browser’s locale is used.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// The account for which the session was created on behalf of. When specified, only subscriptions and invoices with this `on_behalf_of` account appear in the portal. For more information, see the \[docs\](https://docs.stripe.com/connect/separ…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_behalf_of: Option<String>,
    /// The URL to redirect customers to when they click on the portal's link to return to your website.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub return_url: Option<String>,
    /// The short-lived URL of the session that gives customers access to the customer portal.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}
