//! `credit_notes` API object models.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(missing_docs, clippy::doc_markdown, clippy::struct_excessive_bools, clippy::wildcard_imports, rustdoc::bare_urls)]

use serde::{Deserialize, Serialize};

// Models reference each other across modules; the parent re-exports every type.
#[allow(unused_imports)]
use super::*;

/// Issue a credit note to adjust an invoice's amount after the invoice is finalized. Related guide: \[Credit notes\](https://docs.stripe.com/billing/invoices/credit-notes)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct CreditNote {
    /// The integer amount in cents (or local equivalent) representing the total amount of the credit note, including tax.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount: Option<i64>,
    /// This is the sum of all the shipping amounts.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount_shipping: Option<i64>,
    /// Time at which the object was created. Measured in seconds since the Unix epoch.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created: Option<i64>,
    /// Three-letter \[ISO currency code\](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a \[supported currency\](https://stripe.com/docs/currencies).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// ID of the customer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer: Option<serde_json::Value>,
    /// ID of the account representing the customer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_account: Option<String>,
    /// Customer balance transaction related to this credit note.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_balance_transaction: Option<serde_json::Value>,
    /// The integer amount in cents (or local equivalent) representing the total amount of discount that was credited.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub discount_amount: Option<i64>,
    /// The aggregate amounts calculated per discount for all line items.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub discount_amounts: Option<Vec<DiscountsResourceDiscountAmount>>,
    /// The date when this credit note is in effect. Same as `created` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the credit note PDF.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effective_at: Option<i64>,
    /// Unique identifier for the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// ID of the invoice.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub invoice: Option<serde_json::Value>,
    /// Line items that make up the credit note
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lines: Option<serde_json::Value>,
    /// If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub livemode: Option<bool>,
    /// Customer-facing text that appears on the credit note PDF.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::BTreeMap<String, String>>,
    /// A unique number that identifies this particular credit note and appears on the PDF of the credit note and its associated invoice.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub number: Option<String>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// Amount that was credited outside of Stripe.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub out_of_band_amount: Option<i64>,
    /// The link to download the PDF of the credit note.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pdf: Option<String>,
    /// The amount of the credit note that was refunded to the customer, credited to the customer's balance, credited outside of Stripe, or any combination thereof.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub post_payment_amount: Option<i64>,
    /// The amount of the credit note by which the invoice's `amount_remaining` and `amount_due` were reduced.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pre_payment_amount: Option<i64>,
    /// The pretax credit amounts (ex: discount, credit grants, etc) for all line items.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pretax_credit_amounts: Option<Vec<CreditNotesPretaxCreditAmount>>,
    /// Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `order_change`, or `product_unsatisfactory`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Refunds related to this credit note.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refunds: Option<Vec<CreditNoteRefund>>,
    /// The details of the cost of shipping, including the ShippingRate applied to the invoice.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shipping_cost: Option<serde_json::Value>,
    /// Status of this credit note, one of `issued` or `void`. Learn more about \[voiding credit notes\](https://docs.stripe.com/billing/invoices/credit-notes#voiding).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// The integer amount in cents (or local equivalent) representing the amount of the credit note, excluding exclusive tax and invoice level discounts.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subtotal: Option<i64>,
    /// The integer amount in cents (or local equivalent) representing the amount of the credit note, excluding all tax and invoice level discounts.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subtotal_excluding_tax: Option<i64>,
    /// The integer amount in cents (or local equivalent) representing the total amount of the credit note, including tax and all discount.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
    /// The integer amount in cents (or local equivalent) representing the total amount of the credit note, excluding tax, but including discounts.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_excluding_tax: Option<i64>,
    /// The aggregate tax information for all line items.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_taxes: Option<Vec<BillingBillResourceInvoicingTaxesTax>>,
    /// Type of this credit note, one of `pre_payment` or `post_payment`. A `pre_payment` credit note means it was issued when the invoice was open. A `post_payment` credit note means it was issued when the invoice was paid.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub type_: Option<String>,
    /// The time that the credit note was voided.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub voided_at: Option<i64>,
}

/// The credit note line item object
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct CreditNoteLineItem {
    /// The integer amount in cents (or local equivalent) representing the gross amount being credited for this line item, excluding (exclusive) tax and discounts.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount: Option<i64>,
    /// Description of the item being credited.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The integer amount in cents (or local equivalent) representing the discount being credited for this line item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub discount_amount: Option<i64>,
    /// The amount of discount calculated per discount for this line item
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub discount_amounts: Option<Vec<DiscountsResourceDiscountAmount>>,
    /// Unique identifier for the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// ID of the invoice line item being credited
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub invoice_line_item: Option<String>,
    /// If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub livemode: Option<bool>,
    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::BTreeMap<String, String>>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// The pretax credit amounts (ex: discount, credit grants, etc) for this line item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pretax_credit_amounts: Option<Vec<CreditNotesPretaxCreditAmount>>,
    /// The number of units of product being credited.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quantity: Option<i64>,
    /// The tax rates which apply to the line item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tax_rates: Option<Vec<TaxRate>>,
    /// The tax information of the line item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub taxes: Option<Vec<BillingBillResourceInvoicingTaxesTax>>,
    /// The type of the credit note line item, one of `invoice_line_item` or `custom_line_item`. When the type is `invoice_line_item` there is an additional `invoice_line_item` property on the resource the value of which is the id of the credited…
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub type_: Option<String>,
    /// The cost of each unit of product being credited.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unit_amount: Option<i64>,
    /// Same as `unit_amount`, but contains a decimal value with at most 12 decimal places.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unit_amount_decimal: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct CreditNoteRefund {
    /// Amount of the refund that applies to this credit note, in cents (or local equivalent).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount_refunded: Option<i64>,
    /// The PaymentRecord refund details associated with this credit note refund.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_record_refund: Option<serde_json::Value>,
    /// ID of the refund.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refund: Option<serde_json::Value>,
    /// Type of the refund, one of `refund` or `payment_record_refund`.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub type_: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct CreditNotesPaymentRecordRefund {
    /// ID of the payment record.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_record: Option<String>,
    /// ID of the refund group.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refund_group: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct CreditNotesPretaxCreditAmount {
    /// The amount, in cents (or local equivalent), of the pretax credit amount.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount: Option<i64>,
    /// The credit balance transaction that was applied to get this pretax credit amount.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub credit_balance_transaction: Option<serde_json::Value>,
    /// The discount that was applied to get this pretax credit amount.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub discount: Option<serde_json::Value>,
    /// Type of the pretax credit amount referenced.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub type_: Option<String>,
}
