//! `disputes` API object models.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(missing_docs, clippy::doc_markdown, clippy::struct_excessive_bools, clippy::wildcard_imports, rustdoc::bare_urls)]

use serde::{Deserialize, Serialize};

// Models reference each other across modules; the parent re-exports every type.
#[allow(unused_imports)]
use super::*;

/// A dispute occurs when a customer questions your charge with their card issuer. When this happens, you have the opportunity to respond to the dispute with evidence that shows that the charge is legitimate. Related guide: \[Disputes and fraud\](https://docs.stripe.com/disputes)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Dispute {
    /// Disputed amount. Usually the amount of the charge, but it can differ (usually because of currency fluctuation or because only part of the order is disputed).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount: Option<i64>,
    /// List of zero, one, or two balance transactions that show funds withdrawn and reinstated to your Stripe account as a result of this dispute.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub balance_transactions: Option<Vec<BalanceTransaction>>,
    /// ID of the charge that's disputed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub charge: Option<serde_json::Value>,
    /// Time at which the object was created. Measured in seconds since the Unix epoch.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created: Option<i64>,
    /// Three-letter \[ISO currency code\](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a \[supported currency\](https://stripe.com/docs/currencies).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// List of eligibility types that are included in `enhanced_evidence`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enhanced_eligibility_types: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub evidence: Option<Box<DisputeEvidence>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub evidence_details: Option<Box<DisputeEvidenceDetails>>,
    /// Unique identifier for the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// If true, it's still possible to refund the disputed payment. After the payment has been fully refunded, no further funds are withdrawn from your Stripe account as a result of this dispute.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_charge_refundable: Option<bool>,
    /// If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub livemode: Option<bool>,
    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::BTreeMap<String, String>>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// ID of the PaymentIntent that's disputed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_intent: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_method_details: Option<Box<DisputePaymentMethodDetails>>,
    /// Reason given by cardholder for dispute. Possible values are `bank_cannot_process`, `check_returned`, `credit_not_processed`, `customer_initiated`, `debit_not_authorized`, `duplicate`, `fraudulent`, `general`, `incorrect_account_details`, `…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// The current status of a dispute. Possible values include:`warning_needs_response`, `warning_under_review`, `warning_closed`, `needs_response`, `under_review`, `won`, `lost`, or `prevented`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputeEnhancedEligibility {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mastercard_compliance: Option<Box<DisputeEnhancedEligibilityMastercardCompliance>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visa_compelling_evidence_3: Option<Box<DisputeEnhancedEligibilityVisaCompellingEvidence3>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visa_compliance: Option<Box<DisputeEnhancedEligibilityVisaCompliance>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputeEnhancedEligibilityMastercardCompliance {
    /// Mastercard compliance eligibility status.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputeEnhancedEligibilityVisaCompellingEvidence3 {
    /// List of actions required to qualify dispute for Visa Compelling Evidence 3.0 evidence submission.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub required_actions: Option<Vec<String>>,
    /// Visa Compelling Evidence 3.0 eligibility status.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputeEnhancedEligibilityVisaCompliance {
    /// Visa compliance eligibility status.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputeEnhancedEvidence {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mastercard_compliance: Option<Box<DisputeEnhancedEvidenceMastercardCompliance>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visa_compelling_evidence_3: Option<Box<DisputeEnhancedEvidenceVisaCompellingEvidence3>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visa_compliance: Option<Box<DisputeEnhancedEvidenceVisaCompliance>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputeEnhancedEvidenceMastercardCompliance {
    /// A field acknowledging the fee incurred when countering a Mastercard compliance dispute. If this field is set to true, evidence can be submitted for the compliance dispute.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fee_acknowledged: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputeEnhancedEvidenceVisaCompellingEvidence3 {
    /// Disputed transaction details for Visa Compelling Evidence 3.0 evidence submission.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disputed_transaction: Option<serde_json::Value>,
    /// List of exactly two prior undisputed transaction objects for Visa Compelling Evidence 3.0 evidence submission.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prior_undisputed_transactions: Option<Vec<DisputeVisaCompellingEvidence3PriorUndisputedTransaction>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputeEnhancedEvidenceVisaCompliance {
    /// A field acknowledging the fee incurred when countering a Visa compliance dispute. If this field is set to true, evidence can be submitted for the compliance dispute. Stripe collects a 500 USD (or local equivalent) amount to cover the netwo…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fee_acknowledged: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputeEvidence {
    /// Any server or activity logs showing proof that the customer accessed or downloaded the purchased digital product. This information should include IP addresses, corresponding timestamps, and any detailed recorded activity.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub access_activity_log: Option<String>,
    /// The billing address provided by the customer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub billing_address: Option<String>,
    /// (ID of a \[file upload\](https://stripe.com/docs/guides/file-upload)) Your subscription cancellation policy, as shown to the customer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancellation_policy: Option<serde_json::Value>,
    /// An explanation of how and when the customer was shown your refund policy prior to purchase.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancellation_policy_disclosure: Option<String>,
    /// A justification for why the customer's subscription was not canceled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancellation_rebuttal: Option<String>,
    /// (ID of a \[file upload\](https://stripe.com/docs/guides/file-upload)) Any communication with the customer that you feel is relevant to your case. Examples include emails proving that the customer received the product or service, or demonst…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_communication: Option<serde_json::Value>,
    /// The email address of the customer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_email_address: Option<String>,
    /// The name of the customer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_name: Option<String>,
    /// The IP address that the customer used when making the purchase.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_purchase_ip: Option<String>,
    /// (ID of a \[file upload\](https://stripe.com/docs/guides/file-upload)) A relevant document or contract showing the customer's signature.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_signature: Option<serde_json::Value>,
    /// (ID of a \[file upload\](https://stripe.com/docs/guides/file-upload)) Documentation for the prior charge that can uniquely identify the charge, such as a receipt, shipping label, work order, etc. This document should be paired with a simil…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duplicate_charge_documentation: Option<serde_json::Value>,
    /// An explanation of the difference between the disputed charge versus the prior charge that appears to be a duplicate.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duplicate_charge_explanation: Option<String>,
    /// The Stripe ID for the prior charge which appears to be a duplicate of the disputed charge.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duplicate_charge_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enhanced_evidence: Option<Box<DisputeEnhancedEvidence>>,
    /// A description of the product or service that was sold.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product_description: Option<String>,
    /// (ID of a \[file upload\](https://stripe.com/docs/guides/file-upload)) Any receipt or message sent to the customer notifying them of the charge.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub receipt: Option<serde_json::Value>,
    /// (ID of a \[file upload\](https://stripe.com/docs/guides/file-upload)) Your refund policy, as shown to the customer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refund_policy: Option<serde_json::Value>,
    /// Documentation demonstrating that the customer was shown your refund policy prior to purchase.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refund_policy_disclosure: Option<String>,
    /// A justification for why the customer is not entitled to a refund.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refund_refusal_explanation: Option<String>,
    /// The date on which the customer received or began receiving the purchased service, in a clear human-readable format.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_date: Option<String>,
    /// (ID of a \[file upload\](https://stripe.com/docs/guides/file-upload)) Documentation showing proof that a service was provided to the customer. This could include a copy of a signed contract, work order, or other form of written agreement.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_documentation: Option<serde_json::Value>,
    /// The address to which a physical product was shipped. You should try to include as complete address information as possible.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shipping_address: Option<String>,
    /// The delivery service that shipped a physical product, such as Fedex, UPS, USPS, etc. If multiple carriers were used for this purchase, please separate them with commas.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shipping_carrier: Option<String>,
    /// The date on which a physical product began its route to the shipping address, in a clear human-readable format.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shipping_date: Option<String>,
    /// (ID of a \[file upload\](https://stripe.com/docs/guides/file-upload)) Documentation showing proof that a product was shipped to the customer at the same address the customer provided to you. This could include a copy of the shipment receip…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shipping_documentation: Option<serde_json::Value>,
    /// The tracking number for a physical product, obtained from the delivery service. If multiple tracking numbers were generated for this purchase, please separate them with commas.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shipping_tracking_number: Option<String>,
    /// (ID of a \[file upload\](https://stripe.com/docs/guides/file-upload)) Any additional evidence or statements.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uncategorized_file: Option<serde_json::Value>,
    /// Any additional evidence or statements.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uncategorized_text: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputeEvidenceDetails {
    /// Date by which evidence must be submitted in order to successfully challenge dispute. Will be 0 if the customer's bank or credit card company doesn't allow a response for this particular dispute.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub due_by: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enhanced_eligibility: Option<Box<DisputeEnhancedEligibility>>,
    /// Whether evidence has been staged for this dispute.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub has_evidence: Option<bool>,
    /// Whether the last evidence submission was submitted past the due date. Defaults to `false` if no evidence submissions have occurred. If `true`, then delivery of the latest evidence is *not* guaranteed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub past_due: Option<bool>,
    /// The number of times evidence has been submitted. Typically, you may only submit evidence once.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub submission_count: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputePaymentMethodDetails {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amazon_pay: Option<Box<DisputePaymentMethodDetailsAmazonPay>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub card: Option<Box<DisputePaymentMethodDetailsCard>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub klarna: Option<Box<DisputePaymentMethodDetailsKlarna>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub paypal: Option<Box<DisputePaymentMethodDetailsPaypal>>,
    /// Payment method type.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub type_: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputePaymentMethodDetailsAmazonPay {
    /// The AmazonPay dispute type, chargeback or claim
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dispute_type: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputePaymentMethodDetailsCard {
    /// Card brand. Can be `amex`, `cartes_bancaires`, `diners`, `discover`, `eftpos_au`, `jcb`, `link`, `mastercard`, `unionpay`, `visa` or `unknown`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub brand: Option<String>,
    /// The type of dispute opened. Different case types may have varying fees and financial impact.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub case_type: Option<String>,
    /// The card network's specific dispute reason code, which maps to one of Stripe's primary dispute categories to simplify response guidance. The \[Network code map\](https://stripe.com/docs/disputes/categories#network-code-map) lists all avail…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub network_reason_code: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputePaymentMethodDetailsKlarna {
    /// Chargeback loss reason mapped by Stripe from Klarna's chargeback loss reason
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub chargeback_loss_reason_code: Option<String>,
    /// The reason for the dispute as defined by Klarna
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason_code: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputePaymentMethodDetailsPaypal {
    /// The ID of the dispute in PayPal.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub case_id: Option<String>,
    /// The reason for the dispute as defined by PayPal
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason_code: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputeTransactionShippingAddress {
    /// City, district, suburb, town, or village.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// Two-letter country code (\[ISO 3166-1 alpha-2\](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Address line 1, such as the street, PO Box, or company name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub line1: Option<String>,
    /// Address line 2, such as the apartment, suite, unit, or building.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub line2: Option<String>,
    /// ZIP or postal code.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<String>,
    /// State, county, province, or region (\[ISO 3166-2\](https://en.wikipedia.org/wiki/ISO_3166-2)).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputeVisaCompellingEvidence3DisputedTransaction {
    /// User Account ID used to log into business platform. Must be recognizable by the user.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_account_id: Option<String>,
    /// Unique identifier of the cardholder’s device derived from a combination of at least two hardware and software attributes. Must be at least 20 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_device_fingerprint: Option<String>,
    /// Unique identifier of the cardholder’s device such as a device serial number (e.g., International Mobile Equipment Identity \[IMEI\]). Must be at least 15 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_device_id: Option<String>,
    /// The email address of the customer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_email_address: Option<String>,
    /// The IP address that the customer used when making the purchase.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_purchase_ip: Option<String>,
    /// Categorization of disputed payment.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub merchandise_or_services: Option<String>,
    /// A description of the product or service that was sold.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product_description: Option<String>,
    /// The address to which a physical product was shipped. All fields are required for Visa Compelling Evidence 3.0 evidence submission.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shipping_address: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DisputeVisaCompellingEvidence3PriorUndisputedTransaction {
    /// Stripe charge ID for the Visa Compelling Evidence 3.0 eligible prior charge.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub charge: Option<String>,
    /// User Account ID used to log into business platform. Must be recognizable by the user.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_account_id: Option<String>,
    /// Unique identifier of the cardholder’s device derived from a combination of at least two hardware and software attributes. Must be at least 20 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_device_fingerprint: Option<String>,
    /// Unique identifier of the cardholder’s device such as a device serial number (e.g., International Mobile Equipment Identity \[IMEI\]). Must be at least 15 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_device_id: Option<String>,
    /// The email address of the customer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_email_address: Option<String>,
    /// The IP address that the customer used when making the purchase.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_purchase_ip: Option<String>,
    /// A description of the product or service that was sold.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product_description: Option<String>,
    /// The address to which a physical product was shipped. All fields are required for Visa Compelling Evidence 3.0 evidence submission.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shipping_address: Option<serde_json::Value>,
}
