//! `setup_attempts` API object models.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(missing_docs, clippy::doc_markdown, clippy::struct_excessive_bools, clippy::wildcard_imports, rustdoc::bare_urls)]

use serde::{Deserialize, Serialize};

// Models reference each other across modules; the parent re-exports every type.
#[allow(unused_imports)]
use super::*;

/// A SetupAttempt describes one attempted confirmation of a SetupIntent, whether that confirmation is successful or unsuccessful. You can use SetupAttempts to inspect details of a specific attempt at setting up a payment method using a SetupIntent.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttempt {
    /// The value of \[application\](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-application) on the SetupIntent at the time of this confirmation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub application: Option<serde_json::Value>,
    /// If present, the SetupIntent's payment method will be attached to the in-context Stripe Account. It can only be used for this Stripe Account’s own money movement flows like InboundTransfer and OutboundTransfers. It cannot be set to true whe…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attach_to_self: Option<bool>,
    /// Time at which the object was created. Measured in seconds since the Unix epoch.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created: Option<i64>,
    /// The value of \[customer\](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-customer) on the SetupIntent at the time of this confirmation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer: Option<serde_json::Value>,
    /// The value of \[customer_account\](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-customer_account) on the SetupIntent at the time of this confirmation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_account: Option<String>,
    /// Indicates the directions of money movement for which this payment method is intended to be used. Include `inbound` if you intend to use the payment method as the origin to pull funds from. Include `outbound` if you intend to use the paymen…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub flow_directions: Option<Vec<String>>,
    /// Unique identifier for the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub livemode: Option<bool>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// The value of \[on_behalf_of\](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-on_behalf_of) on the SetupIntent at the time of this confirmation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_behalf_of: Option<serde_json::Value>,
    /// ID of the payment method used with this SetupAttempt.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_method_details: Option<Box<SetupAttemptPaymentMethodDetails>>,
    /// The error encountered during this attempt to confirm the SetupIntent, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub setup_error: Option<serde_json::Value>,
    /// ID of the SetupIntent that this attempt belongs to.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub setup_intent: Option<serde_json::Value>,
    /// Status of this SetupAttempt, one of `requires_confirmation`, `requires_action`, `processing`, `succeeded`, `failed`, or `abandoned`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// The value of \[usage\](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-usage) on the SetupIntent at the time of this confirmation, one of `off_session` or `on_session`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetails {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub acss_debit: Option<Box<SetupAttemptPaymentMethodDetailsAcssDebit>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amazon_pay: Option<Box<SetupAttemptPaymentMethodDetailsAmazonPay>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub au_becs_debit: Option<Box<SetupAttemptPaymentMethodDetailsAuBecsDebit>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bacs_debit: Option<Box<SetupAttemptPaymentMethodDetailsBacsDebit>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bancontact: Option<Box<SetupAttemptPaymentMethodDetailsBancontact>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub boleto: Option<Box<SetupAttemptPaymentMethodDetailsBoleto>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub card: Option<Box<SetupAttemptPaymentMethodDetailsCard>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub card_present: Option<Box<SetupAttemptPaymentMethodDetailsCardPresent>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cashapp: Option<Box<SetupAttemptPaymentMethodDetailsCashapp>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ideal: Option<Box<SetupAttemptPaymentMethodDetailsIdeal>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kakao_pay: Option<Box<SetupAttemptPaymentMethodDetailsKakaoPay>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub klarna: Option<Box<SetupAttemptPaymentMethodDetailsKlarna>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kr_card: Option<Box<SetupAttemptPaymentMethodDetailsKrCard>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub link: Option<Box<SetupAttemptPaymentMethodDetailsLink>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub naver_pay: Option<Box<SetupAttemptPaymentMethodDetailsNaverPay>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nz_bank_account: Option<Box<SetupAttemptPaymentMethodDetailsNzBankAccount>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub paypal: Option<Box<SetupAttemptPaymentMethodDetailsPaypal>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payto: Option<Box<SetupAttemptPaymentMethodDetailsPayto>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pix: Option<Box<SetupAttemptPaymentMethodDetailsPix>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revolut_pay: Option<Box<SetupAttemptPaymentMethodDetailsRevolutPay>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub satispay: Option<Box<PaymentFlowsPrivatePaymentMethodsSatispaySetupAttemptDetails>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sepa_debit: Option<Box<SetupAttemptPaymentMethodDetailsSepaDebit>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sofort: Option<Box<SetupAttemptPaymentMethodDetailsSofort>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub twint: Option<Box<SetupAttemptPaymentMethodDetailsTwint>>,
    /// The type of the payment method used in the SetupIntent (e.g., `card`). An additional hash is included on `payment_method_details` with a name matching this value. It contains confirmation-specific information for the payment method.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub type_: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upi: Option<Box<SetupAttemptPaymentMethodDetailsUpi>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub us_bank_account: Option<Box<SetupAttemptPaymentMethodDetailsUsBankAccount>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsAcssDebit {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsAmazonPay {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsAuBecsDebit {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsBacsDebit {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsBancontact {
    /// Bank code of bank associated with the bank account.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bank_code: Option<String>,
    /// Name of the bank associated with the bank account.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bank_name: Option<String>,
    /// Bank Identifier Code of the bank associated with the bank account.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bic: Option<String>,
    /// The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_sepa_debit: Option<serde_json::Value>,
    /// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_sepa_debit_mandate: Option<serde_json::Value>,
    /// Last four characters of the IBAN.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iban_last4: Option<String>,
    /// Preferred language of the Bancontact authorization page that the customer is redirected to. Can be one of `en`, `de`, `fr`, or `nl`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preferred_language: Option<String>,
    /// Owner's verified full name. Values are verified or provided by Bancontact directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verified_name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsBoleto {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsCard {
    /// Card brand. Can be `amex`, `cartes_bancaires`, `diners`, `discover`, `eftpos_au`, `jcb`, `link`, `mastercard`, `unionpay`, `visa` or `unknown`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub brand: Option<String>,
    /// Check results by Card networks on Card address and CVC at the time of authorization
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub checks: Option<serde_json::Value>,
    /// Two-letter ISO code representing the country of the card. You could use this attribute to get a sense of the international breakdown of cards you've collected.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Two-digit number representing the card's expiration month.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exp_month: Option<i64>,
    /// Four-digit number representing the card's expiration year.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exp_year: Option<i64>,
    /// Uniquely identifies this particular card number. You can use this attribute to check whether two customers who’ve signed up with you are using the same card number, for example. For payment methods that tokenize card information (Apple Pay…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fingerprint: Option<String>,
    /// Card funding type. Can be `credit`, `debit`, `prepaid`, or `unknown`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub funding: Option<String>,
    /// The last four digits of the card.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last4: Option<String>,
    /// Identifies which network this charge was processed on. Can be `amex`, `cartes_bancaires`, `diners`, `discover`, `eftpos_au`, `interac`, `jcb`, `link`, `mastercard`, `unionpay`, `visa`, or `unknown`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub network: Option<String>,
    /// Populated if this authorization used 3D Secure authentication.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub three_d_secure: Option<serde_json::Value>,
    /// If this Card is part of a card wallet, this contains the details of the card wallet.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wallet: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsCardChecks {
    /// If a address line1 was provided, results of the check, one of `pass`, `fail`, `unavailable`, or `unchecked`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address_line1_check: Option<String>,
    /// If a address postal code was provided, results of the check, one of `pass`, `fail`, `unavailable`, or `unchecked`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address_postal_code_check: Option<String>,
    /// If a CVC was provided, results of the check, one of `pass`, `fail`, `unavailable`, or `unchecked`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cvc_check: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsCardPresent {
    /// The ID of the Card PaymentMethod which was generated by this SetupAttempt.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_card: Option<serde_json::Value>,
    /// Details about payments collected offline.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offline: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsCardWallet {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub apple_pay: Option<Box<PaymentMethodDetailsCardWalletApplePay>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub google_pay: Option<Box<PaymentMethodDetailsCardWalletGooglePay>>,
    /// The type of the card wallet, one of `apple_pay`, `google_pay`, or `link`. An additional hash is included on the Wallet subhash with a name matching this value. It contains additional information specific to the card wallet type.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub type_: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsCashapp {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsIdeal {
    /// The customer's bank. Can be one of `abn_amro`, `adyen`, `asn_bank`, `bunq`, `buut`, `finom`, `handelsbanken`, `ing`, `knab`, `mollie`, `moneyou`, `n26`, `nn`, `rabobank`, `regiobank`, `revolut`, `sns_bank`, `triodos_bank`, `van_lanschot`,…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bank: Option<String>,
    /// The Bank Identifier Code of the customer's bank.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bic: Option<String>,
    /// The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_sepa_debit: Option<serde_json::Value>,
    /// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_sepa_debit_mandate: Option<serde_json::Value>,
    /// Last four characters of the IBAN.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iban_last4: Option<String>,
    /// Owner's verified full name. Values are verified or provided by iDEAL directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verified_name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsKakaoPay {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsKlarna {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsKrCard {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsLink {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsNaverPay {
    /// Uniquely identifies this particular Naver Pay account. You can use this attribute to check whether two Naver Pay accounts are the same.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyer_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsNzBankAccount {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsPaypal {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsPayto {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsPix {
    /// Uniquely identifies this particular Pix account. You can use this attribute to check whether two Pix accounts are the same.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fingerprint: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsRevolutPay {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsSepaDebit {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsSofort {
    /// Bank code of bank associated with the bank account.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bank_code: Option<String>,
    /// Name of the bank associated with the bank account.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bank_name: Option<String>,
    /// Bank Identifier Code of the bank associated with the bank account.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bic: Option<String>,
    /// The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_sepa_debit: Option<serde_json::Value>,
    /// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_sepa_debit_mandate: Option<serde_json::Value>,
    /// Last four characters of the IBAN.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iban_last4: Option<String>,
    /// Preferred language of the Sofort authorization page that the customer is redirected to. Can be one of `en`, `de`, `fr`, or `nl`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preferred_language: Option<String>,
    /// Owner's verified full name. Values are verified or provided by Sofort directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verified_name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsTwint {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsUpi {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SetupAttemptPaymentMethodDetailsUsBankAccount {
}
