//! `tax_rates` API object models.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(missing_docs, clippy::doc_markdown, clippy::struct_excessive_bools, clippy::wildcard_imports, rustdoc::bare_urls)]

use serde::{Deserialize, Serialize};

// Models reference each other across modules; the parent re-exports every type.
#[allow(unused_imports)]
use super::*;

/// Tax rates can be applied to \[invoices\](/invoicing/taxes/tax-rates), \[subscriptions\](/billing/taxes/tax-rates) and \[Checkout Sessions\](/payments/checkout/use-manual-tax-rates) to collect tax. Related guide: \[Tax rates\](/billing/taxes/tax-rates)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TaxRate {
    /// Defaults to `true`. When set to `false`, this tax rate cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// Two-letter country code (\[ISO 3166-1 alpha-2\](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Time at which the object was created. Measured in seconds since the Unix epoch.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created: Option<i64>,
    /// An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The display name of the tax rates as it will appear to your customer on their receipt email, PDF, and the hosted invoice page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Actual/effective tax rate percentage out of 100. For tax calculations with automatic_tax\[enabled\]=true, this percentage reflects the rate actually used to calculate tax based on the product's taxability and whether the user is registered…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effective_percentage: Option<f64>,
    /// The amount of the tax rate when the `rate_type` is `flat_amount`. Tax rates with `rate_type` `percentage` can vary based on the transaction, resulting in this field being `null`. This field exposes the amount and currency of the flat tax r…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub flat_amount: Option<serde_json::Value>,
    /// Unique identifier for the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// This specifies if the tax rate is inclusive or exclusive.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inclusive: Option<bool>,
    /// The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub jurisdiction: Option<String>,
    /// The level of the jurisdiction that imposes this tax rate. Will be `null` for manually defined tax rates.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub jurisdiction_level: Option<String>,
    /// If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub livemode: Option<bool>,
    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::BTreeMap<String, String>>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// Tax rate percentage out of 100. For tax calculations with automatic_tax\[enabled\]=true, this percentage includes the statutory tax rate of non-taxable jurisdictions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub percentage: Option<f64>,
    /// Indicates the type of tax rate applied to the taxable amount. This value can be `null` when no tax applies to the location. This field is only present for TaxRates created by Stripe Tax.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rate_type: Option<String>,
    /// \[ISO 3166-2 subdivision code\](https://en.wikipedia.org/wiki/ISO_3166-2), without country prefix. For example, "NY" for New York, United States.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    /// The high-level tax type, such as `vat` or `sales_tax`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tax_type: Option<String>,
}

/// The amount of the tax rate when the `rate_type`` is `flat_amount`. Tax rates with `rate_type` `percentage` can vary based on the transaction, resulting in this field being `null`. This field exposes the amount and currency of the flat tax rate.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TaxRateFlatAmount {
    /// Amount of the tax when the `rate_type` is `flat_amount`. This positive integer represents how much to charge in the smallest currency unit (e.g., 100 cents to charge $1.00 or 100 to charge ¥100, a zero-decimal currency). The amount value s…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount: Option<i64>,
    /// Three-letter ISO currency code, in lowercase.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
}
