//! `tax_ids` API object models.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(missing_docs, clippy::doc_markdown, clippy::struct_excessive_bools, clippy::wildcard_imports, rustdoc::bare_urls)]

use serde::{Deserialize, Serialize};

// Models reference each other across modules; the parent re-exports every type.
#[allow(unused_imports)]
use super::*;

/// You can add one or multiple tax IDs to a \[customer\](https://docs.stripe.com/api/customers) or account. Customer and account tax IDs get displayed on related invoices and credit notes. Related guides: \[Customer tax identification numbers\](https://docs.stripe.com/billing/taxes/tax-ids), \[Account tax IDs\](https://docs.stripe.com/invoicing/connect#account-tax-ids)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TaxId {
    /// Two-letter ISO code representing the country of the tax ID.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Time at which the object was created. Measured in seconds since the Unix epoch.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created: Option<i64>,
    /// ID of the customer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer: Option<serde_json::Value>,
    /// ID of the Account representing the customer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_account: Option<String>,
    /// Unique identifier for the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub livemode: Option<bool>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// The account or customer the tax ID belongs to.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub owner: Option<serde_json::Value>,
    /// Type of the tax ID, one of `ad_nrt`, `ae_trn`, `al_tin`, `am_tin`, `ao_tin`, `ar_cuit`, `au_abn`, `au_arn`, `aw_tin`, `az_tin`, `ba_tin`, `bb_tin`, `bd_bin`, `bf_ifu`, `bg_uic`, `bh_vat`, `bj_ifu`, `bo_tin`, `br_cnpj`, `br_cpf`, `bs_tin`,…
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub type_: Option<String>,
    /// Value of the tax ID.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// Tax ID verification information.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verification: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TaxIdVerification {
    /// Verification status, one of `pending`, `verified`, `unverified`, or `unavailable`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Verified address.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verified_address: Option<String>,
    /// Verified name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verified_name: Option<String>,
}
