//! `terminal` API object models.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(missing_docs, clippy::doc_markdown, clippy::struct_excessive_bools, clippy::wildcard_imports, rustdoc::bare_urls)]

use serde::{Deserialize, Serialize};

// Models reference each other across modules; the parent re-exports every type.
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DeletedTerminalConfiguration {
    /// Always true for a deleted object
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    /// Unique identifier for the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DeletedTerminalLocation {
    /// Always true for a deleted object
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    /// Unique identifier for the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DeletedTerminalReader {
    /// Always true for a deleted object
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    /// Device type of the reader.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_type: Option<String>,
    /// Unique identifier for the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// Serial number of the reader.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub serial_number: Option<String>,
}

/// A Configurations object represents how features should be configured for terminal readers. For information about how to use it, see the \[Terminal configurations documentation\](https://docs.stripe.com/terminal/fleet/configurations-overview).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalConfiguration {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bbpos_wisepad3: Option<Box<TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bbpos_wisepos_e: Option<Box<TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cellular: Option<Box<TerminalConfigurationConfigurationResourceCellularConfig>>,
    /// Unique identifier for the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Whether this Configuration is the default for your account
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_account_default: Option<bool>,
    /// If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub livemode: Option<bool>,
    /// String indicating the name of the Configuration object, set by the user
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offline: Option<Box<TerminalConfigurationConfigurationResourceOfflineConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reboot_window: Option<Box<TerminalConfigurationConfigurationResourceRebootWindow>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stripe_s700: Option<Box<TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stripe_s710: Option<Box<TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tipping: Option<Box<TerminalConfigurationConfigurationResourceTipping>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verifone_m425: Option<Box<TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verifone_p400: Option<Box<TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verifone_p630: Option<Box<TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verifone_ux700: Option<Box<TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verifone_v660p: Option<Box<TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wifi: Option<Box<TerminalConfigurationConfigurationResourceWifiConfig>>,
}

/// A Connection Token is used by the Stripe Terminal SDK to connect to a reader. Related guide: \[Fleet management\](https://docs.stripe.com/terminal/fleet/locations)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalConnectionToken {
    /// The id of the location that this connection token is scoped to. Note that location scoping only applies to internet-connected readers. For more details, see \[the docs on scoping connection tokens\](https://docs.stripe.com/terminal/fleet/l…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// Your application should pass this token to the Stripe Terminal SDK.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
}

/// A Location represents a grouping of readers. Related guide: \[Fleet management\](https://docs.stripe.com/terminal/fleet/locations)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalLocation {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<Address>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address_kana: Option<Box<LegalEntityJapanAddress>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address_kanji: Option<Box<LegalEntityJapanAddress>>,
    /// The ID of a configuration that will be used to customize all readers in this location.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub configuration_overrides: Option<String>,
    /// The display name of the location.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// The Kana variation of the display name of the location.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name_kana: Option<String>,
    /// The Kanji variation of the display name of the location.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name_kanji: Option<String>,
    /// Unique identifier for the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub livemode: Option<bool>,
    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::BTreeMap<String, String>>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// The phone number of the location.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
}

/// Returns redirect links used for onboarding onto Tap to Pay on iPhone.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalOnboardingLink {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub link_options: Option<Box<TerminalOnboardingLinkLinkOptions>>,
    /// The type of link being generated.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub link_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// Stripe account ID to generate the link for.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_behalf_of: Option<String>,
    /// The link passed back to the user for their onboarding.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub redirect_url: Option<String>,
}

/// A Reader represents a physical device for accepting payment details. Related guide: \[Connecting to a reader\](https://docs.stripe.com/terminal/payments/connect-reader)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReader {
    /// The most recent action performed by the reader.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action: Option<serde_json::Value>,
    /// The current software version of the reader.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_sw_version: Option<String>,
    /// Device type of the reader.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_type: Option<String>,
    /// Unique identifier for the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The local IP address of the reader.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    /// Custom label given to the reader for easier identification.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// The last time this reader reported to Stripe backend. Timestamp is measured in milliseconds since the Unix epoch. Unlike most other Stripe timestamp fields which use seconds, this field uses milliseconds.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_seen_at: Option<i64>,
    /// If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub livemode: Option<bool>,
    /// The location identifier of the reader.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<serde_json::Value>,
    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::BTreeMap<String, String>>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// Serial number of the reader.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub serial_number: Option<String>,
    /// The networking status of the reader. We do not recommend using this field in flows that may block taking payments.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

/// A Refund object returned by the Terminal refunds API.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalRefund {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalConfigurationConfigurationResourceCellularConfig {
    /// Whether a cellular-capable reader can connect to the internet over cellular.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalConfigurationConfigurationResourceCurrencySpecificConfig {
    /// Fixed amounts displayed when collecting a tip
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fixed_amounts: Option<Vec<i64>>,
    /// Percentages displayed when collecting a tip
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub percentages: Option<Vec<i64>>,
    /// Below this amount, fixed amounts will be displayed; above it, percentages will be displayed
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub smart_tip_threshold: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig {
    /// A File ID representing an image to display on the reader
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub splashscreen: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalConfigurationConfigurationResourceEnterprisePeapWifi {
    /// A File ID representing a PEM file containing the server certificate
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ca_certificate_file: Option<String>,
    /// Password for connecting to the WiFi network
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// Name of the WiFi network
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ssid: Option<String>,
    /// Username for connecting to the WiFi network
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalConfigurationConfigurationResourceEnterpriseTlsWifi {
    /// A File ID representing a PEM file containing the server certificate
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ca_certificate_file: Option<String>,
    /// A File ID representing a PEM file containing the client certificate
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub client_certificate_file: Option<String>,
    /// A File ID representing a PEM file containing the client RSA private key
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub private_key_file: Option<String>,
    /// Password for the private key file
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub private_key_file_password: Option<String>,
    /// Name of the WiFi network
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ssid: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalConfigurationConfigurationResourceOfflineConfig {
    /// Determines whether to allow transactions to be collected while reader is offline. Defaults to false.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalConfigurationConfigurationResourcePersonalPskWifi {
    /// Password for connecting to the WiFi network
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// Name of the WiFi network
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ssid: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalConfigurationConfigurationResourceRebootWindow {
    /// Integer between 0 to 23 that represents the end hour of the reboot time window. The value must be different than the start_hour.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_hour: Option<i64>,
    /// Integer between 0 to 23 that represents the start hour of the reboot time window.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start_hour: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalConfigurationConfigurationResourceTipping {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aed: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aud: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cad: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub chf: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub czk: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dkk: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub eur: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gbp: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gip: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hkd: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub huf: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub jpy: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mxn: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub myr: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nok: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nzd: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pln: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ron: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sek: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sgd: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usd: Option<Box<TerminalConfigurationConfigurationResourceCurrencySpecificConfig>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalConfigurationConfigurationResourceWifiConfig {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enterprise_eap_peap: Option<Box<TerminalConfigurationConfigurationResourceEnterprisePeapWifi>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enterprise_eap_tls: Option<Box<TerminalConfigurationConfigurationResourceEnterpriseTlsWifi>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub personal_psk: Option<Box<TerminalConfigurationConfigurationResourcePersonalPskWifi>>,
    /// Security type of the WiFi network. The hash with the corresponding name contains the credentials for this security type.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub type_: Option<String>,
}

/// Options associated with the Apple Terms and Conditions link type.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalOnboardingLinkAppleTermsAndConditions {
    /// Whether the link should also support users relinking their Apple account.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allow_relinking: Option<bool>,
    /// The business name of the merchant accepting Apple's Terms and Conditions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub merchant_display_name: Option<String>,
}

/// Link type options associated with the current onboarding link object.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalOnboardingLinkLinkOptions {
    /// The options associated with the Apple Terms and Conditions link type.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub apple_terms_and_conditions: Option<serde_json::Value>,
}

/// Represents a cart to be displayed on the reader
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceCart {
    /// Three-letter \[ISO currency code\](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a \[supported currency\](https://stripe.com/docs/currencies).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// List of line items in the cart.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub line_items: Option<Vec<TerminalReaderReaderResourceLineItem>>,
    /// Tax amount for the entire cart. A positive integer in the \[smallest currency unit\](https://docs.stripe.com/currencies#zero-decimal).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tax: Option<i64>,
    /// Total amount for the entire cart, including tax. A positive integer in the \[smallest currency unit\](https://docs.stripe.com/currencies#zero-decimal).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
}

/// Choice to be selected on a Reader
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceChoice {
    /// The identifier for the selected choice. Maximum 50 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The button style for the choice. Can be `primary` or `secondary`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
    /// The text to be selected. Maximum 30 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
}

/// Represents a per-transaction override of a reader configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceCollectConfig {
    /// Enable customer-initiated cancellation when processing this payment.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enable_customer_cancellation: Option<bool>,
    /// Override showing a tipping selection screen on this transaction.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub skip_tipping: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tipping: Option<Box<TerminalReaderReaderResourceTippingConfig>>,
}

/// Represents a reader action to collect customer inputs
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceCollectInputsAction {
    /// List of inputs to be collected.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inputs: Option<Vec<TerminalReaderReaderResourceInput>>,
    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::BTreeMap<String, String>>,
}

/// Represents a reader action to collect a payment method
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceCollectPaymentMethodAction {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub collect_config: Option<Box<TerminalReaderReaderResourceCollectConfig>>,
    /// Most recent PaymentIntent processed by the reader.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_intent: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<Box<PaymentMethod>>,
}

/// Represents a per-transaction override of a reader configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceConfirmConfig {
    /// If the customer doesn't abandon authenticating the payment, they're redirected to this URL after completion.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub return_url: Option<String>,
}

/// Represents a reader action to confirm a payment
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceConfirmPaymentIntentAction {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confirm_config: Option<Box<TerminalReaderReaderResourceConfirmConfig>>,
    /// Most recent PaymentIntent processed by the reader.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_intent: Option<serde_json::Value>,
}

/// Represents custom text to be displayed when collecting the input using a reader
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceCustomText {
    /// Customize the default description for this input
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Customize the default label for this input's skip button
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub skip_button: Option<String>,
    /// Customize the default label for this input's submit button
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub submit_button: Option<String>,
    /// Customize the default title for this input
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

/// Information about a email being collected using a reader
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceEmail {
    /// The collected email address
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

/// Metadata of an uploaded file
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceFileMetadata {
    /// Creation time of the object (in seconds since the Unix epoch).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// The original name of the uploaded file (e.g. `receipt.png`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    /// The size (in bytes) of the uploaded file.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
    /// The format of the uploaded file.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub type_: Option<String>,
}

/// Represents an input to be collected using the reader
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceInput {
    /// Default text of input being collected.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub custom_text: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<Box<TerminalReaderReaderResourceEmail>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub numeric: Option<Box<TerminalReaderReaderResourceNumeric>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<Box<TerminalReaderReaderResourcePhone>>,
    /// Indicate that this input is required, disabling the skip button.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub selection: Option<Box<TerminalReaderReaderResourceSelection>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signature: Option<Box<TerminalReaderReaderResourceSignature>>,
    /// Indicate that this input was skipped by the user.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub skipped: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<Box<TerminalReaderReaderResourceText>>,
    /// List of toggles being collected. Values are present if collection is complete.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub toggles: Option<Vec<TerminalReaderReaderResourceToggle>>,
    /// Type of input being collected.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub type_: Option<String>,
}

/// Represents a line item to be displayed on the reader
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceLineItem {
    /// The amount of the line item. A positive integer in the \[smallest currency unit\](https://docs.stripe.com/currencies#zero-decimal).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount: Option<i64>,
    /// Description of the line item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The quantity of the line item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quantity: Option<i64>,
}

/// Information about a number being collected using a reader
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceNumeric {
    /// The collected number
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

/// Information about a phone number being collected using a reader
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourcePhone {
    /// The collected phone number
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

/// Represents a reader action to print content
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourcePrintContent {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<Box<TerminalReaderReaderResourceFileMetadata>>,
    /// The type of content to print. Currently supports `image`.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub type_: Option<String>,
}

/// Represents a per-transaction override of a reader configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceProcessConfig {
    /// Enable customer-initiated cancellation when processing this payment.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enable_customer_cancellation: Option<bool>,
    /// If the customer doesn't abandon authenticating the payment, they're redirected to this URL after completion.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub return_url: Option<String>,
    /// Override showing a tipping selection screen on this transaction.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub skip_tipping: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tipping: Option<Box<TerminalReaderReaderResourceTippingConfig>>,
}

/// Represents a reader action to process a payment intent
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceProcessPaymentIntentAction {
    /// Most recent PaymentIntent processed by the reader.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_intent: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub process_config: Option<Box<TerminalReaderReaderResourceProcessConfig>>,
}

/// Represents a per-setup override of a reader configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceProcessSetupConfig {
    /// Enable customer-initiated cancellation when processing this SetupIntent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enable_customer_cancellation: Option<bool>,
}

/// Represents a reader action to process a setup intent
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceProcessSetupIntentAction {
    /// ID of a card PaymentMethod generated from the card_present PaymentMethod that may be attached to a Customer for future transactions. Only present if it was possible to generate a card PaymentMethod.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_card: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub process_config: Option<Box<TerminalReaderReaderResourceProcessSetupConfig>>,
    /// Most recent SetupIntent processed by the reader.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub setup_intent: Option<serde_json::Value>,
}

/// Represents an action performed by the reader
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceReaderAction {
    /// The reader action failed due to an \[API error\](https://docs.stripe.com/api/errors). Only present when `status` is `failed` and the underlying failure was an API error. Avoid parsing the `message` field for programmatic logic; use `type`…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_error: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub collect_inputs: Option<Box<TerminalReaderReaderResourceCollectInputsAction>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub collect_payment_method: Option<Box<TerminalReaderReaderResourceCollectPaymentMethodAction>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confirm_payment_intent: Option<Box<TerminalReaderReaderResourceConfirmPaymentIntentAction>>,
    /// Failure code, only set if status is `failed`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
    /// Detailed failure message, only set if status is `failed`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub print_content: Option<Box<TerminalReaderReaderResourcePrintContent>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub process_payment_intent: Option<Box<TerminalReaderReaderResourceProcessPaymentIntentAction>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub process_setup_intent: Option<Box<TerminalReaderReaderResourceProcessSetupIntentAction>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refund_payment: Option<Box<TerminalReaderReaderResourceRefundPaymentAction>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub set_reader_display: Option<Box<TerminalReaderReaderResourceSetReaderDisplayAction>>,
    /// Status of the action performed by the reader.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Type of action performed by the reader.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub type_: Option<String>,
}

/// Represents a reader action to refund a payment
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceRefundPaymentAction {
    /// The amount being refunded.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount: Option<i64>,
    /// Charge that is being refunded.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub charge: Option<serde_json::Value>,
    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::BTreeMap<String, String>>,
    /// Payment intent that is being refunded.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_intent: Option<serde_json::Value>,
    /// The reason for the refund.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Unique identifier for the refund object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refund: Option<serde_json::Value>,
    /// Boolean indicating whether the application fee should be refunded when refunding this charge. If a full charge refund is given, the full application fee will be refunded. Otherwise, the application fee will be refunded in an amount proport…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refund_application_fee: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refund_payment_config: Option<Box<TerminalReaderReaderResourceRefundPaymentConfig>>,
    /// Boolean indicating whether the transfer should be reversed when refunding this charge. The transfer will be reversed proportionally to the amount being refunded (either the entire or partial amount). A transfer can be reversed only by the…
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reverse_transfer: Option<bool>,
}

/// Represents a per-transaction override of a reader configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceRefundPaymentConfig {
    /// Enable customer-initiated cancellation when refunding this payment.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enable_customer_cancellation: Option<bool>,
}

/// Information about a selection being collected using a reader
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceSelection {
    /// List of possible choices to be selected
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub choices: Option<Vec<TerminalReaderReaderResourceChoice>>,
    /// The id of the selected choice
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The text of the selected choice
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
}

/// Represents a reader action to set the reader display
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceSetReaderDisplayAction {
    /// Cart object to be displayed by the reader, including line items, amounts, and currency.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cart: Option<serde_json::Value>,
    /// Type of information to be displayed by the reader. Only `cart` is currently supported.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub type_: Option<String>,
}

/// Information about a signature being collected using a reader
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceSignature {
    /// The File ID of a collected signature image
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

/// Information about text being collected using a reader
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceText {
    /// The collected text value
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

/// Represents a per-transaction tipping configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceTippingConfig {
    /// Amount used to calculate tip suggestions on tipping selection screen for this transaction. Must be a positive integer in the smallest currency unit (e.g., 100 cents to represent $1.00 or 100 to represent ¥100, a zero-decimal currency).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount_eligible: Option<i64>,
}

/// Information about an input's toggle
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TerminalReaderReaderResourceToggle {
    /// The toggle's default value. Can be `enabled` or `disabled`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default_value: Option<String>,
    /// The toggle's description text. Maximum 50 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The toggle's title text. Maximum 50 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The toggle's collected value. Can be `enabled` or `disabled`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}
