//! Generated operations for the `account_sessions` section of the Stripe v1 API.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(
    clippy::doc_markdown,
    clippy::too_many_arguments,
    clippy::new_without_default,
    rustdoc::bare_urls
)]

use payrs_stripe_client::{Body, Client, Error, Method, RequestSpec};

/// `POST /v1/account_sessions`
///
/// Creates a AccountSession object that includes a single-use token that the platform can use on their front-end to grant client-side API access.
#[derive(Debug, Clone)]
pub struct PostAccountSessions {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostAccountSessions {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(account: impl Into<String>, components: serde_json::Value) -> Self {
        let mut params = serde_json::Map::new();
        params.insert(
            "account".to_owned(),
            serde_json::Value::String(account.into()),
        );
        params.insert("components".to_owned(), components);
        Self {
            path: "/v1/account_sessions".to_owned(),
            params,
        }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::AccountSession, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}
