//! Generated operations for the `billing_portal` section of the Stripe v1 API.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(clippy::doc_markdown, clippy::too_many_arguments, clippy::new_without_default, rustdoc::bare_urls)]

use payrs_stripe_client::{Body, Client, Error, Method, RequestSpec};

/// `GET /v1/billing_portal/configurations`
///
/// Returns a list of configurations that describe the functionality of the customer portal.
#[derive(Debug, Clone)]
pub struct GetBillingPortalConfigurations {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetBillingPortalConfigurations {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new() -> Self {
        let params = serde_json::Map::new();
        Self { path: "/v1/billing_portal/configurations".to_owned(), params }
    }

    /// Only return configurations that are active or inactive (e.g., pass `true` to only list active configurations).
    #[must_use]
    pub fn active(mut self, value: bool) -> Self {
        self.params.insert("active".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before…
    #[must_use]
    pub fn ending_before(mut self, value: impl Into<String>) -> Self {
        self.params.insert("ending_before".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Only return the default or non-default configurations (e.g., pass `true` to only list the default configuration).
    #[must_use]
    pub fn is_default(mut self, value: bool) -> Self {
        self.params.insert("is_default".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    #[must_use]
    pub fn limit(mut self, value: i64) -> Self {
        self.params.insert("limit".to_owned(), serde_json::Value::from(value));
        self
    }

    /// A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after…
    #[must_use]
    pub fn starting_after(mut self, value: impl Into<String>) -> Self {
        self.params.insert("starting_after".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Turn this list request into a cursor [`crate::Paginator`]:
    /// `starting_after` is threaded automatically between pages.
    #[must_use]
    pub fn paginate(self) -> crate::Paginator<crate::models::BillingPortalConfiguration> {
        crate::Paginator::new(self.path, self.params)
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<payrs_stripe_types::List<crate::models::BillingPortalConfiguration>, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `POST /v1/billing_portal/configurations`
///
/// Creates a configuration that describes the functionality and behavior of a PortalSession
#[derive(Debug, Clone)]
pub struct PostBillingPortalConfigurations {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostBillingPortalConfigurations {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(features: serde_json::Value) -> Self {
        let mut params = serde_json::Map::new();
        params.insert("features".to_owned(), features);
        Self { path: "/v1/billing_portal/configurations".to_owned(), params }
    }

    /// The business information shown to customers in the portal.
    #[must_use]
    pub fn business_profile(mut self, value: serde_json::Value) -> Self {
        self.params.insert("business_profile".to_owned(), value);
        self
    }

    /// The default URL to redirect customers to when they click on the portal's link to return to your website. This can be \[overriden\](https://docs.stripe.com/api/customer_portal/sessions/create#create_portal_session-return_url) when creating…
    #[must_use]
    pub fn default_return_url(mut self, value: serde_json::Value) -> Self {
        self.params.insert("default_return_url".to_owned(), value);
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// The hosted login page for this configuration. Learn more about the portal login page in our \[integration docs\](https://stripe.com/docs/billing/subscriptions/integrating-customer-portal#share).
    #[must_use]
    pub fn login_page(mut self, value: serde_json::Value) -> Self {
        self.params.insert("login_page".to_owned(), value);
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn metadata(mut self, value: std::collections::BTreeMap<String, String>) -> Self {
        self.params.insert("metadata".to_owned(), serde_json::Value::Object(value.into_iter().map(|(k, v)| (k, serde_json::Value::String(v))).collect()));
        self
    }

    /// The name of the configuration.
    #[must_use]
    pub fn name(mut self, value: serde_json::Value) -> Self {
        self.params.insert("name".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::BillingPortalConfiguration, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `GET /v1/billing_portal/configurations/{configuration}`
///
/// Retrieves a configuration that describes the functionality of the customer portal.
#[derive(Debug, Clone)]
pub struct GetBillingPortalConfigurationsConfiguration {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetBillingPortalConfigurationsConfiguration {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(configuration: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let configuration = configuration.into();
        Self { path: format!("/v1/billing_portal/configurations/{configuration}"), params }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::BillingPortalConfiguration, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `POST /v1/billing_portal/configurations/{configuration}`
///
/// Updates a configuration that describes the functionality of the customer portal.
#[derive(Debug, Clone)]
pub struct PostBillingPortalConfigurationsConfiguration {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostBillingPortalConfigurationsConfiguration {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(configuration: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let configuration = configuration.into();
        Self { path: format!("/v1/billing_portal/configurations/{configuration}"), params }
    }

    /// Whether the configuration is active and can be used to create portal sessions.
    #[must_use]
    pub fn active(mut self, value: bool) -> Self {
        self.params.insert("active".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// The business information shown to customers in the portal.
    #[must_use]
    pub fn business_profile(mut self, value: serde_json::Value) -> Self {
        self.params.insert("business_profile".to_owned(), value);
        self
    }

    /// The default URL to redirect customers to when they click on the portal's link to return to your website. This can be \[overriden\](https://docs.stripe.com/api/customer_portal/sessions/create#create_portal_session-return_url) when creating…
    #[must_use]
    pub fn default_return_url(mut self, value: serde_json::Value) -> Self {
        self.params.insert("default_return_url".to_owned(), value);
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Information about the features available in the portal.
    #[must_use]
    pub fn features(mut self, value: serde_json::Value) -> Self {
        self.params.insert("features".to_owned(), value);
        self
    }

    /// The hosted login page for this configuration. Learn more about the portal login page in our \[integration docs\](https://stripe.com/docs/billing/subscriptions/integrating-customer-portal#share).
    #[must_use]
    pub fn login_page(mut self, value: serde_json::Value) -> Self {
        self.params.insert("login_page".to_owned(), value);
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn metadata(mut self, value: serde_json::Value) -> Self {
        self.params.insert("metadata".to_owned(), value);
        self
    }

    /// The name of the configuration.
    #[must_use]
    pub fn name(mut self, value: serde_json::Value) -> Self {
        self.params.insert("name".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::BillingPortalConfiguration, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/billing_portal/sessions`
///
/// Creates a session of the customer portal.
#[derive(Debug, Clone)]
pub struct PostBillingPortalSessions {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostBillingPortalSessions {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new() -> Self {
        let params = serde_json::Map::new();
        Self { path: "/v1/billing_portal/sessions".to_owned(), params }
    }

    /// The ID of an existing \[configuration\](https://docs.stripe.com/api/customer_portal/configurations) to use for this session, describing its functionality and features. If not specified, the session uses the default configuration.
    #[must_use]
    pub fn configuration(mut self, value: impl Into<String>) -> Self {
        self.params.insert("configuration".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The ID of an existing customer.
    #[must_use]
    pub fn customer(mut self, value: impl Into<String>) -> Self {
        self.params.insert("customer".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The ID of an existing account.
    #[must_use]
    pub fn customer_account(mut self, value: impl Into<String>) -> Self {
        self.params.insert("customer_account".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Information about a specific flow for the customer to go through. See the \[docs\](https://docs.stripe.com/customer-management/portal-deep-links) to learn more about using customer portal deep links and flows.
    #[must_use]
    pub fn flow_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("flow_data".to_owned(), value);
        self
    }

    /// The IETF language tag of the locale customer portal is displayed in. If blank or auto, the customer’s `preferred_locales` or browser’s locale is used.
    #[must_use]
    pub fn locale(mut self, value: impl Into<String>) -> Self {
        self.params.insert("locale".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The `on_behalf_of` account to use for this session. When specified, only subscriptions and invoices with this `on_behalf_of` account appear in the portal. For more information, see the \[docs\](https://docs.stripe.com/connect/separate-char…
    #[must_use]
    pub fn on_behalf_of(mut self, value: impl Into<String>) -> Self {
        self.params.insert("on_behalf_of".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The default URL to redirect customers to when they click on the portal's link to return to your website.
    #[must_use]
    pub fn return_url(mut self, value: impl Into<String>) -> Self {
        self.params.insert("return_url".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::BillingPortalSession, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}
