//! Generated operations for the `checkout` section of the Stripe v1 API.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(
    clippy::doc_markdown,
    clippy::too_many_arguments,
    clippy::new_without_default,
    rustdoc::bare_urls
)]

use payrs_stripe_client::{Body, Client, Error, Method, RequestSpec};

/// `GET /v1/checkout/sessions`
///
/// Returns a list of Checkout Sessions.
#[derive(Debug, Clone)]
pub struct GetCheckoutSessions {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetCheckoutSessions {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new() -> Self {
        let params = serde_json::Map::new();
        Self {
            path: "/v1/checkout/sessions".to_owned(),
            params,
        }
    }

    /// Only return Checkout Sessions that were created during the given date interval.
    #[must_use]
    pub fn created(mut self, value: serde_json::Value) -> Self {
        self.params.insert("created".to_owned(), value);
        self
    }

    /// Only return the Checkout Sessions for the Customer specified.
    #[must_use]
    pub fn customer(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "customer".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Only return the Checkout Sessions for the Account specified.
    #[must_use]
    pub fn customer_account(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "customer_account".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Only return the Checkout Sessions for the Customer details specified.
    #[must_use]
    pub fn customer_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("customer_details".to_owned(), value);
        self
    }

    /// A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before…
    #[must_use]
    pub fn ending_before(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "ending_before".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    #[must_use]
    pub fn limit(mut self, value: i64) -> Self {
        self.params
            .insert("limit".to_owned(), serde_json::Value::from(value));
        self
    }

    /// Only return the Checkout Session for the PaymentIntent specified.
    #[must_use]
    pub fn payment_intent(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "payment_intent".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Only return the Checkout Sessions for the Payment Link specified.
    #[must_use]
    pub fn payment_link(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "payment_link".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after…
    #[must_use]
    pub fn starting_after(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "starting_after".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Only return the Checkout Sessions matching the given status.
    #[must_use]
    pub fn status(mut self, value: impl Into<String>) -> Self {
        self.params
            .insert("status".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Only return the Checkout Session for the subscription specified.
    #[must_use]
    pub fn subscription(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "subscription".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Turn this list request into a cursor [`crate::Paginator`]:
    /// `starting_after` is threaded automatically between pages.
    #[must_use]
    pub fn paginate(self) -> crate::Paginator<crate::models::CheckoutSession> {
        crate::Paginator::new(self.path, self.params)
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<payrs_stripe_types::List<crate::models::CheckoutSession>, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `POST /v1/checkout/sessions`
///
/// Creates a Checkout Session object.
#[derive(Debug, Clone)]
pub struct PostCheckoutSessions {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostCheckoutSessions {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new() -> Self {
        let params = serde_json::Map::new();
        Self {
            path: "/v1/checkout/sessions".to_owned(),
            params,
        }
    }

    /// Settings for price localization with \[Adaptive Pricing\](https://docs.stripe.com/payments/checkout/adaptive-pricing).
    #[must_use]
    pub fn adaptive_pricing(mut self, value: serde_json::Value) -> Self {
        self.params.insert("adaptive_pricing".to_owned(), value);
        self
    }

    /// Configure actions after a Checkout Session has expired. You can't set this parameter if `ui_mode` is `elements`.
    #[must_use]
    pub fn after_expiration(mut self, value: serde_json::Value) -> Self {
        self.params.insert("after_expiration".to_owned(), value);
        self
    }

    /// Enables user redeemable promotion codes.
    #[must_use]
    pub fn allow_promotion_codes(mut self, value: bool) -> Self {
        self.params.insert(
            "allow_promotion_codes".to_owned(),
            serde_json::Value::Bool(value),
        );
        self
    }

    /// Settings for automatic tax lookup for this session and resulting payments, invoices, and subscriptions.
    #[must_use]
    pub fn automatic_tax(mut self, value: serde_json::Value) -> Self {
        self.params.insert("automatic_tax".to_owned(), value);
        self
    }

    /// Specify whether Checkout should collect the customer's billing address. Defaults to `auto`.
    #[must_use]
    pub fn billing_address_collection(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "billing_address_collection".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// The branding settings for the Checkout Session. This parameter is not allowed if ui_mode is `elements`.
    #[must_use]
    pub fn branding_settings(mut self, value: serde_json::Value) -> Self {
        self.params.insert("branding_settings".to_owned(), value);
        self
    }

    /// If set, Checkout displays a back button and customers will be directed to this URL if they decide to cancel payment and return to your website. This parameter is not allowed if ui_mode is `embedded_page` or `elements`.
    #[must_use]
    pub fn cancel_url(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "cancel_url".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// A unique string to reference the Checkout Session. This can be a customer ID, a cart ID, or similar, and can be used to reconcile the session with your internal systems.
    #[must_use]
    pub fn client_reference_id(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "client_reference_id".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Configure fields for the Checkout Session to gather active consent from customers.
    #[must_use]
    pub fn consent_collection(mut self, value: serde_json::Value) -> Self {
        self.params.insert("consent_collection".to_owned(), value);
        self
    }

    /// Three-letter \[ISO currency code\](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a \[supported currency\](https://stripe.com/docs/currencies). Required in `setup` mode when `payment_method_types` is not set.
    #[must_use]
    pub fn currency(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "currency".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Collect additional information from your customer using custom fields. Up to 3 fields are supported. You can't set this parameter if `ui_mode` is `custom`.
    #[must_use]
    pub fn custom_fields(mut self, value: serde_json::Value) -> Self {
        self.params.insert("custom_fields".to_owned(), value);
        self
    }

    /// Display additional text for your customers using custom text. You can't set this parameter if `ui_mode` is `custom`.
    #[must_use]
    pub fn custom_text(mut self, value: serde_json::Value) -> Self {
        self.params.insert("custom_text".to_owned(), value);
        self
    }

    /// ID of an existing Customer, if one exists. In `payment` mode, the customer’s most recently saved card payment method will be used to prefill the email, name, card details, and billing address on the Checkout page. In `subscription` mode, t…
    #[must_use]
    pub fn customer(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "customer".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// ID of an existing Account, if one exists. Has the same behavior as `customer`.
    #[must_use]
    pub fn customer_account(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "customer_account".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Configure whether a Checkout Session creates a \[Customer\](https://docs.stripe.com/api/customers) during Session confirmation. When a Customer is not created, you can still retrieve email, address, and other customer data entered in Check…
    #[must_use]
    pub fn customer_creation(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "customer_creation".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// If provided, this value will be used when the Customer object is created. If not provided, customers will be asked to enter their email address. Use this parameter to prefill customer data if you already have an email on file. To access in…
    #[must_use]
    pub fn customer_email(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "customer_email".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Controls what fields on Customer can be updated by the Checkout Session. Can only be provided when `customer` is provided.
    #[must_use]
    pub fn customer_update(mut self, value: serde_json::Value) -> Self {
        self.params.insert("customer_update".to_owned(), value);
        self
    }

    /// The coupon or promotion code to apply to this Session. Currently, only up to one may be specified.
    #[must_use]
    pub fn discounts(mut self, value: serde_json::Value) -> Self {
        self.params.insert("discounts".to_owned(), value);
        self
    }

    /// A list of the types of payment methods (e.g., `card`) that should be excluded from this Checkout Session. This should only be used when payment methods for this Checkout Session are managed through the \[Stripe Dashboard\](https://dashboar…
    #[must_use]
    pub fn excluded_payment_method_types(mut self, value: serde_json::Value) -> Self {
        self.params
            .insert("excluded_payment_method_types".to_owned(), value);
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// The Epoch time in seconds at which the Checkout Session will expire. It can be anywhere from 30 minutes to 24 hours after Checkout Session creation. By default, this value is 24 hours from creation.
    #[must_use]
    pub fn expires_at(mut self, value: i64) -> Self {
        self.params
            .insert("expires_at".to_owned(), serde_json::Value::from(value));
        self
    }

    /// The integration identifier for this Checkout Session. Multiple Checkout Sessions can have the same integration identifier.
    #[must_use]
    pub fn integration_identifier(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "integration_identifier".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Generate a post-purchase Invoice for one-time payments.
    #[must_use]
    pub fn invoice_creation(mut self, value: serde_json::Value) -> Self {
        self.params.insert("invoice_creation".to_owned(), value);
        self
    }

    /// A list of items the customer is purchasing. Use this parameter to pass one-time or recurring \[Prices\](https://docs.stripe.com/api/prices). The parameter is required for `payment` and `subscription` mode. For `payment` mode, there is a ma…
    #[must_use]
    pub fn line_items(mut self, value: serde_json::Value) -> Self {
        self.params.insert("line_items".to_owned(), value);
        self
    }

    /// The IETF language tag of the locale Checkout is displayed in. If blank or `auto`, the browser's locale is used.
    #[must_use]
    pub fn locale(mut self, value: impl Into<String>) -> Self {
        self.params
            .insert("locale".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Settings for Managed Payments for this Checkout Session and resulting \[PaymentIntents\](/api/payment_intents/object), \[Invoices\](/api/invoices/object), and \[Subscriptions\](/api/subscriptions/object).
    #[must_use]
    pub fn managed_payments(mut self, value: serde_json::Value) -> Self {
        self.params.insert("managed_payments".to_owned(), value);
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn metadata(mut self, value: std::collections::BTreeMap<String, String>) -> Self {
        self.params.insert(
            "metadata".to_owned(),
            serde_json::Value::Object(
                value
                    .into_iter()
                    .map(|(k, v)| (k, serde_json::Value::String(v)))
                    .collect(),
            ),
        );
        self
    }

    /// The mode of the Checkout Session. Pass `subscription` if the Checkout Session includes at least one recurring item.
    #[must_use]
    pub fn mode(mut self, value: impl Into<String>) -> Self {
        self.params
            .insert("mode".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Controls name collection settings for the session. You can configure Checkout to collect your customers' business names, individual names, or both. Each name field can be either required or optional. If a \[Customer\](https://docs.stripe.c…
    #[must_use]
    pub fn name_collection(mut self, value: serde_json::Value) -> Self {
        self.params.insert("name_collection".to_owned(), value);
        self
    }

    /// A list of optional items the customer can add to their order at checkout. Use this parameter to pass one-time or recurring \[Prices\](https://docs.stripe.com/api/prices). There is a maximum of 10 optional items allowed on a Checkout Sessio…
    #[must_use]
    pub fn optional_items(mut self, value: serde_json::Value) -> Self {
        self.params.insert("optional_items".to_owned(), value);
        self
    }

    /// Where the user is coming from. This informs the optimizations that are applied to the session. You can't set this parameter if `ui_mode` is `elements`.
    #[must_use]
    pub fn origin_context(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "origin_context".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// A subset of parameters to be passed to PaymentIntent creation for Checkout Sessions in `payment` mode.
    #[must_use]
    pub fn payment_intent_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("payment_intent_data".to_owned(), value);
        self
    }

    /// Specify whether Checkout should collect a payment method. When set to `if_required`, Checkout will not collect a payment method when the total due for the session is 0. This may occur if the Checkout Session includes a free trial or a disc…
    #[must_use]
    pub fn payment_method_collection(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "payment_method_collection".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// The ID of the payment method configuration to use with this Checkout session.
    #[must_use]
    pub fn payment_method_configuration(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "payment_method_configuration".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// This parameter allows you to set some attributes on the payment method created during a Checkout session.
    #[must_use]
    pub fn payment_method_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("payment_method_data".to_owned(), value);
        self
    }

    /// Payment-method-specific configuration.
    #[must_use]
    pub fn payment_method_options(mut self, value: serde_json::Value) -> Self {
        self.params
            .insert("payment_method_options".to_owned(), value);
        self
    }

    /// A list of the types of payment methods (e.g., `card`) this Checkout Session can accept. You can omit this attribute to manage your payment methods from the \[Stripe Dashboard\](https://dashboard.stripe.com/settings/payment_methods). See \[…
    #[must_use]
    pub fn payment_method_types(mut self, value: serde_json::Value) -> Self {
        self.params.insert("payment_method_types".to_owned(), value);
        self
    }

    /// This property is used to set up permissions for various actions (e.g., update) on the CheckoutSession object. Can only be set when creating `embedded` or `custom` sessions. For specific permissions, please refer to their dedicated subsecti…
    #[must_use]
    pub fn permissions(mut self, value: serde_json::Value) -> Self {
        self.params.insert("permissions".to_owned(), value);
        self
    }

    /// Controls phone number collection settings for the session. We recommend that you review your privacy policy and check with your legal contacts before using this feature. Learn more about \[collecting phone numbers with Checkout\](https://d…
    #[must_use]
    pub fn phone_number_collection(mut self, value: serde_json::Value) -> Self {
        self.params
            .insert("phone_number_collection".to_owned(), value);
        self
    }

    /// This parameter applies to `ui_mode: embedded_page`. Learn more about the \[redirect behavior\](https://docs.stripe.com/payments/checkout/custom-success-page?payment-ui=embedded-form) of embedded sessions. Defaults to `always`.
    #[must_use]
    pub fn redirect_on_completion(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "redirect_on_completion".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// The URL to redirect your customer back to after they authenticate or cancel their payment on the payment method's app or site. This parameter is required if `ui_mode` is `embedded_page` or `elements` and redirect-based payment methods are…
    #[must_use]
    pub fn return_url(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "return_url".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Controls saved payment method settings for the session. Only available in `payment` and `subscription` mode.
    #[must_use]
    pub fn saved_payment_method_options(mut self, value: serde_json::Value) -> Self {
        self.params
            .insert("saved_payment_method_options".to_owned(), value);
        self
    }

    /// A subset of parameters to be passed to SetupIntent creation for Checkout Sessions in `setup` mode.
    #[must_use]
    pub fn setup_intent_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("setup_intent_data".to_owned(), value);
        self
    }

    /// When set, provides configuration for Checkout to collect a shipping address from a customer.
    #[must_use]
    pub fn shipping_address_collection(mut self, value: serde_json::Value) -> Self {
        self.params
            .insert("shipping_address_collection".to_owned(), value);
        self
    }

    /// The shipping rate options to apply to this Session. Up to a maximum of 5.
    #[must_use]
    pub fn shipping_options(mut self, value: serde_json::Value) -> Self {
        self.params.insert("shipping_options".to_owned(), value);
        self
    }

    /// Describes the type of transaction being performed by Checkout in order to customize relevant text on the page, such as the submit button. `submit_type` can only be specified on Checkout Sessions in `payment` or `subscription` mode. If blan…
    #[must_use]
    pub fn submit_type(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "submit_type".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// A subset of parameters to be passed to subscription creation for Checkout Sessions in `subscription` mode.
    #[must_use]
    pub fn subscription_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("subscription_data".to_owned(), value);
        self
    }

    /// The URL to which Stripe should send customers when payment or setup is complete. This parameter is not allowed if ui_mode is `embedded_page` or `elements`. If you'd like to use information from the successful Checkout Session on your page,…
    #[must_use]
    pub fn success_url(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "success_url".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Controls tax ID collection during checkout.
    #[must_use]
    pub fn tax_id_collection(mut self, value: serde_json::Value) -> Self {
        self.params.insert("tax_id_collection".to_owned(), value);
        self
    }

    /// The UI mode of the Session. Defaults to `hosted_page`.
    #[must_use]
    pub fn ui_mode(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "ui_mode".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Wallet-specific configuration.
    #[must_use]
    pub fn wallet_options(mut self, value: serde_json::Value) -> Self {
        self.params.insert("wallet_options".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::CheckoutSession, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `GET /v1/checkout/sessions/{session}`
///
/// Retrieves a Checkout Session object.
#[derive(Debug, Clone)]
pub struct GetCheckoutSessionsSession {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetCheckoutSessionsSession {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(session: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let session = session.into();
        Self {
            path: format!("/v1/checkout/sessions/{session}"),
            params,
        }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::CheckoutSession, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `POST /v1/checkout/sessions/{session}`
///
/// Updates a Checkout Session object. Related guide: Dynamically update a Checkout Session
#[derive(Debug, Clone)]
pub struct PostCheckoutSessionsSession {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostCheckoutSessionsSession {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(session: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let session = session.into();
        Self {
            path: format!("/v1/checkout/sessions/{session}"),
            params,
        }
    }

    /// Information about the customer collected within the Checkout Session. Can only be set when updating `embedded` or `custom` sessions.
    #[must_use]
    pub fn collected_information(mut self, value: serde_json::Value) -> Self {
        self.params
            .insert("collected_information".to_owned(), value);
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// A list of items the customer is purchasing. When updating line items, you must retransmit the entire array of line items. To retain an existing line item, specify its `id`. To update an existing line item, specify its `id` along with the n…
    #[must_use]
    pub fn line_items(mut self, value: serde_json::Value) -> Self {
        self.params.insert("line_items".to_owned(), value);
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn metadata(mut self, value: serde_json::Value) -> Self {
        self.params.insert("metadata".to_owned(), value);
        self
    }

    /// The shipping rate options to apply to this Session. Up to a maximum of 5.
    #[must_use]
    pub fn shipping_options(mut self, value: serde_json::Value) -> Self {
        self.params.insert("shipping_options".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::CheckoutSession, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/checkout/sessions/{session}/expire`
///
/// A Checkout Session can be expired when it is in one of these statuses: open After it expires, a customer can’t complete a Checkout Session and customers loading the Checkout Session see a message saying the Checkout Session is expired.
#[derive(Debug, Clone)]
pub struct PostCheckoutSessionsSessionExpire {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostCheckoutSessionsSessionExpire {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(session: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let session = session.into();
        Self {
            path: format!("/v1/checkout/sessions/{session}/expire"),
            params,
        }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::CheckoutSession, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `GET /v1/checkout/sessions/{session}/line_items`
///
/// When retrieving a Checkout Session, there is an includable line_items property containing the first handful of those items. There is also a URL where you can retrieve the full (paginated) list of line items.
#[derive(Debug, Clone)]
pub struct GetCheckoutSessionsSessionLineItems {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetCheckoutSessionsSessionLineItems {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(session: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let session = session.into();
        Self {
            path: format!("/v1/checkout/sessions/{session}/line_items"),
            params,
        }
    }

    /// A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before…
    #[must_use]
    pub fn ending_before(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "ending_before".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    #[must_use]
    pub fn limit(mut self, value: i64) -> Self {
        self.params
            .insert("limit".to_owned(), serde_json::Value::from(value));
        self
    }

    /// A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after…
    #[must_use]
    pub fn starting_after(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "starting_after".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Turn this list request into a cursor [`crate::Paginator`]:
    /// `starting_after` is threaded automatically between pages.
    #[must_use]
    pub fn paginate(self) -> crate::Paginator<crate::models::Item> {
        crate::Paginator::new(self.path, self.params)
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<payrs_stripe_types::List<crate::models::Item>, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}
