//! Generated operations for the `financial_connections` section of the Stripe v1 API.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(
    clippy::doc_markdown,
    clippy::too_many_arguments,
    clippy::new_without_default,
    rustdoc::bare_urls
)]

use payrs_stripe_client::{Body, Client, Error, Method, RequestSpec};

/// `GET /v1/financial_connections/accounts`
///
/// Returns a list of Financial Connections Account objects.
#[derive(Debug, Clone)]
pub struct GetFinancialConnectionsAccounts {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetFinancialConnectionsAccounts {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new() -> Self {
        let params = serde_json::Map::new();
        Self {
            path: "/v1/financial_connections/accounts".to_owned(),
            params,
        }
    }

    /// If present, only return accounts that belong to the specified account holder. `account_holder\[customer\]` and `account_holder\[account\]` are mutually exclusive.
    #[must_use]
    pub fn account_holder(mut self, value: serde_json::Value) -> Self {
        self.params.insert("account_holder".to_owned(), value);
        self
    }

    /// A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before…
    #[must_use]
    pub fn ending_before(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "ending_before".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    #[must_use]
    pub fn limit(mut self, value: i64) -> Self {
        self.params
            .insert("limit".to_owned(), serde_json::Value::from(value));
        self
    }

    /// If present, only return accounts that were collected as part of the given session.
    #[must_use]
    pub fn session(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "session".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after…
    #[must_use]
    pub fn starting_after(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "starting_after".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Turn this list request into a cursor [`crate::Paginator`]:
    /// `starting_after` is threaded automatically between pages.
    #[must_use]
    pub fn paginate(self) -> crate::Paginator<crate::models::FinancialConnectionsAccount> {
        crate::Paginator::new(self.path, self.params)
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<payrs_stripe_types::List<crate::models::FinancialConnectionsAccount>, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `GET /v1/financial_connections/accounts/{account}`
///
/// Retrieves the details of an Financial Connections Account.
#[derive(Debug, Clone)]
pub struct GetFinancialConnectionsAccountsAccount {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetFinancialConnectionsAccountsAccount {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(account: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let account = account.into();
        Self {
            path: format!("/v1/financial_connections/accounts/{account}"),
            params,
        }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<crate::models::FinancialConnectionsAccount, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `POST /v1/financial_connections/accounts/{account}/disconnect`
///
/// Disables your access to a Financial Connections Account. You will no longer be able to access data associated with the account (e.g. balances, transactions).
#[derive(Debug, Clone)]
pub struct PostFinancialConnectionsAccountsAccountDisconnect {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostFinancialConnectionsAccountsAccountDisconnect {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(account: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let account = account.into();
        Self {
            path: format!("/v1/financial_connections/accounts/{account}/disconnect"),
            params,
        }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<crate::models::FinancialConnectionsAccount, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `GET /v1/financial_connections/accounts/{account}/owners`
///
/// Lists all owners for a given Account
#[derive(Debug, Clone)]
pub struct GetFinancialConnectionsAccountsAccountOwners {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetFinancialConnectionsAccountsAccountOwners {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(account: impl Into<String>, ownership: impl Into<String>) -> Self {
        let mut params = serde_json::Map::new();
        let account = account.into();
        params.insert(
            "ownership".to_owned(),
            serde_json::Value::String(ownership.into()),
        );
        Self {
            path: format!("/v1/financial_connections/accounts/{account}/owners"),
            params,
        }
    }

    /// A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before…
    #[must_use]
    pub fn ending_before(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "ending_before".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    #[must_use]
    pub fn limit(mut self, value: i64) -> Self {
        self.params
            .insert("limit".to_owned(), serde_json::Value::from(value));
        self
    }

    /// A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after…
    #[must_use]
    pub fn starting_after(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "starting_after".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Turn this list request into a cursor [`crate::Paginator`]:
    /// `starting_after` is threaded automatically between pages.
    #[must_use]
    pub fn paginate(self) -> crate::Paginator<crate::models::FinancialConnectionsAccountOwner> {
        crate::Paginator::new(self.path, self.params)
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<payrs_stripe_types::List<crate::models::FinancialConnectionsAccountOwner>, Error>
    {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `POST /v1/financial_connections/accounts/{account}/refresh`
///
/// Refreshes the data associated with a Financial Connections Account.
#[derive(Debug, Clone)]
pub struct PostFinancialConnectionsAccountsAccountRefresh {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostFinancialConnectionsAccountsAccountRefresh {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(account: impl Into<String>, features: serde_json::Value) -> Self {
        let mut params = serde_json::Map::new();
        let account = account.into();
        params.insert("features".to_owned(), features);
        Self {
            path: format!("/v1/financial_connections/accounts/{account}/refresh"),
            params,
        }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<crate::models::FinancialConnectionsAccount, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/financial_connections/accounts/{account}/subscribe`
///
/// Subscribes to periodic refreshes of data associated with a Financial Connections Account. When the account status is active, data is typically refreshed once a day.
#[derive(Debug, Clone)]
pub struct PostFinancialConnectionsAccountsAccountSubscribe {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostFinancialConnectionsAccountsAccountSubscribe {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(account: impl Into<String>, features: serde_json::Value) -> Self {
        let mut params = serde_json::Map::new();
        let account = account.into();
        params.insert("features".to_owned(), features);
        Self {
            path: format!("/v1/financial_connections/accounts/{account}/subscribe"),
            params,
        }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<crate::models::FinancialConnectionsAccount, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/financial_connections/accounts/{account}/unsubscribe`
///
/// Unsubscribes from periodic refreshes of data associated with a Financial Connections Account.
#[derive(Debug, Clone)]
pub struct PostFinancialConnectionsAccountsAccountUnsubscribe {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostFinancialConnectionsAccountsAccountUnsubscribe {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(account: impl Into<String>, features: serde_json::Value) -> Self {
        let mut params = serde_json::Map::new();
        let account = account.into();
        params.insert("features".to_owned(), features);
        Self {
            path: format!("/v1/financial_connections/accounts/{account}/unsubscribe"),
            params,
        }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<crate::models::FinancialConnectionsAccount, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/financial_connections/sessions`
///
/// To launch the Financial Connections authorization flow, create a Session. The session’s client_secret can be used to launch the flow using Stripe.js.
#[derive(Debug, Clone)]
pub struct PostFinancialConnectionsSessions {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostFinancialConnectionsSessions {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(account_holder: serde_json::Value, permissions: serde_json::Value) -> Self {
        let mut params = serde_json::Map::new();
        params.insert("account_holder".to_owned(), account_holder);
        params.insert("permissions".to_owned(), permissions);
        Self {
            path: "/v1/financial_connections/sessions".to_owned(),
            params,
        }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Filters to restrict the kinds of accounts to collect.
    #[must_use]
    pub fn filters(mut self, value: serde_json::Value) -> Self {
        self.params.insert("filters".to_owned(), value);
        self
    }

    /// List of data features that you would like to retrieve upon account creation.
    #[must_use]
    pub fn prefetch(mut self, value: serde_json::Value) -> Self {
        self.params.insert("prefetch".to_owned(), value);
        self
    }

    /// For webview integrations only. Upon completing OAuth login in the native browser, the user will be redirected to this URL to return to your app.
    #[must_use]
    pub fn return_url(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "return_url".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<crate::models::FinancialConnectionsSession, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `GET /v1/financial_connections/sessions/{session}`
///
/// Retrieves the details of a Financial Connections Session
#[derive(Debug, Clone)]
pub struct GetFinancialConnectionsSessionsSession {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetFinancialConnectionsSessionsSession {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(session: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let session = session.into();
        Self {
            path: format!("/v1/financial_connections/sessions/{session}"),
            params,
        }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<crate::models::FinancialConnectionsSession, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `GET /v1/financial_connections/transactions`
///
/// Returns a list of Financial Connections Transaction objects.
#[derive(Debug, Clone)]
pub struct GetFinancialConnectionsTransactions {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetFinancialConnectionsTransactions {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(account: impl Into<String>) -> Self {
        let mut params = serde_json::Map::new();
        params.insert(
            "account".to_owned(),
            serde_json::Value::String(account.into()),
        );
        Self {
            path: "/v1/financial_connections/transactions".to_owned(),
            params,
        }
    }

    /// A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before…
    #[must_use]
    pub fn ending_before(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "ending_before".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    #[must_use]
    pub fn limit(mut self, value: i64) -> Self {
        self.params
            .insert("limit".to_owned(), serde_json::Value::from(value));
        self
    }

    /// A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after…
    #[must_use]
    pub fn starting_after(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "starting_after".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// A filter on the list based on the object `transacted_at` field. The value can be a string with an integer Unix timestamp, or it can be a dictionary with the following options:
    #[must_use]
    pub fn transacted_at(mut self, value: serde_json::Value) -> Self {
        self.params.insert("transacted_at".to_owned(), value);
        self
    }

    /// A filter on the list based on the object `transaction_refresh` field. The value can be a dictionary with the following options:
    #[must_use]
    pub fn transaction_refresh(mut self, value: serde_json::Value) -> Self {
        self.params.insert("transaction_refresh".to_owned(), value);
        self
    }

    /// Turn this list request into a cursor [`crate::Paginator`]:
    /// `starting_after` is threaded automatically between pages.
    #[must_use]
    pub fn paginate(self) -> crate::Paginator<crate::models::FinancialConnectionsTransaction> {
        crate::Paginator::new(self.path, self.params)
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<payrs_stripe_types::List<crate::models::FinancialConnectionsTransaction>, Error>
    {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `GET /v1/financial_connections/transactions/{transaction}`
///
/// Retrieves the details of a Financial Connections Transaction
#[derive(Debug, Clone)]
pub struct GetFinancialConnectionsTransactionsTransaction {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetFinancialConnectionsTransactionsTransaction {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(transaction: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let transaction = transaction.into();
        Self {
            path: format!("/v1/financial_connections/transactions/{transaction}"),
            params,
        }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<crate::models::FinancialConnectionsTransaction, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}
