//! Generated operations for the `invoices` section of the Stripe v1 API.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(clippy::doc_markdown, clippy::too_many_arguments, clippy::new_without_default, rustdoc::bare_urls)]

use payrs_stripe_client::{Body, Client, Error, Method, RequestSpec};

/// `GET /v1/invoices`
///
/// You can list all invoices, or list the invoices for a specific customer. The invoices are returned sorted by creation date, with the most recently created invoices appearing first.
#[derive(Debug, Clone)]
pub struct GetInvoices {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetInvoices {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new() -> Self {
        let params = serde_json::Map::new();
        Self { path: "/v1/invoices".to_owned(), params }
    }

    /// The collection method of the invoice to retrieve. Either `charge_automatically` or `send_invoice`.
    #[must_use]
    pub fn collection_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert("collection_method".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Only return invoices that were created during the given date interval.
    #[must_use]
    pub fn created(mut self, value: serde_json::Value) -> Self {
        self.params.insert("created".to_owned(), value);
        self
    }

    /// Only return invoices for the customer specified by this customer ID.
    #[must_use]
    pub fn customer(mut self, value: impl Into<String>) -> Self {
        self.params.insert("customer".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Only return invoices for the account representing the customer specified by this account ID.
    #[must_use]
    pub fn customer_account(mut self, value: impl Into<String>) -> Self {
        self.params.insert("customer_account".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Set the `due_date` parameter.
    #[must_use]
    pub fn due_date(mut self, value: serde_json::Value) -> Self {
        self.params.insert("due_date".to_owned(), value);
        self
    }

    /// A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before…
    #[must_use]
    pub fn ending_before(mut self, value: impl Into<String>) -> Self {
        self.params.insert("ending_before".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    #[must_use]
    pub fn limit(mut self, value: i64) -> Self {
        self.params.insert("limit".to_owned(), serde_json::Value::from(value));
        self
    }

    /// A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after…
    #[must_use]
    pub fn starting_after(mut self, value: impl Into<String>) -> Self {
        self.params.insert("starting_after".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The status of the invoice, one of `draft`, `open`, `paid`, `uncollectible`, or `void`. \[Learn more\](https://docs.stripe.com/billing/invoices/workflow#workflow-overview)
    #[must_use]
    pub fn status(mut self, value: impl Into<String>) -> Self {
        self.params.insert("status".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Only return invoices for the subscription specified by this subscription ID.
    #[must_use]
    pub fn subscription(mut self, value: impl Into<String>) -> Self {
        self.params.insert("subscription".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Turn this list request into a cursor [`crate::Paginator`]:
    /// `starting_after` is threaded automatically between pages.
    #[must_use]
    pub fn paginate(self) -> crate::Paginator<crate::models::Invoice> {
        crate::Paginator::new(self.path, self.params)
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<payrs_stripe_types::List<crate::models::Invoice>, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `POST /v1/invoices`
///
/// This endpoint creates a draft invoice for a given customer. The invoice remains a draft until you finalize the invoice, which allows you to pay or send the invoice to your customers.
#[derive(Debug, Clone)]
pub struct PostInvoices {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostInvoices {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new() -> Self {
        let params = serde_json::Map::new();
        Self { path: "/v1/invoices".to_owned(), params }
    }

    /// The account tax IDs associated with the invoice. Only editable when the invoice is a draft.
    #[must_use]
    pub fn account_tax_ids(mut self, value: serde_json::Value) -> Self {
        self.params.insert("account_tax_ids".to_owned(), value);
        self
    }

    /// A fee in cents (or local equivalent) that will be applied to the invoice and transferred to the application owner's Stripe account. The request must be made with an OAuth key or the Stripe-Account header in order to take an application fee…
    #[must_use]
    pub fn application_fee_amount(mut self, value: i64) -> Self {
        self.params.insert("application_fee_amount".to_owned(), serde_json::Value::from(value));
        self
    }

    /// Controls whether Stripe performs \[automatic collection\](https://docs.stripe.com/invoicing/integration/automatic-advancement-collection) of the invoice. If `false`, the invoice's state doesn't automatically advance without an explicit act…
    #[must_use]
    pub fn auto_advance(mut self, value: bool) -> Self {
        self.params.insert("auto_advance".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// Settings for automatic tax lookup for this invoice.
    #[must_use]
    pub fn automatic_tax(mut self, value: serde_json::Value) -> Self {
        self.params.insert("automatic_tax".to_owned(), value);
        self
    }

    /// The time when this invoice should be scheduled to finalize (up to 5 years in the future). The invoice is finalized at this time if it's still in draft state.
    #[must_use]
    pub fn automatically_finalizes_at(mut self, value: i64) -> Self {
        self.params.insert("automatically_finalizes_at".to_owned(), serde_json::Value::from(value));
        self
    }

    /// Either `charge_automatically`, or `send_invoice`. When charging automatically, Stripe will attempt to pay this invoice using the default source attached to the customer. When sending an invoice, Stripe will email this invoice to the custom…
    #[must_use]
    pub fn collection_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert("collection_method".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The currency to create this invoice in. Defaults to that of `customer` if not specified.
    #[must_use]
    pub fn currency(mut self, value: impl Into<String>) -> Self {
        self.params.insert("currency".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// A list of up to 4 custom fields to be displayed on the invoice.
    #[must_use]
    pub fn custom_fields(mut self, value: serde_json::Value) -> Self {
        self.params.insert("custom_fields".to_owned(), value);
        self
    }

    /// The ID of the customer to bill.
    #[must_use]
    pub fn customer(mut self, value: impl Into<String>) -> Self {
        self.params.insert("customer".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The ID of the account to bill.
    #[must_use]
    pub fn customer_account(mut self, value: impl Into<String>) -> Self {
        self.params.insert("customer_account".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The number of days from when the invoice is created until it is due. Valid only for invoices where `collection_method=send_invoice`.
    #[must_use]
    pub fn days_until_due(mut self, value: i64) -> Self {
        self.params.insert("days_until_due".to_owned(), serde_json::Value::from(value));
        self
    }

    /// ID of the default payment method for the invoice. It must belong to the customer associated with the invoice. If not set, defaults to the subscription's default payment method, if any, or to the default payment method in the customer's inv…
    #[must_use]
    pub fn default_payment_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert("default_payment_method".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// ID of the default payment source for the invoice. It must belong to the customer associated with the invoice and be in a chargeable state. If not set, defaults to the subscription's default source, if any, or to the customer's default sour…
    #[must_use]
    pub fn default_source(mut self, value: impl Into<String>) -> Self {
        self.params.insert("default_source".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The tax rates that will apply to any line item that does not have `tax_rates` set.
    #[must_use]
    pub fn default_tax_rates(mut self, value: Vec<String>) -> Self {
        self.params.insert("default_tax_rates".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// An arbitrary string attached to the object. Often useful for displaying to users. Referenced as 'memo' in the Dashboard.
    #[must_use]
    pub fn description(mut self, value: impl Into<String>) -> Self {
        self.params.insert("description".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The coupons and promotion codes to redeem into discounts for the invoice. If not specified, inherits the discount from the invoice's customer. Pass an empty string to avoid inheriting any discounts.
    #[must_use]
    pub fn discounts(mut self, value: serde_json::Value) -> Self {
        self.params.insert("discounts".to_owned(), value);
        self
    }

    /// The date on which payment for this invoice is due. Valid only for invoices where `collection_method=send_invoice`.
    #[must_use]
    pub fn due_date(mut self, value: i64) -> Self {
        self.params.insert("due_date".to_owned(), serde_json::Value::from(value));
        self
    }

    /// The date when this invoice is in effect. Same as `finalized_at` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the invoice PDF and receipt.
    #[must_use]
    pub fn effective_at(mut self, value: i64) -> Self {
        self.params.insert("effective_at".to_owned(), serde_json::Value::from(value));
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Footer to be displayed on the invoice.
    #[must_use]
    pub fn footer(mut self, value: impl Into<String>) -> Self {
        self.params.insert("footer".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Revise an existing invoice. The new invoice will be created in `status=draft`. See the \[revision documentation\](https://docs.stripe.com/invoicing/invoice-revisions) for more details.
    #[must_use]
    pub fn from_invoice(mut self, value: serde_json::Value) -> Self {
        self.params.insert("from_invoice".to_owned(), value);
        self
    }

    /// The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
    #[must_use]
    pub fn issuer(mut self, value: serde_json::Value) -> Self {
        self.params.insert("issuer".to_owned(), value);
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn metadata(mut self, value: serde_json::Value) -> Self {
        self.params.insert("metadata".to_owned(), value);
        self
    }

    /// Set the number for this invoice. If no number is present then a number will be assigned automatically when the invoice is finalized. In many markets, regulations require invoices to be unique, sequential and / or gapless. You are responsib…
    #[must_use]
    pub fn number(mut self, value: impl Into<String>) -> Self {
        self.params.insert("number".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The account (if any) for which the funds of the invoice payment are intended. If set, the invoice will be presented with the branding and support information of the specified account. See the \[Invoices with Connect\](https://docs.stripe.c…
    #[must_use]
    pub fn on_behalf_of(mut self, value: impl Into<String>) -> Self {
        self.params.insert("on_behalf_of".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Configuration settings for the PaymentIntent that is generated when the invoice is finalized.
    #[must_use]
    pub fn payment_settings(mut self, value: serde_json::Value) -> Self {
        self.params.insert("payment_settings".to_owned(), value);
        self
    }

    /// How to handle pending invoice items on invoice creation. Defaults to `exclude` if the parameter is omitted.
    #[must_use]
    pub fn pending_invoice_items_behavior(mut self, value: impl Into<String>) -> Self {
        self.params.insert("pending_invoice_items_behavior".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The rendering-related settings that control how the invoice is displayed on customer-facing surfaces such as PDF and Hosted Invoice Page.
    #[must_use]
    pub fn rendering(mut self, value: serde_json::Value) -> Self {
        self.params.insert("rendering".to_owned(), value);
        self
    }

    /// Settings for the cost of shipping for this invoice.
    #[must_use]
    pub fn shipping_cost(mut self, value: serde_json::Value) -> Self {
        self.params.insert("shipping_cost".to_owned(), value);
        self
    }

    /// Shipping details for the invoice. The Invoice PDF will use the `shipping_details` value if it is set, otherwise the PDF will render the shipping address from the customer.
    #[must_use]
    pub fn shipping_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("shipping_details".to_owned(), value);
        self
    }

    /// Extra information about a charge for the customer's credit card statement. It must contain at least one letter. If not specified and this invoice is part of a subscription, the default `statement_descriptor` will be set to the first subscr…
    #[must_use]
    pub fn statement_descriptor(mut self, value: impl Into<String>) -> Self {
        self.params.insert("statement_descriptor".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The ID of the subscription to invoice, if any. If set, the created invoice will only include pending invoice items for that subscription. The subscription's billing cycle and regular subscription events won't be affected.
    #[must_use]
    pub fn subscription(mut self, value: impl Into<String>) -> Self {
        self.params.insert("subscription".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// If specified, the funds from the invoice will be transferred to the destination and the ID of the resulting transfer will be found on the invoice's charge.
    #[must_use]
    pub fn transfer_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("transfer_data".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Invoice, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/invoices/create_preview`
///
/// At any time, you can preview the upcoming invoice for a subscription or subscription schedule. This will show you all the charges that are pending, including subscription renewal charges, invoice item charges, etc. It will also show you any discounts that are applicable to the invoice. You can also preview the effects of creating or updating a subscription or subscription schedule, including a preview of any prorations that will take place. To ensure that the actual proration is calculated exac…
#[derive(Debug, Clone)]
pub struct PostInvoicesCreatePreview {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostInvoicesCreatePreview {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new() -> Self {
        let params = serde_json::Map::new();
        Self { path: "/v1/invoices/create_preview".to_owned(), params }
    }

    /// Settings for automatic tax lookup for this invoice preview.
    #[must_use]
    pub fn automatic_tax(mut self, value: serde_json::Value) -> Self {
        self.params.insert("automatic_tax".to_owned(), value);
        self
    }

    /// The currency to preview this invoice in. Defaults to that of `customer` if not specified.
    #[must_use]
    pub fn currency(mut self, value: impl Into<String>) -> Self {
        self.params.insert("currency".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The identifier of the customer whose upcoming invoice you're retrieving. If `automatic_tax` is enabled then one of `customer`, `customer_details`, `subscription`, or `schedule` must be set.
    #[must_use]
    pub fn customer(mut self, value: impl Into<String>) -> Self {
        self.params.insert("customer".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The identifier of the account representing the customer whose upcoming invoice you're retrieving. If `automatic_tax` is enabled then one of `customer`, `customer_account`, `customer_details`, `subscription`, or `schedule` must be set.
    #[must_use]
    pub fn customer_account(mut self, value: impl Into<String>) -> Self {
        self.params.insert("customer_account".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Details about the customer you want to invoice or overrides for an existing customer. If `automatic_tax` is enabled then one of `customer`, `customer_details`, `subscription`, or `schedule` must be set.
    #[must_use]
    pub fn customer_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("customer_details".to_owned(), value);
        self
    }

    /// The coupons to redeem into discounts for the invoice preview. If not specified, inherits the discount from the subscription or customer. This works for both coupons directly applied to an invoice and coupons applied to a subscription. Pass…
    #[must_use]
    pub fn discounts(mut self, value: serde_json::Value) -> Self {
        self.params.insert("discounts".to_owned(), value);
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// List of invoice items to add or update in the upcoming invoice preview (up to 250).
    #[must_use]
    pub fn invoice_items(mut self, value: serde_json::Value) -> Self {
        self.params.insert("invoice_items".to_owned(), value);
        self
    }

    /// The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
    #[must_use]
    pub fn issuer(mut self, value: serde_json::Value) -> Self {
        self.params.insert("issuer".to_owned(), value);
        self
    }

    /// The account (if any) for which the funds of the invoice payment are intended. If set, the invoice will be presented with the branding and support information of the specified account. See the \[Invoices with Connect\](https://docs.stripe.c…
    #[must_use]
    pub fn on_behalf_of(mut self, value: serde_json::Value) -> Self {
        self.params.insert("on_behalf_of".to_owned(), value);
        self
    }

    /// Customizes the types of values to include when calculating the invoice. Defaults to `next` if unspecified.
    #[must_use]
    pub fn preview_mode(mut self, value: impl Into<String>) -> Self {
        self.params.insert("preview_mode".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The identifier of the schedule whose upcoming invoice you'd like to retrieve. Cannot be used with subscription or subscription fields.
    #[must_use]
    pub fn schedule(mut self, value: impl Into<String>) -> Self {
        self.params.insert("schedule".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The schedule creation or modification params to apply as a preview. Cannot be used with `subscription` or `subscription_` prefixed fields.
    #[must_use]
    pub fn schedule_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("schedule_details".to_owned(), value);
        self
    }

    /// The identifier of the subscription for which you'd like to retrieve the upcoming invoice. If not provided, but a `subscription_details.items` is provided, you will preview creating a subscription with those items. If neither `subscription`…
    #[must_use]
    pub fn subscription(mut self, value: impl Into<String>) -> Self {
        self.params.insert("subscription".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The subscription creation or modification params to apply as a preview. Cannot be used with `schedule` or `schedule_details` fields.
    #[must_use]
    pub fn subscription_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("subscription_details".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Invoice, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `GET /v1/invoices/search`
///
/// Search for invoices you’ve previously created using Stripe’s Search Query Language. Don’t use search in read-after-write flows where strict consistency is necessary. Under normal operating conditions, data is searchable in less than a minute. Occasionally, propagation of new or updated data can be up to an hour behind during outages. Search functionality is not available to merchants in India.
#[derive(Debug, Clone)]
pub struct GetInvoicesSearch {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetInvoicesSearch {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(query: impl Into<String>) -> Self {
        let mut params = serde_json::Map::new();
        params.insert("query".to_owned(), serde_json::Value::String(query.into()));
        Self { path: "/v1/invoices/search".to_owned(), params }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    #[must_use]
    pub fn limit(mut self, value: i64) -> Self {
        self.params.insert("limit".to_owned(), serde_json::Value::from(value));
        self
    }

    /// A cursor for pagination across multiple pages of results. Don't include this parameter on the first call. Use the next_page value returned in a previous response to request subsequent results.
    #[must_use]
    pub fn page(mut self, value: impl Into<String>) -> Self {
        self.params.insert("page".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Turn this list request into a cursor [`crate::Paginator`]:
    /// `starting_after` is threaded automatically between pages.
    #[must_use]
    pub fn paginate(self) -> crate::Paginator<crate::models::Invoice> {
        crate::Paginator::new(self.path, self.params)
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<payrs_stripe_types::List<crate::models::Invoice>, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `GET /v1/invoices/{invoice}`
///
/// Retrieves the invoice with the given ID.
#[derive(Debug, Clone)]
pub struct GetInvoicesInvoice {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetInvoicesInvoice {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(invoice: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let invoice = invoice.into();
        Self { path: format!("/v1/invoices/{invoice}"), params }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Invoice, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `POST /v1/invoices/{invoice}`
///
/// Draft invoices are fully editable. Once an invoice is finalized, monetary values, as well as collection_method, become uneditable. If you would like to stop the Stripe Billing engine from automatically finalizing, reattempting payments on, sending reminders for, or automatically reconciling invoices, pass auto_advance=false.
#[derive(Debug, Clone)]
pub struct PostInvoicesInvoice {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostInvoicesInvoice {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(invoice: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let invoice = invoice.into();
        Self { path: format!("/v1/invoices/{invoice}"), params }
    }

    /// The account tax IDs associated with the invoice. Only editable when the invoice is a draft.
    #[must_use]
    pub fn account_tax_ids(mut self, value: serde_json::Value) -> Self {
        self.params.insert("account_tax_ids".to_owned(), value);
        self
    }

    /// A fee in cents (or local equivalent) that will be applied to the invoice and transferred to the application owner's Stripe account. The request must be made with an OAuth key or the Stripe-Account header in order to take an application fee…
    #[must_use]
    pub fn application_fee_amount(mut self, value: i64) -> Self {
        self.params.insert("application_fee_amount".to_owned(), serde_json::Value::from(value));
        self
    }

    /// Controls whether Stripe performs \[automatic collection\](https://docs.stripe.com/invoicing/integration/automatic-advancement-collection) of the invoice.
    #[must_use]
    pub fn auto_advance(mut self, value: bool) -> Self {
        self.params.insert("auto_advance".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// Settings for automatic tax lookup for this invoice.
    #[must_use]
    pub fn automatic_tax(mut self, value: serde_json::Value) -> Self {
        self.params.insert("automatic_tax".to_owned(), value);
        self
    }

    /// The time when this invoice should be scheduled to finalize (up to 5 years in the future). The invoice is finalized at this time if it's still in draft state. To turn off automatic finalization, set `auto_advance` to false.
    #[must_use]
    pub fn automatically_finalizes_at(mut self, value: i64) -> Self {
        self.params.insert("automatically_finalizes_at".to_owned(), serde_json::Value::from(value));
        self
    }

    /// Either `charge_automatically` or `send_invoice`. This field can be updated only on `draft` invoices.
    #[must_use]
    pub fn collection_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert("collection_method".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// A list of up to 4 custom fields to be displayed on the invoice. If a value for `custom_fields` is specified, the list specified will replace the existing custom field list on this invoice. Pass an empty string to remove previously-defined…
    #[must_use]
    pub fn custom_fields(mut self, value: serde_json::Value) -> Self {
        self.params.insert("custom_fields".to_owned(), value);
        self
    }

    /// The number of days from which the invoice is created until it is due. Only valid for invoices where `collection_method=send_invoice`. This field can only be updated on `draft` invoices.
    #[must_use]
    pub fn days_until_due(mut self, value: i64) -> Self {
        self.params.insert("days_until_due".to_owned(), serde_json::Value::from(value));
        self
    }

    /// ID of the default payment method for the invoice. It must belong to the customer associated with the invoice. If not set, defaults to the subscription's default payment method, if any, or to the default payment method in the customer's inv…
    #[must_use]
    pub fn default_payment_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert("default_payment_method".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// ID of the default payment source for the invoice. It must belong to the customer associated with the invoice and be in a chargeable state. If not set, defaults to the subscription's default source, if any, or to the customer's default sour…
    #[must_use]
    pub fn default_source(mut self, value: serde_json::Value) -> Self {
        self.params.insert("default_source".to_owned(), value);
        self
    }

    /// The tax rates that will apply to any line item that does not have `tax_rates` set. Pass an empty string to remove previously-defined tax rates.
    #[must_use]
    pub fn default_tax_rates(mut self, value: serde_json::Value) -> Self {
        self.params.insert("default_tax_rates".to_owned(), value);
        self
    }

    /// An arbitrary string attached to the object. Often useful for displaying to users. Referenced as 'memo' in the Dashboard.
    #[must_use]
    pub fn description(mut self, value: impl Into<String>) -> Self {
        self.params.insert("description".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The discounts that will apply to the invoice. Pass an empty string to remove previously-defined discounts.
    #[must_use]
    pub fn discounts(mut self, value: serde_json::Value) -> Self {
        self.params.insert("discounts".to_owned(), value);
        self
    }

    /// The date on which payment for this invoice is due. Only valid for invoices where `collection_method=send_invoice`. This field can only be updated on `draft` invoices.
    #[must_use]
    pub fn due_date(mut self, value: i64) -> Self {
        self.params.insert("due_date".to_owned(), serde_json::Value::from(value));
        self
    }

    /// The date when this invoice is in effect. Same as `finalized_at` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the invoice PDF and receipt.
    #[must_use]
    pub fn effective_at(mut self, value: serde_json::Value) -> Self {
        self.params.insert("effective_at".to_owned(), value);
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Footer to be displayed on the invoice.
    #[must_use]
    pub fn footer(mut self, value: impl Into<String>) -> Self {
        self.params.insert("footer".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
    #[must_use]
    pub fn issuer(mut self, value: serde_json::Value) -> Self {
        self.params.insert("issuer".to_owned(), value);
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn metadata(mut self, value: serde_json::Value) -> Self {
        self.params.insert("metadata".to_owned(), value);
        self
    }

    /// Set the number for this invoice. If no number is present then a number will be assigned automatically when the invoice is finalized. In many markets, regulations require invoices to be unique, sequential and / or gapless. You are responsib…
    #[must_use]
    pub fn number(mut self, value: serde_json::Value) -> Self {
        self.params.insert("number".to_owned(), value);
        self
    }

    /// The account (if any) for which the funds of the invoice payment are intended. If set, the invoice will be presented with the branding and support information of the specified account. See the \[Invoices with Connect\](https://docs.stripe.c…
    #[must_use]
    pub fn on_behalf_of(mut self, value: serde_json::Value) -> Self {
        self.params.insert("on_behalf_of".to_owned(), value);
        self
    }

    /// Configuration settings for the PaymentIntent that is generated when the invoice is finalized.
    #[must_use]
    pub fn payment_settings(mut self, value: serde_json::Value) -> Self {
        self.params.insert("payment_settings".to_owned(), value);
        self
    }

    /// The rendering-related settings that control how the invoice is displayed on customer-facing surfaces such as PDF and Hosted Invoice Page.
    #[must_use]
    pub fn rendering(mut self, value: serde_json::Value) -> Self {
        self.params.insert("rendering".to_owned(), value);
        self
    }

    /// Settings for the cost of shipping for this invoice.
    #[must_use]
    pub fn shipping_cost(mut self, value: serde_json::Value) -> Self {
        self.params.insert("shipping_cost".to_owned(), value);
        self
    }

    /// Shipping details for the invoice. The Invoice PDF will use the `shipping_details` value if it is set, otherwise the PDF will render the shipping address from the customer.
    #[must_use]
    pub fn shipping_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("shipping_details".to_owned(), value);
        self
    }

    /// Extra information about a charge for the customer's credit card statement. It must contain at least one letter. If not specified and this invoice is part of a subscription, the default `statement_descriptor` will be set to the first subscr…
    #[must_use]
    pub fn statement_descriptor(mut self, value: impl Into<String>) -> Self {
        self.params.insert("statement_descriptor".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// If specified, the funds from the invoice will be transferred to the destination and the ID of the resulting transfer will be found on the invoice's charge. This will be unset if you POST an empty value.
    #[must_use]
    pub fn transfer_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("transfer_data".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Invoice, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `DELETE /v1/invoices/{invoice}`
///
/// Permanently deletes a one-off invoice draft. This cannot be undone. Attempts to delete invoices that are no longer in a draft state will fail; once an invoice has been finalized or if an invoice is for a subscription, it must be voided.
#[derive(Debug, Clone)]
pub struct DeleteInvoicesInvoice {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl DeleteInvoicesInvoice {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(invoice: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let invoice = invoice.into();
        Self { path: format!("/v1/invoices/{invoice}"), params }
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::DeletedInvoice, Error> {
        let mut spec = RequestSpec::new(Method::Delete, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/invoices/{invoice}/add_lines`
///
/// Adds multiple line items to an invoice. This is only possible when an invoice is still a draft.
#[derive(Debug, Clone)]
pub struct PostInvoicesInvoiceAddLines {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostInvoicesInvoiceAddLines {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(invoice: impl Into<String>, lines: serde_json::Value) -> Self {
        let mut params = serde_json::Map::new();
        let invoice = invoice.into();
        params.insert("lines".to_owned(), lines);
        Self { path: format!("/v1/invoices/{invoice}/add_lines"), params }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn invoice_metadata(mut self, value: serde_json::Value) -> Self {
        self.params.insert("invoice_metadata".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Invoice, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/invoices/{invoice}/attach_payment`
///
/// Attaches a PaymentIntent or an Out of Band Payment to the invoice, adding it to the list of payments. For the PaymentIntent, when the PaymentIntent’s status changes to succeeded, the payment is credited to the invoice, increasing its amount_paid. When the invoice is fully paid, the invoice’s status becomes paid. If the PaymentIntent’s status is already succeeded when it’s attached, it’s credited to the invoice immediately. See: Partial payments to learn more.
#[derive(Debug, Clone)]
pub struct PostInvoicesInvoiceAttachPayment {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostInvoicesInvoiceAttachPayment {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(invoice: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let invoice = invoice.into();
        Self { path: format!("/v1/invoices/{invoice}/attach_payment"), params }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// The ID of the PaymentIntent to attach to the invoice.
    #[must_use]
    pub fn payment_intent(mut self, value: impl Into<String>) -> Self {
        self.params.insert("payment_intent".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The ID of the PaymentRecord to attach to the invoice.
    #[must_use]
    pub fn payment_record(mut self, value: impl Into<String>) -> Self {
        self.params.insert("payment_record".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Invoice, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/invoices/{invoice}/finalize`
///
/// Stripe automatically finalizes drafts before sending and attempting payment on invoices. However, if you’d like to finalize a draft invoice manually, you can do so using this method.
#[derive(Debug, Clone)]
pub struct PostInvoicesInvoiceFinalize {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostInvoicesInvoiceFinalize {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(invoice: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let invoice = invoice.into();
        Self { path: format!("/v1/invoices/{invoice}/finalize"), params }
    }

    /// Controls whether Stripe performs \[automatic collection\](https://docs.stripe.com/invoicing/integration/automatic-advancement-collection) of the invoice. If `false`, the invoice's state doesn't automatically advance without an explicit act…
    #[must_use]
    pub fn auto_advance(mut self, value: bool) -> Self {
        self.params.insert("auto_advance".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Invoice, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `GET /v1/invoices/{invoice}/lines`
///
/// When retrieving an invoice, you’ll get a lines property containing the total count of line items and the first handful of those items. There is also a URL where you can retrieve the full (paginated) list of line items.
#[derive(Debug, Clone)]
pub struct GetInvoicesInvoiceLines {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetInvoicesInvoiceLines {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(invoice: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let invoice = invoice.into();
        Self { path: format!("/v1/invoices/{invoice}/lines"), params }
    }

    /// A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before…
    #[must_use]
    pub fn ending_before(mut self, value: impl Into<String>) -> Self {
        self.params.insert("ending_before".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    #[must_use]
    pub fn limit(mut self, value: i64) -> Self {
        self.params.insert("limit".to_owned(), serde_json::Value::from(value));
        self
    }

    /// A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after…
    #[must_use]
    pub fn starting_after(mut self, value: impl Into<String>) -> Self {
        self.params.insert("starting_after".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Turn this list request into a cursor [`crate::Paginator`]:
    /// `starting_after` is threaded automatically between pages.
    #[must_use]
    pub fn paginate(self) -> crate::Paginator<crate::models::LineItem> {
        crate::Paginator::new(self.path, self.params)
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<payrs_stripe_types::List<crate::models::LineItem>, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `POST /v1/invoices/{invoice}/lines/{line_item_id}`
///
/// Updates an invoice’s line item. Some fields, such as tax_amounts, only live on the invoice line item, so they can only be updated through this endpoint. Other fields, such as amount, live on both the invoice item and the invoice line item, so updates on this endpoint will propagate to the invoice item as well. Updating an invoice’s line item is only possible before the invoice is finalized.
#[derive(Debug, Clone)]
pub struct PostInvoicesInvoiceLinesLineItemId {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostInvoicesInvoiceLinesLineItemId {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(invoice: impl Into<String>, line_item_id: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let invoice = invoice.into();
        let line_item_id = line_item_id.into();
        Self { path: format!("/v1/invoices/{invoice}/lines/{line_item_id}"), params }
    }

    /// The integer amount in cents (or local equivalent) of the charge to be applied to the upcoming invoice. If you want to apply a credit to the customer's account, pass a negative amount.
    #[must_use]
    pub fn amount(mut self, value: i64) -> Self {
        self.params.insert("amount".to_owned(), serde_json::Value::from(value));
        self
    }

    /// An arbitrary string which you can attach to the invoice item. The description is displayed in the invoice for easy tracking.
    #[must_use]
    pub fn description(mut self, value: impl Into<String>) -> Self {
        self.params.insert("description".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Controls whether discounts apply to this line item. Defaults to false for prorations or negative line items, and true for all other line items. Cannot be set to true for prorations.
    #[must_use]
    pub fn discountable(mut self, value: bool) -> Self {
        self.params.insert("discountable".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// The coupons, promotion codes & existing discounts which apply to the line item. Item discounts are applied before invoice discounts. Pass an empty string to remove previously-defined discounts.
    #[must_use]
    pub fn discounts(mut self, value: serde_json::Value) -> Self {
        self.params.insert("discounts".to_owned(), value);
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn metadata(mut self, value: serde_json::Value) -> Self {
        self.params.insert("metadata".to_owned(), value);
        self
    }

    /// The period associated with this invoice item. When set to different values, the period will be rendered on the invoice. If you have \[Stripe Revenue Recognition\](https://docs.stripe.com/revenue-recognition) enabled, the period will be use…
    #[must_use]
    pub fn period(mut self, value: serde_json::Value) -> Self {
        self.params.insert("period".to_owned(), value);
        self
    }

    /// Data used to generate a new \[Price\](https://docs.stripe.com/api/prices) object inline.
    #[must_use]
    pub fn price_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("price_data".to_owned(), value);
        self
    }

    /// The pricing information for the invoice item.
    #[must_use]
    pub fn pricing(mut self, value: serde_json::Value) -> Self {
        self.params.insert("pricing".to_owned(), value);
        self
    }

    /// Non-negative integer. The quantity of units for the line item. Use `quantity_decimal` instead to provide decimal precision. This field will be deprecated in favor of `quantity_decimal` in a future version.
    #[must_use]
    pub fn quantity(mut self, value: i64) -> Self {
        self.params.insert("quantity".to_owned(), serde_json::Value::from(value));
        self
    }

    /// Non-negative decimal with at most 12 decimal places. The quantity of units for the line item.
    #[must_use]
    pub fn quantity_decimal(mut self, value: impl Into<String>) -> Self {
        self.params.insert("quantity_decimal".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// A list of up to 20 tax amounts for this line item. This can be useful if you calculate taxes on your own or use a third-party to calculate them. You cannot set tax amounts if any line item has \[tax_rates\](https://docs.stripe.com/api/invo…
    #[must_use]
    pub fn tax_amounts(mut self, value: serde_json::Value) -> Self {
        self.params.insert("tax_amounts".to_owned(), value);
        self
    }

    /// The tax rates which apply to the line item. When set, the `default_tax_rates` on the invoice do not apply to this line item. Pass an empty string to remove previously-defined tax rates.
    #[must_use]
    pub fn tax_rates(mut self, value: serde_json::Value) -> Self {
        self.params.insert("tax_rates".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::LineItem, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/invoices/{invoice}/mark_uncollectible`
///
/// Marking an invoice as uncollectible is useful for keeping track of bad debts that can be written off for accounting purposes.
#[derive(Debug, Clone)]
pub struct PostInvoicesInvoiceMarkUncollectible {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostInvoicesInvoiceMarkUncollectible {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(invoice: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let invoice = invoice.into();
        Self { path: format!("/v1/invoices/{invoice}/mark_uncollectible"), params }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Invoice, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/invoices/{invoice}/pay`
///
/// Stripe automatically creates and then attempts to collect payment on invoices for customers on subscriptions according to your subscriptions settings. However, if you’d like to attempt payment on an invoice out of the normal collection schedule or for some other reason, you can do so.
#[derive(Debug, Clone)]
pub struct PostInvoicesInvoicePay {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostInvoicesInvoicePay {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(invoice: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let invoice = invoice.into();
        Self { path: format!("/v1/invoices/{invoice}/pay"), params }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// In cases where the source used to pay the invoice has insufficient funds, passing `forgive=true` controls whether a charge should be attempted for the full amount available on the source, up to the amount to fully pay the invoice. This eff…
    #[must_use]
    pub fn forgive(mut self, value: bool) -> Self {
        self.params.insert("forgive".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// ID of the mandate to be used for this invoice. It must correspond to the payment method used to pay the invoice, including the payment_method param or the invoice's default_payment_method or default_source, if set.
    #[must_use]
    pub fn mandate(mut self, value: serde_json::Value) -> Self {
        self.params.insert("mandate".to_owned(), value);
        self
    }

    /// Indicates if a customer is on or off-session while an invoice payment is attempted. Defaults to `true` (off-session).
    #[must_use]
    pub fn off_session(mut self, value: bool) -> Self {
        self.params.insert("off_session".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// Boolean representing whether an invoice is paid outside of Stripe. This will result in no charge being made. Defaults to `false`.
    #[must_use]
    pub fn paid_out_of_band(mut self, value: bool) -> Self {
        self.params.insert("paid_out_of_band".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// A PaymentMethod to be charged. The PaymentMethod must be the ID of a PaymentMethod belonging to the customer associated with the invoice being paid.
    #[must_use]
    pub fn payment_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert("payment_method".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// A payment source to be charged. The source must be the ID of a source belonging to the customer associated with the invoice being paid.
    #[must_use]
    pub fn source(mut self, value: impl Into<String>) -> Self {
        self.params.insert("source".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Invoice, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/invoices/{invoice}/remove_lines`
///
/// Removes multiple line items from an invoice. This is only possible when an invoice is still a draft.
#[derive(Debug, Clone)]
pub struct PostInvoicesInvoiceRemoveLines {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostInvoicesInvoiceRemoveLines {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(invoice: impl Into<String>, lines: serde_json::Value) -> Self {
        let mut params = serde_json::Map::new();
        let invoice = invoice.into();
        params.insert("lines".to_owned(), lines);
        Self { path: format!("/v1/invoices/{invoice}/remove_lines"), params }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn invoice_metadata(mut self, value: serde_json::Value) -> Self {
        self.params.insert("invoice_metadata".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Invoice, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/invoices/{invoice}/send`
///
/// Stripe will automatically send invoices to customers according to your subscriptions settings. However, if you’d like to manually send an invoice to your customer out of the normal schedule, you can do so. When sending invoices that have already been paid, there will be no reference to the payment in the email. Requests made in test-mode result in no emails being sent, despite sending an invoice.sent event.
#[derive(Debug, Clone)]
pub struct PostInvoicesInvoiceSend {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostInvoicesInvoiceSend {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(invoice: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let invoice = invoice.into();
        Self { path: format!("/v1/invoices/{invoice}/send"), params }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Invoice, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/invoices/{invoice}/update_lines`
///
/// Updates multiple line items on an invoice. This is only possible when an invoice is still a draft.
#[derive(Debug, Clone)]
pub struct PostInvoicesInvoiceUpdateLines {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostInvoicesInvoiceUpdateLines {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(invoice: impl Into<String>, lines: serde_json::Value) -> Self {
        let mut params = serde_json::Map::new();
        let invoice = invoice.into();
        params.insert("lines".to_owned(), lines);
        Self { path: format!("/v1/invoices/{invoice}/update_lines"), params }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn invoice_metadata(mut self, value: serde_json::Value) -> Self {
        self.params.insert("invoice_metadata".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Invoice, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/invoices/{invoice}/void`
///
/// Mark a finalized invoice as void. This cannot be undone. Voiding an invoice is similar to deletion, however it only applies to finalized invoices and maintains a papertrail where the invoice can still be found. Consult with local regulations to determine whether and how an invoice might be amended, canceled, or voided in the jurisdiction you’re doing business in. You might need to issue another invoice or credit note instead. Stripe recommends that you consult with your legal counsel for advice…
#[derive(Debug, Clone)]
pub struct PostInvoicesInvoiceVoid {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostInvoicesInvoiceVoid {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(invoice: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let invoice = invoice.into();
        Self { path: format!("/v1/invoices/{invoice}/void"), params }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Invoice, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}
