//! Generated operations for the `payment_intents` section of the Stripe v1 API.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(
    clippy::doc_markdown,
    clippy::too_many_arguments,
    clippy::new_without_default,
    rustdoc::bare_urls
)]

use payrs_stripe_client::{Body, Client, Error, Method, RequestSpec};

/// `GET /v1/payment_intents`
///
/// Returns a list of PaymentIntents.
#[derive(Debug, Clone)]
pub struct GetPaymentIntents {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetPaymentIntents {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new() -> Self {
        let params = serde_json::Map::new();
        Self {
            path: "/v1/payment_intents".to_owned(),
            params,
        }
    }

    /// A filter on the list, based on the object `created` field. The value can be a string with an integer Unix timestamp or a dictionary with a number of different query options.
    #[must_use]
    pub fn created(mut self, value: serde_json::Value) -> Self {
        self.params.insert("created".to_owned(), value);
        self
    }

    /// Only return PaymentIntents for the customer that this customer ID specifies.
    #[must_use]
    pub fn customer(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "customer".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Only return PaymentIntents for the account representing the customer that this ID specifies.
    #[must_use]
    pub fn customer_account(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "customer_account".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before…
    #[must_use]
    pub fn ending_before(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "ending_before".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    #[must_use]
    pub fn limit(mut self, value: i64) -> Self {
        self.params
            .insert("limit".to_owned(), serde_json::Value::from(value));
        self
    }

    /// A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after…
    #[must_use]
    pub fn starting_after(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "starting_after".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Turn this list request into a cursor [`crate::Paginator`]:
    /// `starting_after` is threaded automatically between pages.
    #[must_use]
    pub fn paginate(self) -> crate::Paginator<crate::models::PaymentIntent> {
        crate::Paginator::new(self.path, self.params)
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<payrs_stripe_types::List<crate::models::PaymentIntent>, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `POST /v1/payment_intents`
///
/// Creates a PaymentIntent object. After the PaymentIntent is created, attach a payment method and confirm to continue the payment. Learn more about the available payment flows with the Payment Intents API. When you use confirm=true during creation, it’s equivalent to creating and confirming the PaymentIntent in the same call. You can use any parameters available in the confirm API when you supply confirm=true.
#[derive(Debug, Clone)]
pub struct PostPaymentIntents {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostPaymentIntents {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(amount: i64, currency: impl Into<String>) -> Self {
        let mut params = serde_json::Map::new();
        params.insert("amount".to_owned(), serde_json::Value::from(amount));
        params.insert(
            "currency".to_owned(),
            serde_json::Value::String(currency.into()),
        );
        Self {
            path: "/v1/payment_intents".to_owned(),
            params,
        }
    }

    /// Provides industry-specific information about the amount.
    #[must_use]
    pub fn amount_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("amount_details".to_owned(), value);
        self
    }

    /// The amount of the application fee (if any) that will be requested to be applied to the payment and transferred to the application owner's Stripe account. The amount of the application fee collected will be capped at the total amount captur…
    #[must_use]
    pub fn application_fee_amount(mut self, value: i64) -> Self {
        self.params.insert(
            "application_fee_amount".to_owned(),
            serde_json::Value::from(value),
        );
        self
    }

    /// When you enable this parameter, this PaymentIntent accepts payment methods that you enable in the Dashboard and that are compatible with this PaymentIntent's other parameters.
    #[must_use]
    pub fn automatic_payment_methods(mut self, value: serde_json::Value) -> Self {
        self.params
            .insert("automatic_payment_methods".to_owned(), value);
        self
    }

    /// Controls when the funds will be captured from the customer's account.
    #[must_use]
    pub fn capture_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "capture_method".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Set to `true` to attempt to \[confirm this PaymentIntent\](https://docs.stripe.com/api/payment_intents/confirm) immediately. This parameter defaults to `false`. When creating and confirming a PaymentIntent at the same time, you can also pr…
    #[must_use]
    pub fn confirm(mut self, value: bool) -> Self {
        self.params
            .insert("confirm".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// Describes whether we can confirm this PaymentIntent automatically, or if it requires customer action to confirm the payment.
    #[must_use]
    pub fn confirmation_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "confirmation_method".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// ID of the ConfirmationToken used to confirm this PaymentIntent. If the provided ConfirmationToken contains properties that are also being provided in this request, such as `payment_method`, then the values in this request will take precede…
    #[must_use]
    pub fn confirmation_token(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "confirmation_token".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// ID of the Customer this PaymentIntent belongs to, if one exists. Payment methods attached to other Customers cannot be used with this PaymentIntent. If \[setup_future_usage\](https://api.stripe.com#payment_intent_object-setup_future_usage)…
    #[must_use]
    pub fn customer(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "customer".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// ID of the Account representing the customer that this PaymentIntent belongs to, if one exists. Payment methods attached to other Accounts cannot be used with this PaymentIntent. If \[setup_future_usage\](https://api.stripe.com#payment_inte…
    #[must_use]
    pub fn customer_account(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "customer_account".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// An arbitrary string attached to the object. Often useful for displaying to users.
    #[must_use]
    pub fn description(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "description".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Set to `true` to fail the payment attempt if the PaymentIntent transitions into `requires_action`. Use this parameter for simpler integrations that don't handle customer actions, such as \[saving cards without authentication\](https://docs…
    #[must_use]
    pub fn error_on_requires_action(mut self, value: bool) -> Self {
        self.params.insert(
            "error_on_requires_action".to_owned(),
            serde_json::Value::Bool(value),
        );
        self
    }

    /// The list of payment method types to exclude from use with this payment.
    #[must_use]
    pub fn excluded_payment_method_types(mut self, value: serde_json::Value) -> Self {
        self.params
            .insert("excluded_payment_method_types".to_owned(), value);
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Automations to be run during the PaymentIntent lifecycle
    #[must_use]
    pub fn hooks(mut self, value: serde_json::Value) -> Self {
        self.params.insert("hooks".to_owned(), value);
        self
    }

    /// ID of the mandate that's used for this payment. This parameter can only be used with \[`confirm=true`\](https://docs.stripe.com/api/payment_intents/create#create_payment_intent-confirm).
    #[must_use]
    pub fn mandate(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "mandate".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// This hash contains details about the Mandate to create. This parameter can only be used with \[`confirm=true`\](https://docs.stripe.com/api/payment_intents/create#create_payment_intent-confirm).
    #[must_use]
    pub fn mandate_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("mandate_data".to_owned(), value);
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn metadata(mut self, value: std::collections::BTreeMap<String, String>) -> Self {
        self.params.insert(
            "metadata".to_owned(),
            serde_json::Value::Object(
                value
                    .into_iter()
                    .map(|(k, v)| (k, serde_json::Value::String(v)))
                    .collect(),
            ),
        );
        self
    }

    /// Set to `true` to indicate that the customer isn't in your checkout flow during this payment attempt and can't authenticate. Use this parameter in scenarios where you collect payment method details and \[charge them later\](https://docs.str…
    #[must_use]
    pub fn off_session(mut self, value: serde_json::Value) -> Self {
        self.params.insert("off_session".to_owned(), value);
        self
    }

    /// The Stripe account ID that these funds are intended for. Learn more about the \[use case for connected accounts\](https://docs.stripe.com/payments/connected-accounts).
    #[must_use]
    pub fn on_behalf_of(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "on_behalf_of".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Provides industry-specific information about the charge.
    #[must_use]
    pub fn payment_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("payment_details".to_owned(), value);
        self
    }

    /// ID of the payment method (a PaymentMethod, Card, or \[compatible Source\](https://docs.stripe.com/payments/payment-methods/transitioning#compatibility) object) to attach to this PaymentIntent. If you omit this parameter with `confirm=true`…
    #[must_use]
    pub fn payment_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "payment_method".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// The ID of the \[payment method configuration\](https://docs.stripe.com/api/payment_method_configurations) to use with this PaymentIntent.
    #[must_use]
    pub fn payment_method_configuration(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "payment_method_configuration".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// If provided, this hash will be used to create a PaymentMethod. The new PaymentMethod will appear in the \[payment_method\](https://docs.stripe.com/api/payment_intents/object#payment_intent_object-payment_method) property on the PaymentInte…
    #[must_use]
    pub fn payment_method_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("payment_method_data".to_owned(), value);
        self
    }

    /// Payment method-specific configuration for this PaymentIntent.
    #[must_use]
    pub fn payment_method_options(mut self, value: serde_json::Value) -> Self {
        self.params
            .insert("payment_method_options".to_owned(), value);
        self
    }

    /// The list of payment method types (for example, a card) that this PaymentIntent can use. If you don't provide this, Stripe will dynamically show relevant payment methods from your \[payment method settings\](https://dashboard.stripe.com/set…
    #[must_use]
    pub fn payment_method_types(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "payment_method_types".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Options to configure Radar. Learn more about \[Radar Sessions\](https://docs.stripe.com/radar/radar-session).
    #[must_use]
    pub fn radar_options(mut self, value: serde_json::Value) -> Self {
        self.params.insert("radar_options".to_owned(), value);
        self
    }

    /// Email address to send the receipt to. If you specify `receipt_email` for a payment in live mode, you send a receipt regardless of your \[email settings\](https://dashboard.stripe.com/account/emails).
    #[must_use]
    pub fn receipt_email(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "receipt_email".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// The URL to redirect your customer back to after they authenticate or cancel their payment on the payment method's app or site. If you'd prefer to redirect to a mobile application, you can alternatively supply an application URI scheme. Thi…
    #[must_use]
    pub fn return_url(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "return_url".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Indicates that you intend to make future payments with this PaymentIntent's payment method. If you provide a Customer with the PaymentIntent, you can use this parameter to \[attach the payment method\](/payments/save-during-payment) to the…
    #[must_use]
    pub fn setup_future_usage(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "setup_future_usage".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Shipping information for this PaymentIntent.
    #[must_use]
    pub fn shipping(mut self, value: serde_json::Value) -> Self {
        self.params.insert("shipping".to_owned(), value);
        self
    }

    /// Text that appears on the customer's statement as the statement descriptor for a non-card charge. This value overrides the account's default statement descriptor. For information about requirements, including the 22-character limit, see \[t…
    #[must_use]
    pub fn statement_descriptor(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "statement_descriptor".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Provides information about a card charge. Concatenated to the account's \[statement descriptor prefix\](https://docs.stripe.com/get-started/account/statement-descriptors#static) to form the complete statement descriptor that appears on the…
    #[must_use]
    pub fn statement_descriptor_suffix(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "statement_descriptor_suffix".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// The parameters that you can use to automatically create a Transfer. Learn more about the \[use case for connected accounts\](https://docs.stripe.com/payments/connected-accounts).
    #[must_use]
    pub fn transfer_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("transfer_data".to_owned(), value);
        self
    }

    /// A string that identifies the resulting payment as part of a group. Learn more about the \[use case for connected accounts\](https://docs.stripe.com/connect/separate-charges-and-transfers).
    #[must_use]
    pub fn transfer_group(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "transfer_group".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Set to `true` when confirming server-side and using Stripe.js, iOS, or Android client-side SDKs to handle the next actions.
    #[must_use]
    pub fn use_stripe_sdk(mut self, value: bool) -> Self {
        self.params
            .insert("use_stripe_sdk".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::PaymentIntent, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `GET /v1/payment_intents/search`
///
/// Search for PaymentIntents you’ve previously created using Stripe’s Search Query Language. Don’t use search in read-after-write flows where strict consistency is necessary. Under normal operating conditions, data is searchable in less than a minute. Occasionally, propagation of new or updated data can be up to an hour behind during outages. Search functionality is not available to merchants in India.
#[derive(Debug, Clone)]
pub struct GetPaymentIntentsSearch {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetPaymentIntentsSearch {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(query: impl Into<String>) -> Self {
        let mut params = serde_json::Map::new();
        params.insert("query".to_owned(), serde_json::Value::String(query.into()));
        Self {
            path: "/v1/payment_intents/search".to_owned(),
            params,
        }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    #[must_use]
    pub fn limit(mut self, value: i64) -> Self {
        self.params
            .insert("limit".to_owned(), serde_json::Value::from(value));
        self
    }

    /// A cursor for pagination across multiple pages of results. Don't include this parameter on the first call. Use the next_page value returned in a previous response to request subsequent results.
    #[must_use]
    pub fn page(mut self, value: impl Into<String>) -> Self {
        self.params
            .insert("page".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Turn this list request into a cursor [`crate::Paginator`]:
    /// `starting_after` is threaded automatically between pages.
    #[must_use]
    pub fn paginate(self) -> crate::Paginator<crate::models::PaymentIntent> {
        crate::Paginator::new(self.path, self.params)
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<payrs_stripe_types::List<crate::models::PaymentIntent>, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `GET /v1/payment_intents/{intent}`
///
/// Retrieves the details of a PaymentIntent that has previously been created. You can retrieve a PaymentIntent client-side using a publishable key when the client_secret is in the query string. If you retrieve a PaymentIntent with a publishable key, it only returns a subset of properties. Refer to the payment intent object reference for more details.
#[derive(Debug, Clone)]
pub struct GetPaymentIntentsIntent {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetPaymentIntentsIntent {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(intent: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let intent = intent.into();
        Self {
            path: format!("/v1/payment_intents/{intent}"),
            params,
        }
    }

    /// The client secret of the PaymentIntent. We require it if you use a publishable key to retrieve the source.
    #[must_use]
    pub fn client_secret(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "client_secret".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::PaymentIntent, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `POST /v1/payment_intents/{intent}`
///
/// Updates properties on a PaymentIntent object without confirming. Depending on which properties you update, you might need to confirm the PaymentIntent again. For example, updating the payment_method always requires you to confirm the PaymentIntent again. If you prefer to update and confirm at the same time, we recommend updating properties through the confirm API instead.
#[derive(Debug, Clone)]
pub struct PostPaymentIntentsIntent {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostPaymentIntentsIntent {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(intent: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let intent = intent.into();
        Self {
            path: format!("/v1/payment_intents/{intent}"),
            params,
        }
    }

    /// Amount intended to be collected by this PaymentIntent. A positive integer representing how much to charge in the \[smallest currency unit\](https://docs.stripe.com/currencies#zero-decimal) (e.g., 100 cents to charge $1.00 or 100 to charge…
    #[must_use]
    pub fn amount(mut self, value: i64) -> Self {
        self.params
            .insert("amount".to_owned(), serde_json::Value::from(value));
        self
    }

    /// Provides industry-specific information about the amount.
    #[must_use]
    pub fn amount_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("amount_details".to_owned(), value);
        self
    }

    /// The amount of the application fee (if any) that will be requested to be applied to the payment and transferred to the application owner's Stripe account. The amount of the application fee collected will be capped at the total amount captur…
    #[must_use]
    pub fn application_fee_amount(mut self, value: serde_json::Value) -> Self {
        self.params
            .insert("application_fee_amount".to_owned(), value);
        self
    }

    /// Controls when the funds will be captured from the customer's account.
    #[must_use]
    pub fn capture_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "capture_method".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Three-letter \[ISO currency code\](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a \[supported currency\](https://stripe.com/docs/currencies).
    #[must_use]
    pub fn currency(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "currency".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// ID of the Customer this PaymentIntent belongs to, if one exists. Payment methods attached to other Customers cannot be used with this PaymentIntent. If \[setup_future_usage\](https://api.stripe.com#payment_intent_object-setup_future_usage)…
    #[must_use]
    pub fn customer(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "customer".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// ID of the Account representing the customer that this PaymentIntent belongs to, if one exists. Payment methods attached to other Accounts cannot be used with this PaymentIntent. If \[setup_future_usage\](https://api.stripe.com#payment_inte…
    #[must_use]
    pub fn customer_account(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "customer_account".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// An arbitrary string attached to the object. Often useful for displaying to users.
    #[must_use]
    pub fn description(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "description".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// The list of payment method types to exclude from use with this payment.
    #[must_use]
    pub fn excluded_payment_method_types(mut self, value: serde_json::Value) -> Self {
        self.params
            .insert("excluded_payment_method_types".to_owned(), value);
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Automations to be run during the PaymentIntent lifecycle
    #[must_use]
    pub fn hooks(mut self, value: serde_json::Value) -> Self {
        self.params.insert("hooks".to_owned(), value);
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn metadata(mut self, value: serde_json::Value) -> Self {
        self.params.insert("metadata".to_owned(), value);
        self
    }

    /// Provides industry-specific information about the charge.
    #[must_use]
    pub fn payment_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("payment_details".to_owned(), value);
        self
    }

    /// ID of the payment method (a PaymentMethod, Card, or \[compatible Source\](https://docs.stripe.com/payments/payment-methods/transitioning#compatibility) object) to attach to this PaymentIntent. To unset this field to null, pass in an empty…
    #[must_use]
    pub fn payment_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "payment_method".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// The ID of the \[payment method configuration\](https://docs.stripe.com/api/payment_method_configurations) to use with this PaymentIntent.
    #[must_use]
    pub fn payment_method_configuration(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "payment_method_configuration".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// If provided, this hash will be used to create a PaymentMethod. The new PaymentMethod will appear in the \[payment_method\](https://docs.stripe.com/api/payment_intents/object#payment_intent_object-payment_method) property on the PaymentInte…
    #[must_use]
    pub fn payment_method_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("payment_method_data".to_owned(), value);
        self
    }

    /// Payment-method-specific configuration for this PaymentIntent.
    #[must_use]
    pub fn payment_method_options(mut self, value: serde_json::Value) -> Self {
        self.params
            .insert("payment_method_options".to_owned(), value);
        self
    }

    /// The list of payment method types (for example, card) that this PaymentIntent can use. Use `automatic_payment_methods` to manage payment methods from the \[Stripe Dashboard\](https://dashboard.stripe.com/settings/payment_methods). A list of…
    #[must_use]
    pub fn payment_method_types(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "payment_method_types".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Email address that the receipt for the resulting payment will be sent to. If `receipt_email` is specified for a payment in live mode, a receipt will be sent regardless of your \[email settings\](https://dashboard.stripe.com/account/emails).
    #[must_use]
    pub fn receipt_email(mut self, value: serde_json::Value) -> Self {
        self.params.insert("receipt_email".to_owned(), value);
        self
    }

    /// Indicates that you intend to make future payments with this PaymentIntent's payment method. If you provide a Customer with the PaymentIntent, you can use this parameter to \[attach the payment method\](/payments/save-during-payment) to the…
    #[must_use]
    pub fn setup_future_usage(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "setup_future_usage".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Shipping information for this PaymentIntent.
    #[must_use]
    pub fn shipping(mut self, value: serde_json::Value) -> Self {
        self.params.insert("shipping".to_owned(), value);
        self
    }

    /// Text that appears on the customer's statement as the statement descriptor for a non-card charge. This value overrides the account's default statement descriptor. For information about requirements, including the 22-character limit, see \[t…
    #[must_use]
    pub fn statement_descriptor(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "statement_descriptor".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Provides information about a card charge. Concatenated to the account's \[statement descriptor prefix\](https://docs.stripe.com/get-started/account/statement-descriptors#static) to form the complete statement descriptor that appears on the…
    #[must_use]
    pub fn statement_descriptor_suffix(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "statement_descriptor_suffix".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Use this parameter to automatically create a Transfer when the payment succeeds. Learn more about the \[use case for connected accounts\](https://docs.stripe.com/payments/connected-accounts).
    #[must_use]
    pub fn transfer_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("transfer_data".to_owned(), value);
        self
    }

    /// A string that identifies the resulting payment as part of a group. You can only provide `transfer_group` if it hasn't been set. Learn more about the \[use case for connected accounts\](https://docs.stripe.com/payments/connected-accounts).
    #[must_use]
    pub fn transfer_group(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "transfer_group".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::PaymentIntent, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `GET /v1/payment_intents/{intent}/amount_details_line_items`
///
/// Lists all LineItems of a given PaymentIntent.
#[derive(Debug, Clone)]
pub struct GetPaymentIntentsIntentAmountDetailsLineItems {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetPaymentIntentsIntentAmountDetailsLineItems {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(intent: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let intent = intent.into();
        Self {
            path: format!("/v1/payment_intents/{intent}/amount_details_line_items"),
            params,
        }
    }

    /// A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before…
    #[must_use]
    pub fn ending_before(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "ending_before".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    #[must_use]
    pub fn limit(mut self, value: i64) -> Self {
        self.params
            .insert("limit".to_owned(), serde_json::Value::from(value));
        self
    }

    /// A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after…
    #[must_use]
    pub fn starting_after(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "starting_after".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Turn this list request into a cursor [`crate::Paginator`]:
    /// `starting_after` is threaded automatically between pages.
    #[must_use]
    pub fn paginate(self) -> crate::Paginator<crate::models::PaymentIntentAmountDetailsLineItem> {
        crate::Paginator::new(self.path, self.params)
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(
        self,
        client: &Client,
    ) -> Result<payrs_stripe_types::List<crate::models::PaymentIntentAmountDetailsLineItem>, Error>
    {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `POST /v1/payment_intents/{intent}/apply_customer_balance`
///
/// Manually reconcile the remaining amount for a customer_balance PaymentIntent.
#[derive(Debug, Clone)]
pub struct PostPaymentIntentsIntentApplyCustomerBalance {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostPaymentIntentsIntentApplyCustomerBalance {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(intent: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let intent = intent.into();
        Self {
            path: format!("/v1/payment_intents/{intent}/apply_customer_balance"),
            params,
        }
    }

    /// Amount that you intend to apply to this PaymentIntent from the customer’s cash balance. If the PaymentIntent was created by an Invoice, the full amount of the PaymentIntent is applied regardless of this parameter. A positive integer repres…
    #[must_use]
    pub fn amount(mut self, value: i64) -> Self {
        self.params
            .insert("amount".to_owned(), serde_json::Value::from(value));
        self
    }

    /// Three-letter \[ISO currency code\](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a \[supported currency\](https://stripe.com/docs/currencies).
    #[must_use]
    pub fn currency(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "currency".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::PaymentIntent, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/payment_intents/{intent}/cancel`
///
/// You can cancel a PaymentIntent object when it’s in one of these statuses: requires_payment_method, requires_capture, requires_confirmation, requires_action or, in rare cases, processing. After it’s canceled, no additional charges are made by the PaymentIntent and any operations on the PaymentIntent fail with an error. For PaymentIntents with a status of requires_capture, the remaining amount_capturable is automatically refunded. You can directly cancel the PaymentIntent for a Checkout Session o…
#[derive(Debug, Clone)]
pub struct PostPaymentIntentsIntentCancel {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostPaymentIntentsIntentCancel {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(intent: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let intent = intent.into();
        Self {
            path: format!("/v1/payment_intents/{intent}/cancel"),
            params,
        }
    }

    /// Reason for canceling this PaymentIntent. Possible values are: `duplicate`, `fraudulent`, `requested_by_customer`, or `abandoned`
    #[must_use]
    pub fn cancellation_reason(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "cancellation_reason".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::PaymentIntent, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/payment_intents/{intent}/capture`
///
/// Capture the funds of an existing uncaptured PaymentIntent when its status is requires_capture. Uncaptured PaymentIntents are cancelled a set number of days (7 by default) after their creation. Learn more about separate authorization and capture.
#[derive(Debug, Clone)]
pub struct PostPaymentIntentsIntentCapture {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostPaymentIntentsIntentCapture {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(intent: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let intent = intent.into();
        Self {
            path: format!("/v1/payment_intents/{intent}/capture"),
            params,
        }
    }

    /// Provides industry-specific information about the amount.
    #[must_use]
    pub fn amount_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("amount_details".to_owned(), value);
        self
    }

    /// The amount to capture from the PaymentIntent, which must be less than or equal to the original amount. Defaults to the full `amount_capturable` if it's not provided.
    #[must_use]
    pub fn amount_to_capture(mut self, value: i64) -> Self {
        self.params.insert(
            "amount_to_capture".to_owned(),
            serde_json::Value::from(value),
        );
        self
    }

    /// The amount of the application fee (if any) that will be requested to be applied to the payment and transferred to the application owner's Stripe account. The amount of the application fee collected will be capped at the total amount captur…
    #[must_use]
    pub fn application_fee_amount(mut self, value: i64) -> Self {
        self.params.insert(
            "application_fee_amount".to_owned(),
            serde_json::Value::from(value),
        );
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Defaults to `true`. When capturing a PaymentIntent, setting `final_capture` to `false` notifies Stripe to not release the remaining uncaptured funds to make sure that they're captured in future requests. You can only use this setting when…
    #[must_use]
    pub fn final_capture(mut self, value: bool) -> Self {
        self.params
            .insert("final_capture".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// Automations to be run during the PaymentIntent lifecycle
    #[must_use]
    pub fn hooks(mut self, value: serde_json::Value) -> Self {
        self.params.insert("hooks".to_owned(), value);
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn metadata(mut self, value: serde_json::Value) -> Self {
        self.params.insert("metadata".to_owned(), value);
        self
    }

    /// Provides industry-specific information about the charge.
    #[must_use]
    pub fn payment_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("payment_details".to_owned(), value);
        self
    }

    /// Text that appears on the customer's statement as the statement descriptor for a non-card charge. This value overrides the account's default statement descriptor. For information about requirements, including the 22-character limit, see \[t…
    #[must_use]
    pub fn statement_descriptor(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "statement_descriptor".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Provides information about a card charge. Concatenated to the account's \[statement descriptor prefix\](https://docs.stripe.com/get-started/account/statement-descriptors#static) to form the complete statement descriptor that appears on the…
    #[must_use]
    pub fn statement_descriptor_suffix(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "statement_descriptor_suffix".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// The parameters that you can use to automatically create a transfer after the payment is captured. Learn more about the \[use case for connected accounts\](https://docs.stripe.com/payments/connected-accounts).
    #[must_use]
    pub fn transfer_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("transfer_data".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::PaymentIntent, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/payment_intents/{intent}/confirm`
///
/// Confirm that your customer intends to pay with current or provided payment method. Upon confirmation, the PaymentIntent will attempt to initiate a payment. If the selected payment method requires additional authentication steps, the PaymentIntent will transition to the requires_action status and suggest additional actions via next_action. If payment fails, the PaymentIntent transitions to the requires_payment_method status or the canceled status if the confirmation limit is reached. If payment…
#[derive(Debug, Clone)]
pub struct PostPaymentIntentsIntentConfirm {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostPaymentIntentsIntentConfirm {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(intent: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let intent = intent.into();
        Self {
            path: format!("/v1/payment_intents/{intent}/confirm"),
            params,
        }
    }

    /// Provides industry-specific information about the amount.
    #[must_use]
    pub fn amount_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("amount_details".to_owned(), value);
        self
    }

    /// Amount to confirm on the PaymentIntent. Defaults to `amount` if not provided.
    #[must_use]
    pub fn amount_to_confirm(mut self, value: i64) -> Self {
        self.params.insert(
            "amount_to_confirm".to_owned(),
            serde_json::Value::from(value),
        );
        self
    }

    /// Controls when the funds will be captured from the customer's account.
    #[must_use]
    pub fn capture_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "capture_method".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// The client secret of the PaymentIntent.
    #[must_use]
    pub fn client_secret(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "client_secret".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// ID of the ConfirmationToken used to confirm this PaymentIntent. If the provided ConfirmationToken contains properties that are also being provided in this request, such as `payment_method`, then the values in this request will take precede…
    #[must_use]
    pub fn confirmation_token(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "confirmation_token".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Set to `true` to fail the payment attempt if the PaymentIntent transitions into `requires_action`. This parameter is intended for simpler integrations that do not handle customer actions, like \[saving cards without authentication\](https:…
    #[must_use]
    pub fn error_on_requires_action(mut self, value: bool) -> Self {
        self.params.insert(
            "error_on_requires_action".to_owned(),
            serde_json::Value::Bool(value),
        );
        self
    }

    /// The list of payment method types to exclude from use with this payment.
    #[must_use]
    pub fn excluded_payment_method_types(mut self, value: serde_json::Value) -> Self {
        self.params
            .insert("excluded_payment_method_types".to_owned(), value);
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Automations to be run during the PaymentIntent lifecycle
    #[must_use]
    pub fn hooks(mut self, value: serde_json::Value) -> Self {
        self.params.insert("hooks".to_owned(), value);
        self
    }

    /// ID of the mandate that's used for this payment.
    #[must_use]
    pub fn mandate(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "mandate".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Set the `mandate_data` parameter.
    #[must_use]
    pub fn mandate_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("mandate_data".to_owned(), value);
        self
    }

    /// Set to `true` to indicate that the customer isn't in your checkout flow during this payment attempt and can't authenticate. Use this parameter in scenarios where you collect payment method details and \[charge them later\](https://docs.str…
    #[must_use]
    pub fn off_session(mut self, value: serde_json::Value) -> Self {
        self.params.insert("off_session".to_owned(), value);
        self
    }

    /// Provides industry-specific information about the charge.
    #[must_use]
    pub fn payment_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("payment_details".to_owned(), value);
        self
    }

    /// ID of the payment method (a PaymentMethod, Card, or \[compatible Source\](https://docs.stripe.com/payments/payment-methods/transitioning#compatibility) object) to attach to this PaymentIntent. If the payment method is attached to a Custome…
    #[must_use]
    pub fn payment_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "payment_method".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// If provided, this hash will be used to create a PaymentMethod. The new PaymentMethod will appear in the \[payment_method\](https://docs.stripe.com/api/payment_intents/object#payment_intent_object-payment_method) property on the PaymentInte…
    #[must_use]
    pub fn payment_method_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("payment_method_data".to_owned(), value);
        self
    }

    /// Payment method-specific configuration for this PaymentIntent.
    #[must_use]
    pub fn payment_method_options(mut self, value: serde_json::Value) -> Self {
        self.params
            .insert("payment_method_options".to_owned(), value);
        self
    }

    /// The list of payment method types (for example, a card) that this PaymentIntent can use. Use `automatic_payment_methods` to manage payment methods from the \[Stripe Dashboard\](https://dashboard.stripe.com/settings/payment_methods). A list…
    #[must_use]
    pub fn payment_method_types(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "payment_method_types".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Options to configure Radar. Learn more about \[Radar Sessions\](https://docs.stripe.com/radar/radar-session).
    #[must_use]
    pub fn radar_options(mut self, value: serde_json::Value) -> Self {
        self.params.insert("radar_options".to_owned(), value);
        self
    }

    /// Email address that the receipt for the resulting payment will be sent to. If `receipt_email` is specified for a payment in live mode, a receipt will be sent regardless of your \[email settings\](https://dashboard.stripe.com/account/emails).
    #[must_use]
    pub fn receipt_email(mut self, value: serde_json::Value) -> Self {
        self.params.insert("receipt_email".to_owned(), value);
        self
    }

    /// The URL to redirect your customer back to after they authenticate or cancel their payment on the payment method's app or site. If you'd prefer to redirect to a mobile application, you can alternatively supply an application URI scheme. Thi…
    #[must_use]
    pub fn return_url(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "return_url".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Indicates that you intend to make future payments with this PaymentIntent's payment method. If you provide a Customer with the PaymentIntent, you can use this parameter to \[attach the payment method\](/payments/save-during-payment) to the…
    #[must_use]
    pub fn setup_future_usage(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "setup_future_usage".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Shipping information for this PaymentIntent.
    #[must_use]
    pub fn shipping(mut self, value: serde_json::Value) -> Self {
        self.params.insert("shipping".to_owned(), value);
        self
    }

    /// Set to `true` when confirming server-side and using Stripe.js, iOS, or Android client-side SDKs to handle the next actions.
    #[must_use]
    pub fn use_stripe_sdk(mut self, value: bool) -> Self {
        self.params
            .insert("use_stripe_sdk".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::PaymentIntent, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/payment_intents/{intent}/increment_authorization`
///
/// Perform an incremental authorization on an eligible PaymentIntent. To be eligible, the PaymentIntent’s status must be requires_capture and incremental_authorization_supported must be true. Incremental authorizations attempt to increase the authorized amount on your customer’s card to the new, higher amount provided. Similar to the initial authorization, incremental authorizations can be declined. A single PaymentIntent can call this endpoint multiple times to further increase the authorized amo…
#[derive(Debug, Clone)]
pub struct PostPaymentIntentsIntentIncrementAuthorization {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostPaymentIntentsIntentIncrementAuthorization {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(intent: impl Into<String>, amount: i64) -> Self {
        let mut params = serde_json::Map::new();
        let intent = intent.into();
        params.insert("amount".to_owned(), serde_json::Value::from(amount));
        Self {
            path: format!("/v1/payment_intents/{intent}/increment_authorization"),
            params,
        }
    }

    /// Provides industry-specific information about the amount.
    #[must_use]
    pub fn amount_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("amount_details".to_owned(), value);
        self
    }

    /// The amount of the application fee (if any) that will be requested to be applied to the payment and transferred to the application owner's Stripe account. The amount of the application fee collected will be capped at the total amount captur…
    #[must_use]
    pub fn application_fee_amount(mut self, value: i64) -> Self {
        self.params.insert(
            "application_fee_amount".to_owned(),
            serde_json::Value::from(value),
        );
        self
    }

    /// An arbitrary string attached to the object. Often useful for displaying to users.
    #[must_use]
    pub fn description(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "description".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Automations to be run during the PaymentIntent lifecycle
    #[must_use]
    pub fn hooks(mut self, value: serde_json::Value) -> Self {
        self.params.insert("hooks".to_owned(), value);
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn metadata(mut self, value: std::collections::BTreeMap<String, String>) -> Self {
        self.params.insert(
            "metadata".to_owned(),
            serde_json::Value::Object(
                value
                    .into_iter()
                    .map(|(k, v)| (k, serde_json::Value::String(v)))
                    .collect(),
            ),
        );
        self
    }

    /// Provides industry-specific information about the charge.
    #[must_use]
    pub fn payment_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("payment_details".to_owned(), value);
        self
    }

    /// Text that appears on the customer's statement as the statement descriptor for a non-card or card charge. This value overrides the account's default statement descriptor. For information about requirements, including the 22-character limit,…
    #[must_use]
    pub fn statement_descriptor(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "statement_descriptor".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// The parameters used to automatically create a transfer after the payment is captured. Learn more about the \[use case for connected accounts\](https://docs.stripe.com/payments/connected-accounts).
    #[must_use]
    pub fn transfer_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("transfer_data".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::PaymentIntent, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/payment_intents/{intent}/verify_microdeposits`
///
/// Verifies microdeposits on a PaymentIntent object.
#[derive(Debug, Clone)]
pub struct PostPaymentIntentsIntentVerifyMicrodeposits {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostPaymentIntentsIntentVerifyMicrodeposits {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(intent: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let intent = intent.into();
        Self {
            path: format!("/v1/payment_intents/{intent}/verify_microdeposits"),
            params,
        }
    }

    /// Two positive integers, in *cents*, equal to the values of the microdeposits sent to the bank account.
    #[must_use]
    pub fn amounts(mut self, value: serde_json::Value) -> Self {
        self.params.insert("amounts".to_owned(), value);
        self
    }

    /// The client secret of the PaymentIntent.
    #[must_use]
    pub fn client_secret(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "client_secret".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// A six-character code starting with SM present in the microdeposit sent to the bank account.
    #[must_use]
    pub fn descriptor_code(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "descriptor_code".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::PaymentIntent, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}
