//! Generated operations for the `subscriptions` section of the Stripe v1 API.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(clippy::doc_markdown, clippy::too_many_arguments, clippy::new_without_default, rustdoc::bare_urls)]

use payrs_stripe_client::{Body, Client, Error, Method, RequestSpec};

/// `GET /v1/subscriptions`
///
/// By default, returns a list of subscriptions that have not been canceled. In order to list canceled subscriptions, specify status=canceled.
#[derive(Debug, Clone)]
pub struct GetSubscriptions {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetSubscriptions {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new() -> Self {
        let params = serde_json::Map::new();
        Self { path: "/v1/subscriptions".to_owned(), params }
    }

    /// Filter subscriptions by their automatic tax settings.
    #[must_use]
    pub fn automatic_tax(mut self, value: serde_json::Value) -> Self {
        self.params.insert("automatic_tax".to_owned(), value);
        self
    }

    /// The collection method of the subscriptions to retrieve. Either `charge_automatically` or `send_invoice`.
    #[must_use]
    pub fn collection_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert("collection_method".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Only return subscriptions that were created during the given date interval.
    #[must_use]
    pub fn created(mut self, value: serde_json::Value) -> Self {
        self.params.insert("created".to_owned(), value);
        self
    }

    /// Only return subscriptions whose minimum item current_period_end falls within the given date interval.
    #[must_use]
    pub fn current_period_end(mut self, value: serde_json::Value) -> Self {
        self.params.insert("current_period_end".to_owned(), value);
        self
    }

    /// Only return subscriptions whose maximum item current_period_start falls within the given date interval.
    #[must_use]
    pub fn current_period_start(mut self, value: serde_json::Value) -> Self {
        self.params.insert("current_period_start".to_owned(), value);
        self
    }

    /// The ID of the customer whose subscriptions you're retrieving.
    #[must_use]
    pub fn customer(mut self, value: impl Into<String>) -> Self {
        self.params.insert("customer".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The ID of the account representing the customer whose subscriptions you're retrieving.
    #[must_use]
    pub fn customer_account(mut self, value: impl Into<String>) -> Self {
        self.params.insert("customer_account".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before…
    #[must_use]
    pub fn ending_before(mut self, value: impl Into<String>) -> Self {
        self.params.insert("ending_before".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    #[must_use]
    pub fn limit(mut self, value: i64) -> Self {
        self.params.insert("limit".to_owned(), serde_json::Value::from(value));
        self
    }

    /// Filter for subscriptions that contain this recurring price ID.
    #[must_use]
    pub fn price(mut self, value: impl Into<String>) -> Self {
        self.params.insert("price".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after…
    #[must_use]
    pub fn starting_after(mut self, value: impl Into<String>) -> Self {
        self.params.insert("starting_after".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The status of the subscriptions to retrieve. Passing in a value of `canceled` will return all canceled subscriptions, including those belonging to deleted customers. Pass `ended` to find subscriptions that are canceled and subscriptions th…
    #[must_use]
    pub fn status(mut self, value: impl Into<String>) -> Self {
        self.params.insert("status".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Filter for subscriptions that are associated with the specified test clock. The response will not include subscriptions with test clocks if this and the customer parameter is not set.
    #[must_use]
    pub fn test_clock(mut self, value: impl Into<String>) -> Self {
        self.params.insert("test_clock".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Turn this list request into a cursor [`crate::Paginator`]:
    /// `starting_after` is threaded automatically between pages.
    #[must_use]
    pub fn paginate(self) -> crate::Paginator<crate::models::Subscription> {
        crate::Paginator::new(self.path, self.params)
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<payrs_stripe_types::List<crate::models::Subscription>, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `POST /v1/subscriptions`
///
/// Creates a new subscription on an existing customer. Each customer can have up to 500 active or scheduled subscriptions. When you create a subscription with collection_method=charge_automatically, the first invoice is finalized as part of the request. The payment_behavior parameter determines the exact behavior of the initial payment. To start subscriptions where the first invoice always begins in a draft status, use subscription schedules instead. Schedules provide the flexibility to model more…
#[derive(Debug, Clone)]
pub struct PostSubscriptions {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostSubscriptions {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new() -> Self {
        let params = serde_json::Map::new();
        Self { path: "/v1/subscriptions".to_owned(), params }
    }

    /// A list of prices and quantities that will generate invoice items appended to the next invoice for this subscription. You may pass up to 20 items.
    #[must_use]
    pub fn add_invoice_items(mut self, value: serde_json::Value) -> Self {
        self.params.insert("add_invoice_items".to_owned(), value);
        self
    }

    /// A non-negative decimal between 0 and 100, with at most two decimal places. This represents the percentage of the subscription invoice total that will be transferred to the application owner's Stripe account. The request must be made by a p…
    #[must_use]
    pub fn application_fee_percent(mut self, value: serde_json::Value) -> Self {
        self.params.insert("application_fee_percent".to_owned(), value);
        self
    }

    /// Automatic tax settings for this subscription.
    #[must_use]
    pub fn automatic_tax(mut self, value: serde_json::Value) -> Self {
        self.params.insert("automatic_tax".to_owned(), value);
        self
    }

    /// A past timestamp to backdate the subscription's start date to. If set, the first invoice will contain line items for the timespan between the start date and the current time. Can be combined with trials and the billing cycle anchor.
    #[must_use]
    pub fn backdate_start_date(mut self, value: i64) -> Self {
        self.params.insert("backdate_start_date".to_owned(), serde_json::Value::from(value));
        self
    }

    /// A future timestamp in UTC format to anchor the subscription's \[billing cycle\](https://docs.stripe.com/subscriptions/billing-cycle). The anchor is the reference point that aligns future billing cycle dates. It sets the day of week for `we…
    #[must_use]
    pub fn billing_cycle_anchor(mut self, value: i64) -> Self {
        self.params.insert("billing_cycle_anchor".to_owned(), serde_json::Value::from(value));
        self
    }

    /// Mutually exclusive with billing_cycle_anchor and only valid with monthly and yearly price intervals. When provided, the billing_cycle_anchor is set to the next occurrence of the day_of_month at the hour, minute, and second UTC.
    #[must_use]
    pub fn billing_cycle_anchor_config(mut self, value: serde_json::Value) -> Self {
        self.params.insert("billing_cycle_anchor_config".to_owned(), value);
        self
    }

    /// Controls how prorations and invoices for subscriptions are calculated and orchestrated.
    #[must_use]
    pub fn billing_mode(mut self, value: serde_json::Value) -> Self {
        self.params.insert("billing_mode".to_owned(), value);
        self
    }

    /// Sets the billing schedules for the subscription.
    #[must_use]
    pub fn billing_schedules(mut self, value: serde_json::Value) -> Self {
        self.params.insert("billing_schedules".to_owned(), value);
        self
    }

    /// Define thresholds at which an invoice will be sent, and the subscription advanced to a new billing period. When updating, pass an empty string to remove previously-defined thresholds.
    #[must_use]
    pub fn billing_thresholds(mut self, value: serde_json::Value) -> Self {
        self.params.insert("billing_thresholds".to_owned(), value);
        self
    }

    /// A timestamp at which the subscription should cancel. If set to a date before the current period ends, this will cause a proration if prorations have been enabled using `proration_behavior`. If set during a future period, this will always c…
    #[must_use]
    pub fn cancel_at(mut self, value: serde_json::Value) -> Self {
        self.params.insert("cancel_at".to_owned(), value);
        self
    }

    /// Indicate whether this subscription should cancel at the end of the current period (`current_period_end`). Defaults to `false`.
    #[must_use]
    pub fn cancel_at_period_end(mut self, value: bool) -> Self {
        self.params.insert("cancel_at_period_end".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// Either `charge_automatically`, or `send_invoice`. When charging automatically, Stripe will attempt to pay this subscription at the end of the cycle using the default source attached to the customer. When sending an invoice, Stripe will ema…
    #[must_use]
    pub fn collection_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert("collection_method".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Three-letter \[ISO currency code\](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a \[supported currency\](https://stripe.com/docs/currencies).
    #[must_use]
    pub fn currency(mut self, value: impl Into<String>) -> Self {
        self.params.insert("currency".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The identifier of the customer to subscribe.
    #[must_use]
    pub fn customer(mut self, value: impl Into<String>) -> Self {
        self.params.insert("customer".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The identifier of the account representing the customer to subscribe.
    #[must_use]
    pub fn customer_account(mut self, value: impl Into<String>) -> Self {
        self.params.insert("customer_account".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Number of days a customer has to pay invoices generated by this subscription. Valid only for subscriptions where `collection_method` is set to `send_invoice`.
    #[must_use]
    pub fn days_until_due(mut self, value: i64) -> Self {
        self.params.insert("days_until_due".to_owned(), serde_json::Value::from(value));
        self
    }

    /// ID of the default payment method for the subscription. It must belong to the customer associated with the subscription. This takes precedence over `default_source`. If neither are set, invoices will use the customer's \[invoice_settings.de…
    #[must_use]
    pub fn default_payment_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert("default_payment_method".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// ID of the default payment source for the subscription. It must belong to the customer associated with the subscription and be in a chargeable state. If `default_payment_method` is also set, `default_payment_method` will take precedence. If…
    #[must_use]
    pub fn default_source(mut self, value: impl Into<String>) -> Self {
        self.params.insert("default_source".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The tax rates that will apply to any subscription item that does not have `tax_rates` set. Invoices created will have their `default_tax_rates` populated from the subscription.
    #[must_use]
    pub fn default_tax_rates(mut self, value: serde_json::Value) -> Self {
        self.params.insert("default_tax_rates".to_owned(), value);
        self
    }

    /// The subscription's description, meant to be displayable to the customer. Use this field to optionally store an explanation of the subscription for rendering in Stripe surfaces and certain local payment methods UIs.
    #[must_use]
    pub fn description(mut self, value: impl Into<String>) -> Self {
        self.params.insert("description".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// The coupons to redeem into discounts for the subscription. If not specified or empty, inherits the discount from the subscription's customer.
    #[must_use]
    pub fn discounts(mut self, value: serde_json::Value) -> Self {
        self.params.insert("discounts".to_owned(), value);
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// All invoices will be billed using the specified settings.
    #[must_use]
    pub fn invoice_settings(mut self, value: serde_json::Value) -> Self {
        self.params.insert("invoice_settings".to_owned(), value);
        self
    }

    /// A list of up to 20 subscription items, each with an attached price.
    #[must_use]
    pub fn items(mut self, value: serde_json::Value) -> Self {
        self.params.insert("items".to_owned(), value);
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn metadata(mut self, value: serde_json::Value) -> Self {
        self.params.insert("metadata".to_owned(), value);
        self
    }

    /// Indicates if a customer is on or off-session while an invoice payment is attempted. Defaults to `false` (on-session).
    #[must_use]
    pub fn off_session(mut self, value: bool) -> Self {
        self.params.insert("off_session".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// The account on behalf of which to charge, for each of the subscription's invoices.
    #[must_use]
    pub fn on_behalf_of(mut self, value: serde_json::Value) -> Self {
        self.params.insert("on_behalf_of".to_owned(), value);
        self
    }

    /// Controls how Stripe handles the first invoice when payment is required and `collection_method=charge_automatically`. Subscriptions with `collection_method=send_invoice` are automatically activated regardless of the first Invoice status.
    #[must_use]
    pub fn payment_behavior(mut self, value: impl Into<String>) -> Self {
        self.params.insert("payment_behavior".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Payment settings to pass to invoices created by the subscription.
    #[must_use]
    pub fn payment_settings(mut self, value: serde_json::Value) -> Self {
        self.params.insert("payment_settings".to_owned(), value);
        self
    }

    /// Specifies an interval for how often to bill for any pending invoice items. It is analogous to calling \[Create an invoice\](/api/invoices/create) for the given subscription at the specified interval.
    #[must_use]
    pub fn pending_invoice_item_interval(mut self, value: serde_json::Value) -> Self {
        self.params.insert("pending_invoice_item_interval".to_owned(), value);
        self
    }

    /// Determines how to handle \[prorations\](https://docs.stripe.com/billing/subscriptions/prorations) resulting from the `billing_cycle_anchor`. If no value is passed, the default is `create_prorations`.
    #[must_use]
    pub fn proration_behavior(mut self, value: impl Into<String>) -> Self {
        self.params.insert("proration_behavior".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// If specified, the funds from the subscription's invoices will be transferred to the destination and the ID of the resulting transfers will be found on the resulting charges.
    #[must_use]
    pub fn transfer_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("transfer_data".to_owned(), value);
        self
    }

    /// Unix timestamp representing the end of the trial period the customer will get before being charged for the first time. If set, trial_end will override the default trial period of the plan the customer is being subscribed to. The special va…
    #[must_use]
    pub fn trial_end(mut self, value: serde_json::Value) -> Self {
        self.params.insert("trial_end".to_owned(), value);
        self
    }

    /// Indicates if a plan's `trial_period_days` should be applied to the subscription. Setting `trial_end` per subscription is preferred, and this defaults to `false`. Setting this flag to `true` together with `trial_end` is not allowed. See \[U…
    #[must_use]
    pub fn trial_from_plan(mut self, value: bool) -> Self {
        self.params.insert("trial_from_plan".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// Integer representing the number of trial period days before the customer is charged for the first time. This will always overwrite any trials that might apply via a subscribed plan. See \[Using trial periods on subscriptions\](https://docs…
    #[must_use]
    pub fn trial_period_days(mut self, value: i64) -> Self {
        self.params.insert("trial_period_days".to_owned(), serde_json::Value::from(value));
        self
    }

    /// Settings related to subscription trials.
    #[must_use]
    pub fn trial_settings(mut self, value: serde_json::Value) -> Self {
        self.params.insert("trial_settings".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Subscription, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `GET /v1/subscriptions/search`
///
/// Search for subscriptions you’ve previously created using Stripe’s Search Query Language. Don’t use search in read-after-write flows where strict consistency is necessary. Under normal operating conditions, data is searchable in less than a minute. Occasionally, propagation of new or updated data can be up to an hour behind during outages. Search functionality is not available to merchants in India.
#[derive(Debug, Clone)]
pub struct GetSubscriptionsSearch {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetSubscriptionsSearch {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(query: impl Into<String>) -> Self {
        let mut params = serde_json::Map::new();
        params.insert("query".to_owned(), serde_json::Value::String(query.into()));
        Self { path: "/v1/subscriptions/search".to_owned(), params }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    #[must_use]
    pub fn limit(mut self, value: i64) -> Self {
        self.params.insert("limit".to_owned(), serde_json::Value::from(value));
        self
    }

    /// A cursor for pagination across multiple pages of results. Don't include this parameter on the first call. Use the next_page value returned in a previous response to request subsequent results.
    #[must_use]
    pub fn page(mut self, value: impl Into<String>) -> Self {
        self.params.insert("page".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Turn this list request into a cursor [`crate::Paginator`]:
    /// `starting_after` is threaded automatically between pages.
    #[must_use]
    pub fn paginate(self) -> crate::Paginator<crate::models::Subscription> {
        crate::Paginator::new(self.path, self.params)
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<payrs_stripe_types::List<crate::models::Subscription>, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `GET /v1/subscriptions/{subscription_exposed_id}`
///
/// Retrieves the subscription with the given ID.
#[derive(Debug, Clone)]
pub struct GetSubscriptionsSubscriptionExposedId {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetSubscriptionsSubscriptionExposedId {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(subscription_exposed_id: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let subscription_exposed_id = subscription_exposed_id.into();
        Self { path: format!("/v1/subscriptions/{subscription_exposed_id}"), params }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Subscription, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `POST /v1/subscriptions/{subscription_exposed_id}`
///
/// Updates an existing subscription to match the specified parameters. When changing prices or quantities, we optionally prorate the price we charge next month to make up for any price changes. To preview how the proration is calculated, use the create preview endpoint. By default, we prorate subscription changes. For example, if a customer signs up on May 1 for a 100 price, they’ll be billed 100 immediately. If on May 15 they switch to a 200 price, then on June 1 they’ll be billed 250 (200 for a…
#[derive(Debug, Clone)]
pub struct PostSubscriptionsSubscriptionExposedId {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostSubscriptionsSubscriptionExposedId {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(subscription_exposed_id: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let subscription_exposed_id = subscription_exposed_id.into();
        Self { path: format!("/v1/subscriptions/{subscription_exposed_id}"), params }
    }

    /// A list of prices and quantities that will generate invoice items appended to the next invoice for this subscription. You may pass up to 20 items.
    #[must_use]
    pub fn add_invoice_items(mut self, value: serde_json::Value) -> Self {
        self.params.insert("add_invoice_items".to_owned(), value);
        self
    }

    /// A non-negative decimal between 0 and 100, with at most two decimal places. This represents the percentage of the subscription invoice total that will be transferred to the application owner's Stripe account. The request must be made by a p…
    #[must_use]
    pub fn application_fee_percent(mut self, value: serde_json::Value) -> Self {
        self.params.insert("application_fee_percent".to_owned(), value);
        self
    }

    /// Automatic tax settings for this subscription. We recommend you only include this parameter when the existing value is being changed.
    #[must_use]
    pub fn automatic_tax(mut self, value: serde_json::Value) -> Self {
        self.params.insert("automatic_tax".to_owned(), value);
        self
    }

    /// Either `now` or `unchanged`. Setting the value to `now` resets the subscription's billing cycle anchor to the current time (in UTC). For more information, see the billing cycle \[documentation\](https://docs.stripe.com/billing/subscription…
    #[must_use]
    pub fn billing_cycle_anchor(mut self, value: impl Into<String>) -> Self {
        self.params.insert("billing_cycle_anchor".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Sets the billing schedules for the subscription.
    #[must_use]
    pub fn billing_schedules(mut self, value: serde_json::Value) -> Self {
        self.params.insert("billing_schedules".to_owned(), value);
        self
    }

    /// Define thresholds at which an invoice will be sent, and the subscription advanced to a new billing period. When updating, pass an empty string to remove previously-defined thresholds.
    #[must_use]
    pub fn billing_thresholds(mut self, value: serde_json::Value) -> Self {
        self.params.insert("billing_thresholds".to_owned(), value);
        self
    }

    /// A timestamp at which the subscription should cancel. If set to a date before the current period ends, this will cause a proration if prorations have been enabled using `proration_behavior`. If set during a future period, this will always c…
    #[must_use]
    pub fn cancel_at(mut self, value: serde_json::Value) -> Self {
        self.params.insert("cancel_at".to_owned(), value);
        self
    }

    /// Indicate whether this subscription should cancel at the end of the current period (`current_period_end`). Defaults to `false`.
    #[must_use]
    pub fn cancel_at_period_end(mut self, value: bool) -> Self {
        self.params.insert("cancel_at_period_end".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// Details about why this subscription was cancelled
    #[must_use]
    pub fn cancellation_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("cancellation_details".to_owned(), value);
        self
    }

    /// Either `charge_automatically`, or `send_invoice`. When charging automatically, Stripe will attempt to pay this subscription at the end of the cycle using the default source attached to the customer. When sending an invoice, Stripe will ema…
    #[must_use]
    pub fn collection_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert("collection_method".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Number of days a customer has to pay invoices generated by this subscription. Valid only for subscriptions where `collection_method` is set to `send_invoice`.
    #[must_use]
    pub fn days_until_due(mut self, value: i64) -> Self {
        self.params.insert("days_until_due".to_owned(), serde_json::Value::from(value));
        self
    }

    /// ID of the default payment method for the subscription. It must belong to the customer associated with the subscription. This takes precedence over `default_source`. If neither are set, invoices will use the customer's \[invoice_settings.de…
    #[must_use]
    pub fn default_payment_method(mut self, value: impl Into<String>) -> Self {
        self.params.insert("default_payment_method".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// ID of the default payment source for the subscription. It must belong to the customer associated with the subscription and be in a chargeable state. If `default_payment_method` is also set, `default_payment_method` will take precedence. If…
    #[must_use]
    pub fn default_source(mut self, value: serde_json::Value) -> Self {
        self.params.insert("default_source".to_owned(), value);
        self
    }

    /// The tax rates that will apply to any subscription item that does not have `tax_rates` set. Invoices created will have their `default_tax_rates` populated from the subscription. Pass an empty string to remove previously-defined tax rates.
    #[must_use]
    pub fn default_tax_rates(mut self, value: serde_json::Value) -> Self {
        self.params.insert("default_tax_rates".to_owned(), value);
        self
    }

    /// The subscription's description, meant to be displayable to the customer. Use this field to optionally store an explanation of the subscription for rendering in Stripe surfaces and certain local payment methods UIs.
    #[must_use]
    pub fn description(mut self, value: serde_json::Value) -> Self {
        self.params.insert("description".to_owned(), value);
        self
    }

    /// The coupons to redeem into discounts for the subscription. A populated array overwrites the existing discounts on the subscription. If not specified or empty array, it leaves the subscription's discounts unchanged. If empty string, it clea…
    #[must_use]
    pub fn discounts(mut self, value: serde_json::Value) -> Self {
        self.params.insert("discounts".to_owned(), value);
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// All invoices will be billed using the specified settings.
    #[must_use]
    pub fn invoice_settings(mut self, value: serde_json::Value) -> Self {
        self.params.insert("invoice_settings".to_owned(), value);
        self
    }

    /// A list of up to 20 subscription items, each with an attached price.
    #[must_use]
    pub fn items(mut self, value: serde_json::Value) -> Self {
        self.params.insert("items".to_owned(), value);
        self
    }

    /// Set of \[key-value pairs\](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an em…
    #[must_use]
    pub fn metadata(mut self, value: serde_json::Value) -> Self {
        self.params.insert("metadata".to_owned(), value);
        self
    }

    /// Indicates if a customer is on or off-session while an invoice payment is attempted. Defaults to `false` (on-session).
    #[must_use]
    pub fn off_session(mut self, value: bool) -> Self {
        self.params.insert("off_session".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// The account on behalf of which to charge, for each of the subscription's invoices.
    #[must_use]
    pub fn on_behalf_of(mut self, value: serde_json::Value) -> Self {
        self.params.insert("on_behalf_of".to_owned(), value);
        self
    }

    /// If specified, payment collection for this subscription will be paused. Note that the subscription status will be unchanged and will not be updated to `paused`. Learn more about \[pausing collection\](https://docs.stripe.com/billing/subscri…
    #[must_use]
    pub fn pause_collection(mut self, value: serde_json::Value) -> Self {
        self.params.insert("pause_collection".to_owned(), value);
        self
    }

    /// Controls how Stripe handles payment when a subscription update requires payment and `collection_method=charge_automatically`.
    #[must_use]
    pub fn payment_behavior(mut self, value: impl Into<String>) -> Self {
        self.params.insert("payment_behavior".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Payment settings to pass to invoices created by the subscription.
    #[must_use]
    pub fn payment_settings(mut self, value: serde_json::Value) -> Self {
        self.params.insert("payment_settings".to_owned(), value);
        self
    }

    /// Specifies an interval for how often to bill for any pending invoice items. It is analogous to calling \[Create an invoice\](/api/invoices/create) for the given subscription at the specified interval.
    #[must_use]
    pub fn pending_invoice_item_interval(mut self, value: serde_json::Value) -> Self {
        self.params.insert("pending_invoice_item_interval".to_owned(), value);
        self
    }

    /// Determines how to handle \[prorations\](https://docs.stripe.com/billing/subscriptions/prorations) when the billing cycle changes (e.g., when switching plans, resetting `billing_cycle_anchor=now`, or starting a trial), or if an item's `quan…
    #[must_use]
    pub fn proration_behavior(mut self, value: impl Into<String>) -> Self {
        self.params.insert("proration_behavior".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// If set, prorations will be calculated as though the subscription was updated at the given time. This can be used to apply exactly the same prorations that were previewed with the \[create preview\](https://stripe.com/docs/api/invoices/crea…
    #[must_use]
    pub fn proration_date(mut self, value: i64) -> Self {
        self.params.insert("proration_date".to_owned(), serde_json::Value::from(value));
        self
    }

    /// If specified, the funds from the subscription's invoices will be transferred to the destination and the ID of the resulting transfers will be found on the resulting charges. This will be unset if you POST an empty value.
    #[must_use]
    pub fn transfer_data(mut self, value: serde_json::Value) -> Self {
        self.params.insert("transfer_data".to_owned(), value);
        self
    }

    /// Unix timestamp representing the end of the trial period the customer will get before being charged for the first time. This will always overwrite any trials that might apply via a subscribed plan. If set, `trial_end` will override the defa…
    #[must_use]
    pub fn trial_end(mut self, value: serde_json::Value) -> Self {
        self.params.insert("trial_end".to_owned(), value);
        self
    }

    /// Indicates if a plan's `trial_period_days` should be applied to the subscription. Setting `trial_end` per subscription is preferred, and this defaults to `false`. Setting this flag to `true` together with `trial_end` is not allowed. See \[U…
    #[must_use]
    pub fn trial_from_plan(mut self, value: bool) -> Self {
        self.params.insert("trial_from_plan".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// Settings related to subscription trials.
    #[must_use]
    pub fn trial_settings(mut self, value: serde_json::Value) -> Self {
        self.params.insert("trial_settings".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Subscription, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `DELETE /v1/subscriptions/{subscription_exposed_id}`
///
/// Cancels a customer’s subscription immediately. The customer won’t be charged again for the subscription. After it’s canceled, the subscription is largely immutable. You can still update its metadata and cancellation_details. Any pending invoice items that you’ve created are still charged at the end of the period, unless manually deleted. If you’ve set the subscription to cancel at the end of the period, any pending prorations are also left in place and collected at the end of the period. But if…
#[derive(Debug, Clone)]
pub struct DeleteSubscriptionsSubscriptionExposedId {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl DeleteSubscriptionsSubscriptionExposedId {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(subscription_exposed_id: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let subscription_exposed_id = subscription_exposed_id.into();
        Self { path: format!("/v1/subscriptions/{subscription_exposed_id}"), params }
    }

    /// Details about why this subscription was cancelled
    #[must_use]
    pub fn cancellation_details(mut self, value: serde_json::Value) -> Self {
        self.params.insert("cancellation_details".to_owned(), value);
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Will generate a final invoice that invoices for any un-invoiced metered usage and new/pending proration invoice items. Defaults to `false`.
    #[must_use]
    pub fn invoice_now(mut self, value: bool) -> Self {
        self.params.insert("invoice_now".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// Will generate a proration invoice item that credits remaining unused time until the subscription period end. Defaults to `false`.
    #[must_use]
    pub fn prorate(mut self, value: bool) -> Self {
        self.params.insert("prorate".to_owned(), serde_json::Value::Bool(value));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Subscription, Error> {
        let mut spec = RequestSpec::new(Method::Delete, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `DELETE /v1/subscriptions/{subscription_exposed_id}/discount`
///
/// Removes the currently applied discount on a subscription.
#[derive(Debug, Clone)]
pub struct DeleteSubscriptionsSubscriptionExposedIdDiscount {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl DeleteSubscriptionsSubscriptionExposedIdDiscount {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(subscription_exposed_id: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let subscription_exposed_id = subscription_exposed_id.into();
        Self { path: format!("/v1/subscriptions/{subscription_exposed_id}/discount"), params }
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::DeletedDiscount, Error> {
        let mut spec = RequestSpec::new(Method::Delete, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/subscriptions/{subscription}/migrate`
///
/// Upgrade the billing_mode of an existing subscription.
#[derive(Debug, Clone)]
pub struct PostSubscriptionsSubscriptionMigrate {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostSubscriptionsSubscriptionMigrate {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(subscription: impl Into<String>, billing_mode: serde_json::Value) -> Self {
        let mut params = serde_json::Map::new();
        let subscription = subscription.into();
        params.insert("billing_mode".to_owned(), billing_mode);
        Self { path: format!("/v1/subscriptions/{subscription}/migrate"), params }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Subscription, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `POST /v1/subscriptions/{subscription}/resume`
///
/// Initiates resumption of a paused subscription, optionally resetting the billing cycle anchor and creating prorations. Resume is only available for subscriptions that use charge_automatically collection. If Stripe doesn’t generate a resumption invoice, the subscription becomes active immediately. When a resumption invoice is generated, Stripe finalizes it immediately. If the invoice is paid or marked uncollectible, the subscription becomes active. If the invoice is manually voided, the subscript…
#[derive(Debug, Clone)]
pub struct PostSubscriptionsSubscriptionResume {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostSubscriptionsSubscriptionResume {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(subscription: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let subscription = subscription.into();
        Self { path: format!("/v1/subscriptions/{subscription}/resume"), params }
    }

    /// The billing cycle anchor that applies when the subscription is resumed. Either `now` or `unchanged`. The default is `now`. For more information, see the billing cycle \[documentation\](https://docs.stripe.com/billing/subscriptions/billing-…
    #[must_use]
    pub fn billing_cycle_anchor(mut self, value: impl Into<String>) -> Self {
        self.params.insert("billing_cycle_anchor".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Determines how to handle \[prorations\](https://docs.stripe.com/billing/subscriptions/prorations) resulting from the `billing_cycle_anchor` being `unchanged`. When the `billing_cycle_anchor` is set to `now` (default value), no prorations a…
    #[must_use]
    pub fn proration_behavior(mut self, value: impl Into<String>) -> Self {
        self.params.insert("proration_behavior".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// If set, prorations will be calculated as though the subscription was resumed at the given time. This can be used to apply exactly the same prorations that were previewed with the \[create preview\](https://stripe.com/docs/api/invoices/crea…
    #[must_use]
    pub fn proration_date(mut self, value: i64) -> Self {
        self.params.insert("proration_date".to_owned(), serde_json::Value::from(value));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Subscription, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}
