//! Generated operations for the `tax_codes` section of the Stripe v1 API.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(clippy::doc_markdown, clippy::too_many_arguments, clippy::new_without_default, rustdoc::bare_urls)]

use payrs_stripe_client::{Client, Error, Method, RequestSpec};

/// `GET /v1/tax_codes`
///
/// A list of all tax codes available to add to Products in order to allow specific tax calculations.
#[derive(Debug, Clone)]
pub struct GetTaxCodes {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetTaxCodes {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new() -> Self {
        let params = serde_json::Map::new();
        Self { path: "/v1/tax_codes".to_owned(), params }
    }

    /// A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before…
    #[must_use]
    pub fn ending_before(mut self, value: impl Into<String>) -> Self {
        self.params.insert("ending_before".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    #[must_use]
    pub fn limit(mut self, value: i64) -> Self {
        self.params.insert("limit".to_owned(), serde_json::Value::from(value));
        self
    }

    /// A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after…
    #[must_use]
    pub fn starting_after(mut self, value: impl Into<String>) -> Self {
        self.params.insert("starting_after".to_owned(), serde_json::Value::String(value.into()));
        self
    }

    /// Turn this list request into a cursor [`crate::Paginator`]:
    /// `starting_after` is threaded automatically between pages.
    #[must_use]
    pub fn paginate(self) -> crate::Paginator<crate::models::TaxCode> {
        crate::Paginator::new(self.path, self.params)
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<payrs_stripe_types::List<crate::models::TaxCode>, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}

/// `GET /v1/tax_codes/{id}`
///
/// Retrieves the details of an existing tax code. Supply the unique tax code ID and Stripe will return the corresponding tax code information.
#[derive(Debug, Clone)]
pub struct GetTaxCodesId {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetTaxCodesId {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(id: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let id = id.into();
        Self { path: format!("/v1/tax_codes/{id}"), params }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert("expand".to_owned(), serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()));
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::TaxCode, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}
