//! Generated operations for the `tokens` section of the Stripe v1 API.
//!
//! Generated by `codegen/generate.py`. **Do not edit by hand.**
#![allow(
    clippy::doc_markdown,
    clippy::too_many_arguments,
    clippy::new_without_default,
    rustdoc::bare_urls
)]

use payrs_stripe_client::{Body, Client, Error, Method, RequestSpec};

/// `POST /v1/tokens`
///
/// Creates a single-use token that represents a bank account’s details. You can use this token with any v1 API method in place of a bank account dictionary. You can only use this token once. To do so, attach it to a connected account where controller.requirement_collection is application, which includes Custom accounts.
#[derive(Debug, Clone)]
pub struct PostTokens {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl PostTokens {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new() -> Self {
        let params = serde_json::Map::new();
        Self {
            path: "/v1/tokens".to_owned(),
            params,
        }
    }

    /// Information for the account this token represents.
    #[must_use]
    pub fn account(mut self, value: serde_json::Value) -> Self {
        self.params.insert("account".to_owned(), value);
        self
    }

    /// The bank account this token will represent.
    #[must_use]
    pub fn bank_account(mut self, value: serde_json::Value) -> Self {
        self.params.insert("bank_account".to_owned(), value);
        self
    }

    /// The card this token will represent. If you also pass in a customer, the card must be the ID of a card belonging to the customer. Otherwise, if you do not pass in a customer, this is a dictionary containing a user's credit card details, wit…
    #[must_use]
    pub fn card(mut self, value: serde_json::Value) -> Self {
        self.params.insert("card".to_owned(), value);
        self
    }

    /// Create a token for the customer, which is owned by the application's account. You can only use this with an \[OAuth access token\](https://docs.stripe.com/connect/standard-accounts) or \[Stripe-Account header\](https://docs.stripe.com/conn…
    #[must_use]
    pub fn customer(mut self, value: impl Into<String>) -> Self {
        self.params.insert(
            "customer".to_owned(),
            serde_json::Value::String(value.into()),
        );
        self
    }

    /// The updated CVC value this token represents.
    #[must_use]
    pub fn cvc_update(mut self, value: serde_json::Value) -> Self {
        self.params.insert("cvc_update".to_owned(), value);
        self
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Information for the person this token represents.
    #[must_use]
    pub fn person(mut self, value: serde_json::Value) -> Self {
        self.params.insert("person".to_owned(), value);
        self
    }

    /// The PII this token represents.
    #[must_use]
    pub fn pii(mut self, value: serde_json::Value) -> Self {
        self.params.insert("pii".to_owned(), value);
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Token, Error> {
        let mut spec = RequestSpec::new(Method::Post, self.path);
        if let Some(body) = crate::encode_params(&self.params)? {
            spec.body = Some(Body::Form(body));
        }
        client.execute(spec).await
    }
}

/// `GET /v1/tokens/{token}`
///
/// Retrieves the token with the given ID.
#[derive(Debug, Clone)]
pub struct GetTokensToken {
    path: String,
    params: serde_json::Map<String, serde_json::Value>,
}

impl GetTokensToken {
    /// Start building this request. Required parameters are arguments;
    /// everything optional is a chainable setter.
    #[must_use]
    pub fn new(token: impl Into<String>) -> Self {
        let params = serde_json::Map::new();
        let token = token.into();
        Self {
            path: format!("/v1/tokens/{token}"),
            params,
        }
    }

    /// Specifies which fields in the response should be expanded.
    #[must_use]
    pub fn expand(mut self, value: Vec<String>) -> Self {
        self.params.insert(
            "expand".to_owned(),
            serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect()),
        );
        self
    }

    /// Set any parameter by name — the escape hatch for params newer
    /// than this generated code or deeply nested shapes.
    #[must_use]
    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.params.insert(key.into(), value);
        self
    }

    /// Send the request.
    ///
    /// # Errors
    /// See [`payrs_stripe_client::Error`]: API errors, transport errors
    /// after retries, or response deserialization failures.
    pub async fn send(self, client: &Client) -> Result<crate::models::Token, Error> {
        let mut spec = RequestSpec::new(Method::Get, self.path);
        spec.raw_query = crate::encode_params(&self.params)?;
        client.execute(spec).await
    }
}
