#!/usr/bin/env python3
"""payrs-stripe codegen v0: Stripe OpenAPI spec -> payrs-stripe-api crate.

Generates:
  * models.rs   — a struct per component schema (1,400+), all fields Option
                  for forward-compatibility, serde derives, doc comments.
  * v1/<section>.rs — an operation builder per path+method (587 ops): typed
                  setters for top-level params, path-param substitution,
                  form/query encoding, typed responses where the spec gives
                  a schema $ref (List<T> for list endpoints).

Run: python3 codegen/generate.py   (re-run after bumping codegen/spec3.json)
"""
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = json.load(open(Path(__file__).resolve().parent / "spec3.json"))
OUT = ROOT / "crates" / "payrs-stripe-api" / "src"

RUST_KEYWORDS = {
    "as", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern",
    "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod",
    "move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct",
    "super", "trait", "true", "type", "unsafe", "use", "where", "while", "async",
    "await", "abstract", "become", "box", "do", "final", "macro", "override",
    "priv", "typeof", "unsized", "virtual", "yield", "try", "gen",
}


def pascal(name: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", name)
    out = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if out and out[0].isdigit():
        out = "N" + out
    return out


def field_ident(name: str) -> tuple[str, bool]:
    """snake ident + whether a serde rename is needed."""
    ident = re.sub(r"[^A-Za-z0-9_]", "_", name)
    renamed = ident != name
    if ident in RUST_KEYWORDS:
        ident += "_"
        renamed = True
    if ident and ident[0].isdigit():
        ident = "n" + ident
        renamed = True
    return ident, renamed


def mod_ident(name: str) -> str:
    ident = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").lower()
    if not ident:
        ident = "root"
    if ident[0].isdigit():
        ident = "n" + ident
    if ident in RUST_KEYWORDS:
        ident += "_"
    return ident


def sanitize_doc(text: str, limit: int = 400) -> str:
    if not text:
        return ""
    text = re.sub(r"<[^>]+>", "", text)  # strip HTML tags
    text = text.replace("[", r"\[").replace("]", r"\]")
    text = text.replace("<", r"\<").replace(">", r"\>")
    text = " ".join(text.split())
    if len(text) > limit:
        text = text[: limit - 1].rstrip() + "…"
    return text


def doc_lines(text: str, indent: str = "", limit: int = 400) -> list[str]:
    s = sanitize_doc(text, limit)
    return [f"{indent}/// {s}"] if s else []


SCHEMAS = SPEC["components"]["schemas"]
SCHEMA_STRUCTS: set[str] = set()  # schema names that become structs


def is_struct_schema(schema: dict) -> bool:
    return schema.get("type") == "object" or "properties" in schema


for name, schema in SCHEMAS.items():
    if is_struct_schema(schema):
        SCHEMA_STRUCTS.add(name)


def rust_type(prop: dict, boxed: bool) -> str:
    """Map a property schema to a Rust type (v0 rules)."""
    if "$ref" in prop:
        target = prop["$ref"].rsplit("/", 1)[-1]
        if target in SCHEMA_STRUCTS:
            t = pascal(target)
            return f"Box<{t}>" if boxed else t
        return "serde_json::Value"
    t = prop.get("type")
    if "anyOf" in prop or "oneOf" in prop or "allOf" in prop:
        return "serde_json::Value"
    if t == "string":
        return "String"
    if t == "integer":
        return "i64"
    if t == "number":
        return "f64"
    if t == "boolean":
        return "bool"
    if t == "array":
        items = prop.get("items", {})
        if "$ref" in items:
            target = items["$ref"].rsplit("/", 1)[-1]
            if target in SCHEMA_STRUCTS:
                return f"Vec<{pascal(target)}>"
        inner = rust_type(items, boxed=False)
        return f"Vec<{inner}>"
    if t == "object":
        ap = prop.get("additionalProperties")
        if isinstance(ap, dict) and ap.get("type") == "string" and "properties" not in prop:
            return "std::collections::BTreeMap<String, String>"
        return "serde_json::Value"
    return "serde_json::Value"


def gen_models() -> str:
    lines = [
        "//! Generated Stripe API object models — one struct per schema in the",
        "//! official OpenAPI spec (full surface).",
        "//!",
        "//! Generated by `codegen/generate.py`. **Do not edit by hand.**",
        "//!",
        "//! Forward-compatibility rules: every field is `Option` (Stripe omits",
        "//! fields by context and adds fields over time), unknown JSON fields",
        "//! are ignored, and expandable/polymorphic fields are",
        "//! `serde_json::Value` in this codegen generation (typed `Expandable`",
        "//! lands with the Tier-1 hand-polished modules).",
        "#![allow(missing_docs, clippy::doc_markdown, clippy::struct_excessive_bools, rustdoc::bare_urls)]",
        "",
        "use serde::{Deserialize, Serialize};",
        "",
    ]
    for name in sorted(SCHEMAS):
        schema = SCHEMAS[name]
        struct_name = pascal(name)
        desc = schema.get("description", "")
        if not is_struct_schema(schema):
            lines += doc_lines(desc)
            lines.append(f"pub type {struct_name} = serde_json::Value;")
            lines.append("")
            continue
        lines += doc_lines(desc)
        lines.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
        lines.append("#[non_exhaustive]")
        lines.append(f"pub struct {struct_name} {{")
        props = schema.get("properties", {}) or {}
        for prop_name in sorted(props):
            prop = props[prop_name]
            ident, renamed = field_ident(prop_name)
            pdoc = sanitize_doc(prop.get("description", ""), 240)
            if pdoc:
                lines.append(f"    /// {pdoc}")
            attrs = ['default', 'skip_serializing_if = "Option::is_none"']
            if renamed:
                attrs.append(f'rename = "{prop_name}"')
            lines.append(f"    #[serde({', '.join(attrs)})]")
            ty = rust_type(prop, boxed=True)
            lines.append(f"    pub {ident}: Option<{ty}>,")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------- operations

PARAM_SCALARS = {"string": "String", "integer": "i64", "number": "f64", "boolean": "bool"}


def setter_type(prop: dict) -> tuple[str, str]:
    """(signature type, conversion expr for `value`)."""
    t = prop.get("type")
    if t == "string":
        return "impl Into<String>", "serde_json::Value::String(value.into())"
    if t == "integer":
        return "i64", "serde_json::Value::from(value)"
    if t == "number":
        return "f64", "serde_json::Value::from(value)"
    if t == "boolean":
        return "bool", "serde_json::Value::Bool(value)"
    if t == "array":
        items = prop.get("items", {})
        if items.get("type") == "string" and "enum" not in items:
            return (
                "Vec<String>",
                "serde_json::Value::Array(value.into_iter().map(serde_json::Value::String).collect())",
            )
        return "serde_json::Value", "value"
    if t == "object":
        ap = prop.get("additionalProperties")
        if isinstance(ap, dict) and ap.get("type") == "string" and "properties" not in prop:
            return (
                "std::collections::BTreeMap<String, String>",
                "serde_json::Value::Object(value.into_iter().map(|(k, v)| (k, serde_json::Value::String(v))).collect())",
            )
    return "serde_json::Value", "value"


def new_arg(prop: dict) -> tuple[str, str]:
    """(type for new() arg, conversion) for required params."""
    return setter_type(prop)


def response_type(op: dict) -> tuple[str, str]:
    """(rust type, kind) where kind in {'model','list','value'}."""
    try:
        schema = op["responses"]["200"]["content"]["application/json"]["schema"]
    except KeyError:
        return "serde_json::Value", "value"
    if "$ref" in schema:
        target = schema["$ref"].rsplit("/", 1)[-1]
        if target in SCHEMA_STRUCTS:
            return f"crate::models::{pascal(target)}", "model"
        return "serde_json::Value", "value"
    props = schema.get("properties", {})
    data = props.get("data", {})
    items = data.get("items", {}) if isinstance(data, dict) else {}
    if "$ref" in items:
        target = items["$ref"].rsplit("/", 1)[-1]
        if target in SCHEMA_STRUCTS:
            return f"payrs_stripe_types::List<crate::models::{pascal(target)}>", "list"
    return "serde_json::Value", "value"


def gen_operation(path: str, method: str, op: dict) -> str:
    op_id = op.get("operationId") or pascal(f"{method}_{path}")
    struct_name = pascal(op_id)
    path_params = [p for p in op.get("parameters", []) if p.get("in") == "path"]
    query_params = [p for p in op.get("parameters", []) if p.get("in") == "query"]

    body_schema = {}
    try:
        body_schema = op["requestBody"]["content"]["application/x-www-form-urlencoded"]["schema"]
    except KeyError:
        pass
    body_props = body_schema.get("properties", {}) or {}
    body_required = set(body_schema.get("required", []) or [])

    if method == "get":
        prop_source = {p["name"]: p.get("schema", {}) for p in query_params}
        required = {p["name"] for p in query_params if p.get("required")}
        prop_docs = {p["name"]: p.get("description", "") for p in query_params}
    else:
        prop_source = body_props
        required = body_required
        prop_docs = {k: v.get("description", "") for k, v in body_props.items()}

    resp_ty, resp_kind = response_type(op)
    lines = []
    summary = sanitize_doc(op.get("description", "") or op.get("summary", ""), 500)
    lines.append(f"/// `{method.upper()} {path}`")
    if summary:
        lines.append("///")
        lines.append(f"/// {summary}")
    lines.append("#[derive(Debug, Clone)]")
    lines.append(f"pub struct {struct_name} {{")
    lines.append("    path: String,")
    lines.append("    params: serde_json::Map<String, serde_json::Value>,")
    lines.append("}")
    lines.append("")
    lines.append(f"impl {struct_name} {{")

    # ---- new()
    args = []
    body_lines = []
    fmt_path = path
    for p in path_params:
        ident, _ = field_ident(p["name"])
        args.append(f"{ident}: impl Into<String>")
        fmt_path = fmt_path.replace("{" + p["name"] + "}", "{" + ident + "}")
        body_lines.append(f"        let {ident} = {ident}.into();")
    required_sorted = sorted(required)
    for name in required_sorted:
        prop = prop_source.get(name, {})
        ident, _ = field_ident(name)
        ty, conv = new_arg(prop)
        args.append(f"{ident}: {ty}")
        conv_expr = conv.replace("value", ident) if "value" in conv else conv
        body_lines.append(
            f'        params.insert("{name}".to_owned(), {conv_expr});'
        )
    lines.append("    /// Start building this request. Required parameters are arguments;")
    lines.append("    /// everything optional is a chainable setter.")
    lines.append("    #[must_use]")
    lines.append(f"    pub fn new({', '.join(args)}) -> Self {{")
    if required_sorted:
        lines.append("        let mut params = serde_json::Map::new();")
    else:
        lines.append("        let params = serde_json::Map::new();")
    lines += body_lines
    if path_params:
        lines.append(f'        Self {{ path: format!("{fmt_path}"), params }}')
    else:
        lines.append(f'        Self {{ path: "{path}".to_owned(), params }}')
    lines.append("    }")

    # ---- setters
    used = set()
    for name in sorted(prop_source):
        if name in required:
            continue
        prop = prop_source[name]
        ident, _ = field_ident(name)
        if ident in used:
            continue
        used.add(ident)
        ty, conv = setter_type(prop)
        pdoc = sanitize_doc(prop_docs.get(name, ""), 240)
        lines.append("")
        if pdoc:
            lines.append(f"    /// {pdoc}")
        else:
            lines.append(f"    /// Set the `{name}` parameter.")
        lines.append("    #[must_use]")
        lines.append(f"    pub fn {ident}(mut self, value: {ty}) -> Self {{")
        lines.append(f'        self.params.insert("{name}".to_owned(), {conv});')
        lines.append("        self")
        lines.append("    }")

    # ---- paginate (list endpoints only)
    if resp_kind == "list":
        item_ty = resp_ty[len("payrs_stripe_types::List<"):-1]
        lines.append("")
        lines.append("    /// Turn this list request into a cursor [`crate::Paginator`]:")
        lines.append("    /// `starting_after` is threaded automatically between pages.")
        lines.append("    #[must_use]")
        lines.append(f"    pub fn paginate(self) -> crate::Paginator<{item_ty}> {{")
        lines.append("        crate::Paginator::new(self.path, self.params)")
        lines.append("    }")

    # ---- escape hatch + send
    lines.append("")
    lines.append("    /// Set any parameter by name — the escape hatch for params newer")
    lines.append("    /// than this generated code or deeply nested shapes.")
    lines.append("    #[must_use]")
    lines.append("    pub fn param(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {")
    lines.append("        self.params.insert(key.into(), value);")
    lines.append("        self")
    lines.append("    }")
    lines.append("")
    method_variant = {"get": "Get", "post": "Post", "delete": "Delete"}[method]
    lines.append("    /// Send the request.")
    lines.append("    ///")
    lines.append("    /// # Errors")
    lines.append("    /// See [`payrs_stripe_client::Error`]: API errors, transport errors")
    lines.append("    /// after retries, or response deserialization failures.")
    lines.append(f"    pub async fn send(self, client: &Client) -> Result<{resp_ty}, Error> {{")
    lines.append(f"        let mut spec = RequestSpec::new(Method::{method_variant}, self.path);")
    if method == "get":
        lines.append("        spec.raw_query = crate::encode_params(&self.params)?;")
    else:
        lines.append("        if let Some(body) = crate::encode_params(&self.params)? {")
        lines.append("            spec.body = Some(Body::Form(body));")
        lines.append("        }")
    lines.append("        client.execute(spec).await")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "models.rs").write_text(gen_models())

    sections: dict[str, list[str]] = defaultdict(list)
    op_count = 0
    for path in sorted(SPEC["paths"]):
        if not path.startswith("/v1/"):
            continue
        section = mod_ident(path.split("/")[2])
        for method in ("get", "post", "delete"):
            op = SPEC["paths"][path].get(method)
            if not op:
                continue
            sections[section].append(gen_operation(path, method, op))
            op_count += 1

    v1_dir = OUT / "v1"
    v1_dir.mkdir(exist_ok=True)
    mod_lines = [
        "//! Generated typed operations for the Stripe **v1** namespace — full",
        "//! surface, one module per API section.",
        "//!",
        "//! Generated by `codegen/generate.py`. **Do not edit by hand.**",
        "",
    ]
    for section in sorted(sections):
        code = "\n".join(sections[section])
        imports = (
            "use payrs_stripe_client::{Body, Client, Error, Method, RequestSpec};"
            if "Body::Form" in code
            else "use payrs_stripe_client::{Client, Error, Method, RequestSpec};"
        )
        header = (
            "//! Generated operations for the `"
            + section
            + "` section of the Stripe v1 API.\n"
            + "//!\n//! Generated by `codegen/generate.py`. **Do not edit by hand.**\n"
            + "#![allow(clippy::doc_markdown, clippy::too_many_arguments, clippy::new_without_default, rustdoc::bare_urls)]\n\n"
            + imports + "\n\n"
        )
        (v1_dir / f"{section}.rs").write_text(header + code)
        mod_lines.append(f"pub mod {section};")
    (v1_dir / "mod.rs").write_text("\n".join(mod_lines) + "\n")

    # Auditable coverage report: every operation, grouped by section.
    report = [
        "# API coverage report",
        "",
        "Generated by `codegen/generate.py` from the vendored official OpenAPI",
        f"spec. **{op_count} operations across {len(sections)} sections; "
        f"{len(SCHEMAS)} models.** Every operation below has a typed builder",
        "in `payrs_stripe::api::v1`; every schema is exported from",
        "`payrs_stripe::models`.",
        "",
    ]
    for path in sorted(SPEC["paths"]):
        if not path.startswith("/v1/"):
            continue
        for method in ("get", "post", "delete"):
            op = SPEC["paths"][path].get(method)
            if not op:
                continue
            section = mod_ident(path.split("/")[2])
            builder = pascal(op.get("operationId") or f"{method}_{path}")
            report.append(f"- `{method.upper()} {path}` → `v1::{section}::{builder}`")
    report += [
        "",
        "## v2 namespace",
        "",
        "- `GET /v2/core/events` → `v2::ListEvents`",
        "- `GET /v2/core/events/{id}` → `v2::RetrieveEvent`",
        "- `POST /v2/core/event_destinations` → `v2::CreateEventDestination`",
        "- any other `/v2/…` endpoint → raw client with `.json(&body)`",
        "",
    ]
    (ROOT / "docs" / "coverage.md").write_text("\n".join(report))
    print(f"generated {len(SCHEMAS)} models, {op_count} operations, {len(sections)} sections + docs/coverage.md")

    # Keep generated output rustfmt-clean (best effort; CI enforces).
    import subprocess
    try:
        subprocess.run(["cargo", "fmt", "--package", "payrs-stripe-api"], cwd=ROOT, check=False)
        print("formatted generated code with cargo fmt")
    except OSError:
        print("note: cargo fmt unavailable; run `cargo fmt --all` before committing")


if __name__ == "__main__":
    sys.exit(main())
